### ISSUE TITLE
Arduino support

### ISSUE THREAD

**Issue by didrocks** [ubuntu/ubuntu-make#102]
From https://bugs.launchpad.net/ubuntu/+source/ubuntu-make/+bug/1452440:

I think is a good idea if Ubuntu Make can install Arduino official IDE automagically. The version packaged is very old (1.0 in repository instead 1.6 from website) and is hard to put to work the website version (create a link for executable, create a .desktop file, etc.)

**Comment by didrocks** [comment]
I guess this a good idea, maybe a simple thing for a new contributor?

**Comment by Tinche** [comment]
I can take a look over the weekend if it's not hard... Been a while since
I've done anything :)

**Comment by didrocks** [comment]
I would be delighted! I unfortunately don't have any arduino hardware to do a proper decision job on this :)

**Comment by Tinche** [comment]
Ugh, me neither. I hope just downloading (without testing on real hardware)
will be enough to be useful for someone.

**Comment by didrocks** [comment]
I think my manager has some hardware, I'll ask him to give it a try with your PR!

**Comment by mhalano** [comment]
I don't think an Arduino board is really necessary for this task. The idea is just install the IDE, but there is a trick related with the serial communication, so the user need to be added in the 'dialout' group. But already exist a package .deb, so a look into that solve most problems.

**Comment by didrocks** [comment]
This was is now released as of Ubuntu Make 0.9
