### ISSUE TITLE
Support gdevelop

### ISSUE THREAD

**Issue by popey** [ubuntu/ubuntu-make#106]
http://www.compilgames.net/ gdevelop is available for Ubuntu via a PPA, but perhaps could be supported in umake too.

**Comment by didrocks** [comment]
Sounds like an other easy and great opportunity for anyone wanted to jump on helping on ubuntu make!

**Comment by LyzardKing** [comment]
This only has .deb files, so unless they add tarfiles it's on hold.

**Comment by LyzardKing** [comment]
With the latest release of gdevelop this is now possible!
Merged in https://github.com/ubuntu/ubuntu-make/commit/93aedd6db3ac2696c85fad05cf0aff8a7e2e4a27
