### ISSUE TITLE
Android Studio - aidl is missing

### ISSUE THREAD

**Issue by ali1234** [ubuntu/ubuntu-make#108]
Build: 1.2.1.1, AI-141.1903250, 20150505, 

1.7.0_79-b14x64 Oracle Corporation, Linux(amd64) v3.13.0-53-generic unknown (1024x600) 

Steps to reproduce:

1. umake android
2. Install Android Studio, selecting all default settings.
3. At the main menu "Start a new Android Studio project" (first option), selecting all default options and adding a blank activity.
4. Attempt to build the new entirely default empty project (happens automatically).

Expected result: the project builds correctly.

Actual result: build fails because:

    Error:Execution failed for task ':app:compileDebugAidl'.
    > aidl is missing

This could be a bug in Android Studio, but it has been reported many times on the internet over the past few years. This makes me think it is a problem with paths or similar which can have many causes. It is also trivial enough that I would expect to find at least one bug report about it upstream, but I found none. Therefore I have to suspect that it is somehow caused by Ubuntu Make.

**Comment by didrocks** [comment]
Thanks for your bug report.

It seems indeed to be a bug in Android Studio. If you look for the string "aidl is missing" over the Internet, you find this issue for a couple of years in different OS (Mac OS, Windows, Ubuntu). I can't reproduce your issue (it's part of what I'm testing regularly as well).

So I don't think it's an Ubuntu Make bug. It seems to depend on how the sdk was downloaded (did you download source code and the whole platform when setting it up?). Some clue about that were in https://moringaschool.wordpress.com/2015/05/11/that-annoying-aidl-is-missing/, where switching the SDK and redownloading did it for him.

It seems to happen afain with Android M (see this one on MacOs): http://stackoverflow.com/questions/30506406/aidl-is-missing-android-studio

I hope this can help you! :)

**Comment by ali1234** [comment]
I did a fresh install without using Ubuntu Make and got the same problems. Reported here:

https://code.google.com/p/android/issues/detail?id=175027
https://code.google.com/p/android/issues/detail?id=175028
https://code.google.com/p/android/issues/detail?id=175031
