### ISSUE TITLE
Can't parse Android NDK download page.

### ISSUE THREAD

**Issue by ali1234** [ubuntu/ubuntu-make#109]
When attempting to install the Android NDK using 0.8 from the trusty ppa:

    al@al-ideapad:~/Downloads$ umake --verbose android android-ndk
    Choose installation path: /home/al/tools/android/android-ndk
    ERROR: Download page changed its syntax or is not parsable

More verbose log:

    DEBUG: Installation path provided. Checking if exists.
    DEBUG: Download application provider page
    INFO: Start downloading DownloadItem(url='https://developer.android.com/tools/sdk/ndk/index.html', checksum=None, headers=None, ignore_encoding=False) in memory
    INFO: Starting new HTTPS connection (1): developer.android.com
    DEBUG: Setting read timeout to <object object at 0x7fd43c8cf0b0>
    DEBUG: "GET /tools/sdk/ndk/index.html HTTP/1.1" 200 39784
    DEBUG: Deliver download update: {'https://developer.android.com/tools/sdk/ndk/index.html': {'current': 0, 'size': 39784}} of 39784
    DEBUG: Deliver download update: {'https://developer.android.com/tools/sdk/ndk/index.html': {'current': 8192, 'size': 39784}} of 39784
    DEBUG: Deliver download update: {'https://developer.android.com/tools/sdk/ndk/index.html': {'current': 16384, 'size': 39784}} of 39784
    DEBUG: Deliver download update: {'https://developer.android.com/tools/sdk/ndk/index.html': {'current': 24576, 'size': 39784}} of 39784
    DEBUG: Deliver download update: {'https://developer.android.com/tools/sdk/ndk/index.html': {'current': 32768, 'size': 39784}} of 39784
    DEBUG: Deliver download update: {'https://developer.android.com/tools/sdk/ndk/index.html': {'current': 39784, 'size': 39784}} of 39784
    INFO: https://developer.android.com/tools/sdk/ndk/index.html download finished
    INFO: All pending downloads for [DownloadItem(url='https://developer.android.com/tools/sdk/ndk/index.html', checksum=None, headers=None, ignore_encoding=False)] done
    DEBUG: Parse download metadata
    ERROR: Download page changed its syntax or is not parsable

**Comment by didrocks** [comment]
Thanks for the bug report and help to make ubuntu make better.

You are completely right (the tests results shows that it broke over the week-end). I think the android developer sdk page changed recently. I'll look at it shortly and keep you posted! Sorry for the issue.

**Comment by didrocks** [comment]
Released and fixed in 0.8.1, please give it a try! :)
