### ISSUE TITLE
The Eclipse downloaded via umake does not have Maven support integrated.

### ISSUE THREAD

**Issue by aghasemi** [ubuntu/ubuntu-make#110]
whereas the eclipse I downloaded from the eclipse website has Maven support in it. Would be great if you add it too.
Thanks
Best

**Comment by lagerspetz** [comment]
http://scala-ide.org/ I use Scala, and would like support for Scala-IDE, which is basically an Eclipse bundled with scala-ide, maven, maven-scala. This might help you too.
Download page: http://scala-ide.org/download/sdk.html

**Comment by LyzardKing** [comment]
The default eclipse version we download now is the Java edition. That has maven integration included. (see https://www.eclipse.org/downloads/compare.php?release=mars)
If there is any other version needed it should be easy to add them to umake.
