### ISSUE TITLE
umake ide eclipse issue

### ISSUE THREAD

**Issue by siancu** [ubuntu/ubuntu-make#111]
It seems that umake ide eclipse is trying to download the md5 file instead of the tar.gz and it gets an error:

    umake ide eclipse
    Choose installation path: /home/si/tools/ide/eclipse
    ERROR: https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5&r=1 couldn't finish download: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))
    ERROR: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))

**Comment by didrocks** [comment]
Thanks for reporting this bug and help making ubuntu make better!

I wonder if you are not encountering the same bug than bug #107  where eclipse has a badly configured proxy. Do you mind reading this and tell me if this fixed it for you?

**Comment by didrocks** [comment]
Closing as no feedback for now. Please do not hesitate to reopen once you have more informations
