### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by JasonTheAdams** [ubuntu/ubuntu-make#118]
Greetings!

Sorry if this isn't the right place to get help for this. I'm trying to install umake to get android studio up and running. Unfortunately, after adding the PPA, I get this when doing `sudo apt-get install ubuntu-make`:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ubuntu-make : Depends: python3-bs4 but it is not installable
               Depends: python3-progressbar but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I have Python 3.4.0 installed, and when I try `sudo apt-get install python3-bs4` I get:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-bs4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-bs4' has no installation candidate
```

There's something about Ubuntu dependencies that just makes me sad. I'm running Ubuntu 14.04.

Any help and direction is greatly appreciated! I'd really like to give this a shot!

**Comment by syndbg** [comment]
Everyone is sad when we have to resolve Python dependencies with apt-get.

I would recommend you to manually git clone the repo and install the Python dependencies using pip (possibly in an isolated environment with virtualenv)

**Comment by JasonTheAdams** [comment]
Ah, I didn't know about pip. That did it, thanks!
