### ISSUE TITLE
Add Eclipse Mars support

### ISSUE THREAD

**Issue by syndbg** [ubuntu/ubuntu-make#120]
Latest supported by ubuntu-make is Luna.

https://projects.eclipse.org/releases/mars

**Comment by marcinant** [comment]
Does it support upgrade of existing instances?

**Comment by didrocks** [comment]
@marcinant: it does when upstream provides their own update mechanism (contrary to the ubuntu package, we are compatible with the way upstream autoupdate their tools). So, if eclipse does provide so, it will work.

For tools that don't offer upgrade mechanism, there is a discussion on #74.

**Comment by didrocks** [comment]
This is now available as of Ubuntu Make 16.01. Latest eclipse release should now always be delivered with this refactoring!
