### ISSUE TITLE
ubuntu-make in scripts + Updates to Visual Studio

### ISSUE THREAD

**Issue by thagabe** [ubuntu/ubuntu-make#126]
Can we include an auto-accept flag to umake in such a way that umake can be easily included in scripts? Another thing I wanted to bring up to your attention is the release of Visual Studio 2015 and will ubuntu-make be updated to include this new release? Or while skimming through the code it might be that whenever you install (or reinstall) Visual Studio it will pull down the latest release by Microsoft?

Thanks!
Continue with the great work!

P.S. Any updated on the ubuntu-make updates? haha

**Comment by didrocks** [comment]
Hey thagabe! The good news is that this flag already exist. For instance, in the visual-studio-code case:
$ bin/umake web visual-studio-code --help
usage: umake web visual-studio-code [-h] [-r] [--accept-license] [destdir]

positional arguments:
  destdir           If the default framework name isn't provided, destdir
                    should contain a /

optional arguments:
  -h, --help        show this help message and exit
  -r, --remove      Remove framework if installed
  --accept-license  Accept license without prompting

This --accept-license option only appears on framework asking for license signing. So, something like this should work in a script:
$ umake web visual-studio-code ~/tools/vcs --accept-license
should install it automatically from a script!

On the update question, we let generally what upstream is using, there are some discussion on bug #74 and #122 on how to deal with those, like VSC that don't have their own mecanism.  Do not hesitate to share your though on those!
You are correct that everytime you install VS or any other framework, we always try to grab and install latest stable release.

Finally, on the update for ubuntu-make, I should be able to cut a release today (bringing some fixes and arduino support) ;)
