### ISSUE TITLE
Add VCS and diff/merge tools support

### ISSUE THREAD

**Issue by gperdomor** [ubuntu/ubuntu-make#128]
Add support for tools like smartgit, giteye and p4merge... :D

**Comment by didrocks** [comment]
Thanks for your suggestion for Ubuntu Make!

I'm a little bit puzzled by your request. It seems to me that the need for having those tools at the latest available version is less important than the ones from the IDEs or developer framework, isn't it? To look back at what's the reason and motto for Ubuntu Make, please check https://wiki.ubuntu.com/ubuntu-make.

For those tools, shouldn't we just ensure that the ubuntu distro ships a reasonably recent version instead? What do you think?

**Comment by gperdomor** [comment]
Hi, sorry for the delay, you right, and some packages are provided by the developer in .deb format, but in the case of P4Merge (Perforce Merge) the package is provided as tar file, would be nice having at least this package in ubuntu make to make easier their installation

**Comment by mhalano** [comment]
I think include VCS tools is pertinent, but my concern is about licenses when using commercial solutions.

**Comment by LyzardKing** [comment]
Closing since this is not going to be added now to ubuntu-make.
