### ISSUE TITLE
umake exits with 0 if download page has changed or unavailable

### ISSUE THREAD

**Issue by oijazsh** [ubuntu/ubuntu-make#129]
It appears that currently when umake exits due to the download page being unavailable or having changed, it exits with an exit status of 0 – it shouldn't be 0 after exiting due to an error. This is currently the default behavior in BaseInstaller.

Also perhaps it would be a good idea to also check whether umake's exit status is 0 after a successful install in our large tests.

**Comment by didrocks** [comment]
Oopsss, nicely spotted, just can say "Agreed and agreed"! Do you want to dive into both this or should I, or should we share?

It will be easy to create as well an invalid download in the medium test I think.

**Comment by oijazsh** [comment]
I will be free look into both later today and will be happy to do so. Adding a medium test for bad download pages should be simple enough as well - it can done as the bad md5sum test is handled for android studio.

**Comment by didrocks** [comment]
Exactly what I was thinking about! Great ;)

Now that you mention it, as a FYI, one day as well, I will remove most of the "install/reinstall" and so on tests from the android studio framework and put that in a BaseInstaller large and medium tests as it's clearly what it's testing (and it will clear the time for large tests I guess with smaller download). But that's not the topic, keep me posted :)

**Comment by oijazsh** [comment]
Should I write the extra medium test for every framework, or only for those that overload the "get_metadata_and_check_license" as all others rely on BaseInstaller

**Comment by didrocks** [comment]
Hey!

I would say that you should write:
- one (I guess in android studio medium tests) to cover all frameworks that don't overload get_metadata_and_check_license(). This one as a lot of tests in android studio framework would move one day to a large "BaseInstaller" framework testsuite.
- and as you told, one for those that overload get_metadata_and_check_license().
