### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bpsizemore** [ubuntu/ubuntu-make#130]
First sentence of the README file is confusing. At first glance it seems to be grammatically incorrect. Consider updating for ease of understanding.

**Comment by didrocks** [comment]
Fell free to propose a pull request to fix it (I'm not a native english speaker) and I'm happy to merge it :)
Thanks for your suggestion!

**Comment by bpsizemore** [comment]
I have submitted a pull request with an updated README. Let me know if you have any comments or concerns. I'd love to get more involved with the project if you have anything that you could use some help with let me know.

**Comment by didrocks** [comment]
An merged! Everything looked good to me, thanks!

I noticed however that we only mention Android Studio in the readme (which was the first framework developped in Ubuntu Make). If you want to do some other contribution, maybe refreshing it (not listing all frameworks, but I think something more along the line of what is available at https://wiki.ubuntu.com/ubuntu-make) would be really useful!

Tell me if in addition to this, you have other ideas/desire to contribute to other parts of the project :)
I'm closing the bug report, thanks again for your great help!
