### ISSUE TITLE
Go 1.5 RC1 Released

### ISSUE THREAD

**Issue by thagabe** [ubuntu/ubuntu-make#132]
Are we going to start working on updating the go-lang installation? I figure it will be fairly easy to update.

**Comment by didrocks** [comment]
We are pointing at https://golang.org/dl/. I guess as soon as Go 1.5 gets out of the RC status to be the stable one, it will be picked up then (if they don't change the download page structure), keep me posted!

**Comment by didrocks** [comment]
Just did a manual install, confirming that 1.5 is now downloaded as it hit stable!

**Comment by thagabe** [comment]
Thanks! I too can confirm it works!
