### ISSUE TITLE
VSCode: ERROR: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by vsimonian** [ubuntu/ubuntu-make#136]
Microsoft just released an update to VSCode, and with it, changed the way that download URLs work on their site.

As a result, the script no longer works, erroring in

```text
ERROR: Download page changed its syntax or is not parsable
```

I've gone ahead and created a PR (#135) which fixes this issue.

**Comment by winuxue** [comment]
the issue is back

**Comment by LyzardKing** [comment]
What version of umake do you have? It's working on the latest

**Comment by airjure** [comment]
I also face this issue. Using latest umake.

**Comment by LyzardKing** [comment]
could you run umake --version? It might be that the version you have is not actually the latest (from the ppa)
It should be 16.04.
If that is the version you have, then try running umake -v ide visual-studio-code to see what link it's trying to download from.
We use direct links now, so there is no download page to parse (only the license page)

**Comment by airjure** [comment]
Hey LyzardKing,

thank you for your reply. Firstly, I am not very familiar with Ubuntu, as I use it rarely, but here are my results:

Running "umake --version" seems to not working in my case, as I only get:
```
jure@ubuntu:~$ umake --version
usage: umake [--help] [-v] [-r] {android,web,ide,go,dart,scala} ...
umake: error: unrecognized arguments: --version
```

Running "umake -v ide visual-studio-code" also seems not to be working.
`umake ide: error: argument framework: invalid choice: 'visual-studio-code' (choose from 'pycharm-educational', 'idea-ultimate', 'rubymine', 'phpstorm', 'webstorm', 'pycharm-professional', 'eclipse', 'arduino', 'idea', 'pycharm')`

I suspect that ide should be replaced with "web", and those are the last two lines:
```
INFO: All pending downloads for [DownloadItem(url='https://code.visualstudio.com/Docs', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None)] done
ERROR: Download page changed its syntax or is not parsable
```

I believe I have the latest version, as I downloaded, installed and updated Ubuntu 15.10 today. After that I installed umake, and experienced this problem.

For now I just used package directly from MS website, as this is good enough for me, but I just wanted to state that also I experienced the same problem as users before me. 

Thanks, Jure

**Comment by LyzardKing** [comment]
No problem :)
The version in the 15.10 repositories is not the latest I believe.
It takes some time for it to be uploaded.
To get the latest you should install the repository:
```
sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
sudo apt-get update
```
and the update ubuntu-make

As you can see on this page: https://wiki.ubuntu.com/ubuntu-make

**Comment by airjure** [comment]
Ahhhh... thank you very much! Everything working as expected now! :) :+1:

**Comment by winuxue** [comment]
after add the custom ppa it worked fine.
Thank you
