### ISSUE TITLE
Add JetBrains EAP builds support

### ISSUE THREAD

**Issue by rosolko** [ubuntu/ubuntu-make#140]
It would be nice, if add latest IDEA Early Access Preview releases support from:
https://confluence.jetbrains.com/display/IDEADEV/EAP

For now it's IDEA EAP 15:
https://confluence.jetbrains.com/display/IDEADEV/IDEA+15+EAP

This feature request same for other product:
PyCharm: https://confluence.jetbrains.com/display/PYH/JetBrains+PyCharm+Preview+%28EAP%29
WebStorm: https://confluence.jetbrains.com/display/WI/WebStorm+EAP
0xDBE: https://confluence.jetbrains.com/display/DBE/0xDBE+1.0+EAP

Thanks!

**Comment by didrocks** [comment]
Hey, thanks for this suggestion!

This is doable of course, I do wonder what's the gain of adding the EAP support for the average user? Aren't they any risk of those breaking along the chain and so, we install to some developers something that they may not be fully aware of stability-wise?
Keep in mind that as soon as the EAP becomes "stable", this will is replacing automatically the latest version available on a traditional "umake idea pycharm" for instance.

So, thanks for lightening me up on the need for adding pre-beta support for software, and then, let's imagine if we do that for all supported platforms what would become (I don't want to explode the number of available options and get the user lost due to too many choices)

**Comment by rosolko** [comment]
But, a lot of the people use EAP releases. And this build going as separated releases.

And after end of EA period branch is closing and suggesting to upgrade to stable release.
EA branch is frozing for some period, and after froze starting new EA period.

This build can be added as separated options, not as a options for stable release.

Smth like:
umake ide eap-idea

Also, you don't need to choose between community and commercial branches, because all of the EAP release are commercial branch with EA time subscribe.

Thanks. If you don't understand smth - you're welcome.

**Comment by didrocks** [comment]
I guess it will be great to get number of people using the EAP version vs the traditional ones.

I would really be against adding something like "umake ide eap-idea" as we will see an explosition of choice for the new developers (and too many choices just lead to uninformed one).

However, I would accept a good patch adding a --eap option to each frameworks for stable release that supports it. If the website structure isn't that different from original one, it shouldn't be hard and I'm happy to provide some reviews and guidance :)

**Comment by rosolko** [comment]
I can't find exactly numbers, because JetBrains didn't announce them.
For now, I didn't know, how does framework work. And I can't provide patch.
Suggestion only :C

**Comment by funivan** [comment]
:+1: or even more. A lot of users use EAP. In my company all developers use EAP. First version of EAP is sometimes buggy. But they are feature reached and it is useful for  Intellij developers to get feedback from users about bugs of EAP version.
:+1: for --eap tag 
Providing this tag will install latest build even if it is EAP (non stable). This behavior I thinks is pretty clear.

**Comment by didrocks** [comment]
Thanks for the feedback!

Agreed, the --eap tag seems to be the sanest approach :)

**Comment by rosolko** [comment]
And special vote for 0xDBE - it's a rally comfortable SQL databases management system, that for now appear only in EAP releases version.

**Comment by funivan** [comment]
All new version of jetbrains are EAP =)

**Comment by rosolko** [comment]
I mean, that this product doesn't have a stable release.

**Comment by denji** [comment]
@rosolko We don't need stable releases, new versions support improved font rendering.

**Comment by funivan** [comment]
If we add `--eap` argument it will be used globally right? 
But we can use it only with jetbrains products. How to deal with it?
I find url that provide latest eap build. For example phpstorm:
`https://www.jetbrains.com/phpstorm/download/download_thanks.jsp?os=linux&beta=ok`

Question: How to check arguments in https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/ide.py#L327 and change url if we install programm with `--eap` argument ?

**Comment by didrocks** [comment]
We have per-framework arg parser capability. This is used in firefox dev (see https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/web.py#L126) and quite easy to use!

Basically, you need to implement two methods:
def install_framework_parser(self, parser):
-> to install a new parser option (then shell completion and such will have access to it)

and:
def run_for(self, args):
-> which is where you take any action based on args (which is a traditional args returned by parser.parse(). This thus where you can change the url (as firefox-dev framework is doing).
So the big and complex part should already be handled by ubuntu make for you ;)

**Comment by LyzardKing** [comment]
Is this still a thing?
The "new" link for the eap versions is:
`https://data.services.jetbrains.com/products/releases?code=IIC&type=eap`

Adding &type=eap you either get a different link (formatted like the non eap ones we use);
or an empty set: `{"PCC":[]}`

**Comment by funivan** [comment]
@LyzardKing is this feature documented in intellij platform?

**Comment by LyzardKing** [comment]
I'm not sure. I happened to read this (http://blog.jetbrains.com/idea/2016/02/intellij-idea-16-public-preview/).
It seems to add `&type=eap`, and it works with our download_page.
This is just an idea. Since I don't really use intellij, I'm not sure about this.

**Comment by rosolko** [comment]
Seems like `&type=eap` option is applicable to UI download:
From `https://www.jetbrains.com/idea/download/download-thanks.html?code=IIC` get stable release
From `https://www.jetbrains.com/idea/download/download-thanks.html?code=IIC&type=eap` get EAP release

**Comment by LyzardKing** [comment]
Yes. But since it works with the links we use, like
"https://data.services.jetbrains.com/products/releases?code={}"
It's better to use that. so we only have to change the end of the line

**Comment by ToucheSir** [comment]
It appears that the implemented feature is still unable to detect EAP releases. Adding `type=EAP` to the query for any `code` just returns an empty list for me.

**Comment by ToucheSir** [comment]
@LyzardKing might it be worth checking out https://www.jetbrains.com/updates/updates.xml? FWIW The IDEs themselves appear to use this endpoint for update checks, and every release seems to be covered.

**Comment by LyzardKing** [comment]
The link works.
The whole point is to have an eap available until it becomes a release.
After that it serves no real purpose, since the released version would be newer.
As you can see the latest version of idea is 2016.1
The next eap will be 2016.2, but it's not available at the moment.

**Comment by ToucheSir** [comment]
But the link doesn't work? As far as I can tell, the current link never displays EAP releases (only stable), and filtering using `type=eap` always returns an empty set like `{"PCC":[]}` despite there being readily available EAP releases.

**Comment by LyzardKing** [comment]
If you look at the link you sent in the previous comment,
you can see that the latest eap for idea is the same version of the 
latest release.
That's what I mean. :)

I think the issue here (but I personally don't use any eap version) is 
that what you're
thinking of is an RC, not EAP.

**Comment by ToucheSir** [comment]
Oh, I see where the confusion is now. :) It just so happens that the stable release build was bumped up to be in line with the EAP in the past couple of days, and the latter has not had any releases since then. Just a couple of days ago, for example, the PyCharm build was at something around `145.569` while the EAP was at `145.844` (which is now the new stable build number).

**Comment by funivan** [comment]
Hello. I try to install phpstorm eap version but umake cant detect it.
Manually open url https://data.services.jetbrains.com/products/releases?code=PS&type=eap  and we get 
`{"PS":[]}` 
However there is eap version. You can open https://www.jetbrains.com/updates/updates.xml  and find following code:
```xml
<channel id="EAP" name="PhpStorm 2016.3" status="EAP" url="http://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program" feedback="http://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program" majorVersion="2016" licensing="eap">
      <build number="163.3983" version="2016.3 EAP" fullNumber="163.3983.3">
        <patch from="163.3512" size="from 8 to 23" fullFrom="163.3512.10" />
        <button name="Release Notes / Download" url="https://blog.jetbrains.com/phpstorm/2016/09/phpstorm-2016-3-eap-163-3983/" />
        <message><![CDATA[
          PhpStorm 2016.3 EAP build 163.3983.3 is available!<br/>
          <br/>
          The most important changes include:<br/>
          - Code Style Settings for PHP 7 return types (<em>Spaces->Other</em> in Code Style) <br/>
          - Improvements in completion for overriding methods/fields <br/>
          and many other bug fixes and improvements.
        ]]></message>
      </build>
    </channel>
```

There are many cases how to solve this problem. But I can suggest only 2:
1. Add custom argument --source-url  for example:
`umake -v ide phpstorm --source-url="http://download.jetbrains.com/webide/PhpStorm-EAP-163.3983.3.tar.gz"`  Then user can specify the version of the programm
2. Ask jetbrains team to fix service https://data.services.jetbrains.com/ or provide other services to detect release version.
