### ISSUE TITLE
Allow to install android-sdk only

### ISSUE THREAD

**Issue by sschuberth** [ubuntu/ubuntu-make#141]
Currently, we only have a choice of `android` (which will install Android Studio incl. the SDK) and `android-ndk`. However, esp. for CI systems, it would be nice to be able to only install the Android SDK (in a directory next to the NDK).

**Comment by didrocks** [comment]
Thanks for your suggestion and help making Ubuntu Make better!

I guess this can be easily done, I'm happy to merge a good patch for any new contributor and tutor them with writing tests (this should be just few lines of codes, looking at what is done for android-ndk).

**Comment by sschuberth** [comment]
@didrocks I've given it a try, would you mind having a look?
