### ISSUE TITLE
Adding experimental unity3D support

### ISSUE THREAD

**Issue by didrocks** [ubuntu/ubuntu-make#144]
Working on it as I type this ;)

**Comment by Tinche** [comment]
According to omgubuntu, MonoDevelop isn't bundled. Do we want to support the newest version of that too?

**Comment by didrocks** [comment]
I saw you committed on OMGUbuntu ;) I'm surprised, because it's definitively in the tarball and in the .deb package. I'll test that, maybe it's just a linking missing.

At worst, I can download it for now as a requirements (so, the one from distro), and use that. I guess as long as the Unity 3D editor is in some experimental support mode, that's fine to go that road :)
