### ISSUE TITLE
Add: Lazarus IDE and FPC

### ISSUE THREAD

**Issue by mdalacu** [ubuntu/ubuntu-make#149]
Please, add this great RAD solution. It can compile to different targets and architectures.
The version provided in the USC it is old and conflicts with new versions.
http://www.lazarus-ide.org/

**Comment by didrocks** [comment]
Thanks for your suggestion :)
We don't have any Pascal IDE indeed! It would be an interesting one for a new contributor, opening up for such!

**Comment by mdalacu** [comment]
Great! You have made my day! ;)

**Comment by mdalacu** [comment]
The debs are available on their website, but someone needs to remove the fpc conflictiong package form Ubuntu repositorys.

**Comment by didrocks** [comment]
Hey, thanks for the head's up!
However, we don't download or install debs in Ubuntu Make as we are trying (out of dependencies) to keep the installation process as non root.

It would be great if upstream was providing some compiled archives version as we do for other platforms!

**Comment by mdalacu** [comment]
Unfortunately i don't know how the reach the relevant people for this. :(
This tool will download the latest stable version and compile all in a single self contained directory.
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup

**Comment by didrocks** [comment]
It seems they have a forum, maybe worth a try? We definitively don't want to compile anything (or we recreate the distribution process itself ;)) as part of Ubuntu Make, but really, takes what upstream stamped and tested.

**Comment by mdalacu** [comment]
I have opened a thread...finger crossed.
http://forum.lazarus.freepascal.org/index.php/topic,30368.0.html
