### ISSUE TITLE
How to Install android without interactive post-install configuration steps

### ISSUE THREAD

**Issue by chrisber** [ubuntu/ubuntu-make#150]
How to Install android without interactive post-install configuration steps.

```
# Install Ubuntu make
RUN add-apt-repository ppa:ubuntu-desktop/ubuntu-make
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q ubuntu-make
```

The script fails when the user has to interactively accept the licence.
Is there a workaround?

**Comment by didrocks** [comment]
No workaround, it's even built-in!

umake android --accept-license /home/user/path/to/install/to

as described in bin/umake android --help ;)
