### ISSUE TITLE
Can't install visual studio code

### ISSUE THREAD

**Issue by cimenx** [ubuntu/ubuntu-make#151]
i install using umake web visual-studio-code

but i got this error

Downloading and installing requirements                                        |
ERROR: http://go.microsoft.com/fwlink/?LinkID=620884 couldn't finish download: HTTPSConnectionPool(host='az764295.vo.msecnd.net', port=443): Max retries exceeded with url: /public/0.8.0/VSCode-linux-x64.zip (Caused by <class 'OSError'>: [Errno 101] Network is unreachable)
100% |#########################################################################|
ERROR: HTTPSConnectionPool(host='az764295.vo.msecnd.net', port=443): Max retries exceeded with url: /public/0.8.0/VSCode-linux-x64.zip (Caused by <class 'OSError'>: [Errno 101] Network is unreachable)

after i executed umake web -r visual-studio-code
ERROR: You can't remove Visual Studio Code as it isn't installed

and it didin't have visual code isntalled in folder tools

**Comment by didrocks** [comment]
Hey cimenx,

The automated tests are still running ok and I can install visual studio code here. The error seems like a transient one: "[Errno 101] Network is unreachable". Did you retry it? Do you have access to http://go.microsoft.com/fwlink/?LinkID=620884 from your network?

**Comment by cimenx** [comment]
It seems sometimes the download link for Linux and/or WIndows version is unavailable. Yesterday, i try to download Mac OS version but can't download for Linux and Windows version. Anyway it solved now.

**Comment by didrocks** [comment]
Thanks for the feedback! Closing then :)
