### ISSUE TITLE
Update Eclipse version up to Mars

### ISSUE THREAD

**Issue by idvoretskyi** [ubuntu/ubuntu-make#152]
Current umake version installs Eclipse Luna version (4.4). Current Eclipse version - is Mars (4.5).

Please, implement possibility to install Mars (4.5) version.

Thank you.

**Comment by didrocks** [comment]
Thanks for reporting this bug, however, have a look at pull request #145 following up bug #120 ;)

Any help on that is more than welcomed! (see the first draft on the PR and my answers)
Closing that one as a duplicate thus!
