### ISSUE TITLE
ANDROID_NDK / ANDROID_HOME variables not set

### ISSUE THREAD

**Issue by sschuberth** [ubuntu/ubuntu-make#158]
Is there any specific reason why the ANDROID_NDK / ANDROID_HOME environment variables are not set when installing the Android NDK / SDK respectively? Otherwise they should be set, IMO.

**Comment by didrocks** [comment]
I guess that's a good idea. For android dev, I'm usnig the IDE, so didn't notice that they were missing.

Is should be quite straightforward to implement as we already inject env variables when installing those frameworks, and just need a couple of lines and some tests adapation. Volunteering to work on this? :)

**Comment by sschuberth** [comment]
Well I'd have a few questions first. For example, what's your policy if the variables are already set for some reason? Would you leave them untouched, or overwrite them to ensure they are pointing at the installed NDK / SDK, or onyl overwrite them if the original values point to invalid directories, or ...?

**Comment by didrocks** [comment]
For now, as we only use this functionality in env variables supporting multiple paths, we simply (and bindly) prepend as most of env var, but there is an option to override as well (check the docstring for add_env_to_user() in tools.py). So, this is basically up to you and the toolkit functionality. I would say prepend at first if supported.

Also, when we remove the framework, those env var (tagged for this framework) are automatically removed.

**Comment by sschuberth** [comment]
Prepending is not supported AFAIK. These variables need to point to a single path each.

**Comment by didrocks** [comment]
So, I would say override as the action is explicitely to install those frameworks (at least for android-sdk and android-ndk).
