### ISSUE TITLE
Add a --version argument to umake

### ISSUE THREAD

**Issue by sschuberth** [ubuntu/ubuntu-make#162]
It would be nice if `umake` supported a `--version` argument to print out its version.

**Comment by didrocks** [comment]
Indeed! Good idea!

I want to implement this right and being as automated as possible though, meaning:
- generate a file at build-time from the debian/changelog version (to avoid having discrepancies between version)
- then, this file is somewhat committed at release time, and then, any newer commit or any run from trunk will turn it to <previous-release>+dev

I need to think about it ;)

**Comment by sschuberth** [comment]
> generate a file at build-time from the debian/changelog version (to avoid having discrepancies between version)

Right, or the other way around, as people might want to bump the version without doing a release (yet): Have a text file holding the version, include / read that file from Python, and also pass the contents of that file as a command line argument to `dch -v` to set the version?

**Comment by didrocks** [comment]
Then, we should write a git hook running on github to ensure to have it automatically bumped after a release. By experience, on multiple projects, I know that "post release bump" is something that is easily miss ;)

Part of the issue using that path is that this doesn't really work well with the current ubuntu-make release scheme: YY.MM<.minor>, as the month (and year) can be the next one:
- you do a release the 22nd of october -> releasing 14.10,
- then post release bump commit as 14.10.1.
- finally, you end up releasing in november, and have to not forget to rebump to 14.11 (or have a commit hook doing it). But you do end up with 2 commits for that in one release.

Any enlightening thought? It's something I had to deal with Quickly (as part of release process management, it was handling project bumping as well, it's not as straightforward to get it right as people may think ;)).

**Comment by sschuberth** [comment]
Hmm, sorry, I didn't really get what speaks against having a file named `VERSION` committed to the repo that contains e.g. `14.11`. That's where you bump the version before a release. The file is shipped with `umake` and read when `umake --version` is given. For releasing, there should be some script or so that calls `dch -v $(cat VERSION)`. Put simply.

**Comment by didrocks** [comment]
let me have a look if we can get this as part of a git hook (I prefer that than release script). I also have an evil idea for people running trunk from git (like adding the commit sha).

I guess I'll play with this, unless you want to?

**Comment by sschuberth** [comment]
Please go ahead!

**Comment by didrocks** [comment]
Didn't implement the hook for now, but 80ab46dad84d42c3e871c20b91c3782c2692cff9 should at least address the first concern (having a --version). Will do the hook next week :)

**Comment by didrocks** [comment]
All done now, with scripts to handle release! I'll eventually add some tests to those as well. Closing the bug for now and thanks for your suggestions :)

**Comment by sschuberth** [comment]
Great, thanks for the implementation! Looking forward to the next release :-)
