### ISSUE TITLE
Remove framework doesn't work

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#163]
When running umake -r go, I get prompted:

Go Lang is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)]

I Type N, but nothing happens.  Golang is still setup

If I type y, setup installs go again.  A duplicate env variable is add to .zprofile

**Comment by didrocks** [comment]
Thanks for opening this bug!

I agree this is counter-intuitive.
Basically what happens is that you have parsers and each frameworks install its own subparser. Remove is part of the subparser for each frameworks.

I have an idea on how to fix it (not really a fan of it though as it means messing with user's input and changing parameter order, but I guess it may worth it. Will work on that shortly.

There is a second bug that I wasn't aware of and you just mentioned it. The duplicate env variable during reinstallation shouldn't happen, mind opening a separate bug for this?

**Comment by jravetch** [comment]
@didrocks Thanks for looking into this.  I created a new bug for the dup env variable #165

**Comment by didrocks** [comment]
commit https://github.com/ubuntu/ubuntu-make/commit/49649165b6e216d007f1d8dad3adc88c516afd1c 
should fix it. The 2 appended commits then add tests cases for this. Thanks for your report! The fix will be part as of next release :)
