### ISSUE TITLE
Duplicate Env variable under zsh when reinstalling

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#165]
When reinstalling a framework, the env variable is added again to .zprofile.

**Comment by didrocks** [comment]
So, I tried to replicate that issue today. I can't though.

I installed go to a path, then I run again $ umake go
and specified another path. I don't find any duplication of GOROOT env variable there. I only have one instance pointing to the right directory (the newest).

I checked the code as well, and I confirm that the baseinstaller is doing the right thing (look at https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/baseinstaller.py#L96).

Do you have an easy way to reproduce it? Did you remove by any chance the Ubuntu make tag:
"# Ubuntu make installation of Go Lang" in your .zprofile? (that's how we detect the installation made by Ubuntu Make, while still enabling the user to export/override it manually if they want).

**Comment by jravetch** [comment]
@didrocks So this happens when I was trying to remove a framework or reinstall in the same path, in this case go.  The install would prompt:

Go Lang is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)] y

I'm left with the same install and repeated entries in .zprofile:

# Ubuntu make installation of Go Lang
PATH=/home/tools/go/go-lang/bin:$PATH
export GOROOT=/home/tools/go/go-lang:$GOROOT

# Ubuntu make installation of Go Lang
PATH=/home/tools/go/go-lang/bin:$PATH
export GOROOT=/home/tools/go/go-lang:$GOROOT

I also get repeated entries when I run the install again in the same path.  The install should detect the presence of the env variable in .zprofile or bash_profile and overwrite instead of adding an entry again.

**Comment by didrocks** [comment]
That's exactly what I tried (see my last comment) and couldn't reproduce. I'm surely doing something different. Do you mind posting a step by step reproducer?

**Comment by didrocks** [comment]
Ok, I think I got it giving it another look! You are under zsh and I didn't handle the "removal" case for zsh shell (only addition). Master now fixes it (you can try locally if you want) and I added a test for that use case as well.

Thanks for spotting it! :)
