### ISSUE TITLE
Install path selection

### ISSUE THREAD

**Issue by mhalano** [ubuntu/ubuntu-make#169]
I was trying to create a "recipe" (actually a Ansible playbook) to automate my computer pos-OS installation. The problem is: I need to use expect module (which use expect command line tool), but there is a problem: I can't change the path because the default path is already fulfilled as a text. Example:
I want to expect something like this:
Choose installation path (default: /home/marcos/tools/web/visual-studio-code):
Instead:
Choose installation path: /home/marcos/tools/web/visual-studio-code
What I mean is show the default path, but don't put as string because make hard to automate the installation process.

**Comment by didrocks** [comment]
Actually, I don't think you should try to much doing things with pexpect and such. The inputs are not part of any stable API, so it can break quite easily.

For tools like Ubuntu Make, I made some efforts to ensure that you can script the installation easily, so you are already all set ;)
Simply provide the path after the framework name and it will be chosen without asking you about it (apart if the destination not an empty directory, of course).
For framework with licenses, you can use --auto-accept to accept it without prompting.

If there is any other barrier for your automated post-install, do not hesitate to ask, but please use --help which should cover all this!
Happy automation :)

**Comment by arusahni** [comment]
For those of you who stumble on this after some searching, the argument to use is `--accept-license`, not `--auto-accept`.

**Comment by mhalano** [comment]
Probably this option should be better documented.

2015-11-11 2:02 GMT-02:00 Aru Sahni <notifications@github.com>:

> For those of you who stumble on this after some searching, the argument to
> use is --accept-license, not --auto-accept.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubuntu/ubuntu-make/issues/169#issuecomment-155655287>.
>



-- 
Marcos Alano
----------------------------------------------
P: Por que este email é tão curto?
R: http://five.sentenc.es
----------------------------------------------

**Comment by didrocks** [comment]
Any framework supporting it as it in its --help:
```
umake android android-studio --help
usage: umake android android-studio [-h] [-r] [--accept-license] [destdir]

positional arguments:
  destdir           If the default framework name isn't provided, destdir
                    should contain a /

optional arguments:
  -h, --help        show this help message and exit
  -r, --remove      Remove framework if installed
  --accept-license  Accept license without prompting
```

There is an open pull request which tried to make an man page, but it would be more vital to keep it generated from the --help to keep it always up to date. Any help there welcome :)

**Comment by arusahni** [comment]
Do you maintain the PPA? The version there appears to be significantly older, as the help page reads:

```
$ umake --help
usage: umake [--help] [-v] [-r] [--version]
             {dart,web,scala,games,android,ide,go,rust} ...

Deploy and setup developers environment easily on ubuntu

positional arguments:
  {dart,web,scala,games,android,ide,go,rust}
```

**Comment by didrocks** [comment]
The ppa has the latest version (as you can see with --version).

Look at the difference between my command and yours (you did just print the general `--help`, which shows up categories). I did `--help` on the `android-studio` framework (with `umake android android-studio --help`), which is one framework asking for licensing acceptance.

The general help only prints help for supported category, we don't print help for each frameworks (as we have more than 20 right now, and it will give a too long output).

I hope this is more clear ;)
