### ISSUE TITLE
-r != --remove

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#175]
passing -r doesn't actually work to remove a framework.  Only --remove works

```bash
bin/umake -r go                                                                                
Go Lang is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)] N

bin/umake --remove go                                                                          
Removing Go Lang
Suppression done
```

**Comment by didrocks** [comment]
You're right (in the global option case, it does work on the framework option).

I just fixed it and added a test to back that up: https://github.com/ubuntu/ubuntu-make/commit/d42ccd77d4e229afdcca55acc47a71b96d1e29a3!
Thanks a lot :)
