### ISSUE TITLE
Please add Fritzing support

### ISSUE THREAD

**Issue by 8none1** [ubuntu/ubuntu-make#182]
Fritzing is an open source PCB design tool.

http://fritzing.org/home/

I'm working with people from Fritzing now to get MD5 sums available.

I will follow up on this bug when everything is in place from a formal agreement point of view.

**Comment by 8none1** [comment]
Fritzing are happy for us to add it.  They will work on the MD5 and "latest" download link soon.
http://forum.fritzing.org/t/including-fritzing-in-ubuntu-make/51

**Comment by didrocks** [comment]
We ideally need to have those latest download links and md5 served over https though (not the download itself, as having the rest "secured" is enough). Is that also on the pipe?

**Comment by 8none1** [comment]
I'll follow up, but I don't think it will happen anytime soon.

**Comment by LyzardKing** [comment]
I'm taking a look at this. On the forum they said that the md5 was possible,
and the https connection not likely.
Have there been any other updates on the matter?
Also, one thing missing in the tarfile is an icon.

**Comment by 8none1** [comment]
Sorry, no updates from me or from Fritzing. I can reach out again, or just comment on the thread on the Fritzing forums.

**Comment by LyzardKing** [comment]
That's unfortunate. Thanks for the reply anyway

**Comment by LyzardKing** [comment]
At the moment we could add fritzing, but we have no https nor checksum.

**Comment by LyzardKing** [comment]
Fritzing has been in umake for a while now, thanks to a collaboration with the new upstream.
Closing this issue.
