### ISSUE TITLE
SolidOak (IDE for Rust)

### ISSUE THREAD

**Issue by mhalano** [ubuntu/ubuntu-make#185]
I think is a good idea support the installation of SolidOak (https://sekao.net/solidoak/). That is a IDE for Rust.

**Comment by didrocks** [comment]
Opening for contributions as well! Thanks for the suggestion :)

**Comment by LyzardKing** [comment]
This is a standard github download, like atom.
The only problem is they haven't released a version since 2015.

**Comment by LyzardKing** [comment]
The repo has been archived.
Closing since it's no longer active
