### ISSUE TITLE
Add a new "electronics" category

### ISSUE THREAD

**Issue by mhalano** [Ubuntu/ubuntu-make#186]
Should we create another categories beyond which exists? I think (for now) about "electronics" for electronics related applications, even evolve programming. Like Arduino, or not, like Eagle.

**Comment by didrocks** [comment]
I guess that's a valid and good idea. I wouldn't create it though before we get a second "electronic" application if we get any contribution on this.

Renaming the title to be more explicit as well.

**Comment by jnv** [comment]
Fritzing #182 and Eagle #183 are good candidates for this category.

**Comment by leogaggl** [comment]
Just would like to add my support for this enhancement - both tools mentioned are very popular in the "Maker" community.

**Comment by zgoda** [comment]
Other candidates:

* base toolchains in `crossbuild-essential-{armhf|armel|arm64}` packages
* [PlatformIO](http://platformio.org) - core + IDE integration (Atom, VSCode, CLion)
* esp-open-sdk, Sming, esp-open-rtos

**Comment by LyzardKing** [comment]
@zgoda The tools you listed are not really things we can add to umake, I think:

- platformio is a plugin that is installed from atom or vscode

- esp-open and sming are frameworks that need compiling, and that's not something that umake does.

Let me know if I'm wrong, since I'm not really familiar with any of those.
What we would need is an archive (ie tarball) with a compiled version to extract and run...

**Comment by zgoda** [comment]
There are prebuilt binaries of esp-open-sdk, at least for 1.4, 1.5 and 2.0 Espressif releases.

Packages installed with pip can be installed in arbitrary location using `--root` and `--prefix` options. Atom plugins can be installed from command line using `apm`, VS Code does not have such thing.

**Comment by LyzardKing** [comment]
I don't think installing from pip or apm is something we want to include in umake.
Regarding the prebuilt binaries, could you explain what they are?

**Comment by zgoda** [comment]
Currently they're hosted at Dropbox so not very usable by umake atm. I will try to convince project owner to set up an account at Bintray for this.

**Comment by LyzardKing** [comment]
I can't find any link in the GitHub page...

**Comment by zgoda** [comment]
https://github.com/SmingHub/Sming/wiki/Linux-Quickstart

**Comment by LyzardKing** [comment]
Would it be possible to use the github releases page? It would be easier to pull from there..

**Comment by mhalano** [comment]
I think install with pip isn't the the best choice, but allows the user to isolate the application without virtualenv.
