### ISSUE TITLE
Automatic auto-completion in zsh

### ISSUE THREAD

**Issue by mhalano** [ubuntu/ubuntu-make#187]
Auto-completion should be enabled automatically in Bash and Zsh. Currently only work on Bash.

**Comment by didrocks** [comment]
I have no idea how this works in zsh and not a current zsh user, if anyone want to have a try at that, seems like a good first contribution! Tagging as such (and renaming the title to be more accurate)

**Comment by didrocks** [comment]
It was a little bit more complex than I anticipated, so I just handled it and pushed that to master. Next release will have that feature then :)

Thanks for the suggestion and report @mhalano
