### ISSUE TITLE
Help message is not clear

### ISSUE THREAD

**Issue by Lazza** [ubuntu/ubuntu-make#189]
The help message reports:

~~~~
$ LANGUAGE=en_US.UTF-8 umake --help | head -n 20
usage: umake [--help] [-v] [-r] {dart,ide,web,go,scala,android} ...

Deploy and setup developers environment easily on ubuntu

positional arguments:
  {dart,ide,web,go,scala,android}
                        Developer environment
    dart                Dartlang Development Environment
    ide                 Generic IDEs
    web                 Web Developer Environment
    go                  Go language
    scala               The Scala Programming Language
    android             Android Development Environment

optional arguments:
  --help                Show this help
  -v, --verbose         Increase output verbosity (2 levels)
  -r, --remove          Remove specified framework if installed

Note that you can also configure different debug logs behaviors using LOG_CFG
~~~~

However, trying something like:

    umake -r ide pycharm

Does not work. It takes a while to figure out that one needs to run:

    umake ide pycharm -r

Which is not consistent with the help message. IMHO this should be improved.

**Comment by didrocks** [comment]
@Lazza What is your Ubuntu Make version (umake --version)?
This was indeed an issue in a previous version of Ubuntu Make, but starting with 15.11.1, `umake -r ide pycharm`  should work as expected (and do the same than `umake ide pycharm -r`.

Ensure you get the latest version from the ubuntu make ppa (ppa:ubuntu-desktop/ubuntu-make).
Keep me posted!

**Comment by Lazza** [comment]
Ah sorry! :sweat_smile: The `--version` switch didn't work, but `apt search ubuntu-make` revealed that I am running version 15.08.

**Comment by didrocks** [comment]
Yeah, you need to use the one from the ppa thus! I'm closing then. Do not hesitate to reopen the bug in case that doesn't work! :)
