### ISSUE TITLE
Link to ppa isn't working in README.md

### ISSUE THREAD

**Issue by eldarkg** [ubuntu/ubuntu-make#194]
In README.md [part](https://github.com/ubuntu/ubuntu-make#developing-using-system-package) [link](https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ubuntu-make-builddep)

**Comment by didrocks** [comment]
Thansk for filing this issue! Nicely spotted, there is a missing s in the link, fixing :)

**Comment by didrocks** [comment]
Just fixed in master!

**Comment by eldarkg** [comment]
OK)
