### ISSUE TITLE
Add "font" support

### ISSUE THREAD

**Issue by tschf** [ubuntu/ubuntu-make#196]
Just proposing the idea of fonts for umake.

Recently I was checking out the [file-icons](https://atom.io/packages/file-icons) package for Atom. They use font libraries such as:

- Font Awesome - http://fortawesome.github.io/Font-Awesome/ https://github.com/FortAwesome/Font-Awesome
- Font Mfizz - http://fizzed.com/oss/font-mfizz https://github.com/fizzed/font-mfizz
- IcoMoon - https://icomoon.io/ https://github.com/Keyamoon/IcoMoon-Free/blob/master/IcoMoon-Free.pdf
- GitHub Octicons - https://octicons.github.com/ https://github.com/github/octicons
- DevIcons - http://vorillaz.github.io/devicons/#/main https://github.com/vorillaz/devicons

I installed a couple of them on my system by grabbing the `ttf` file and manually installing them. (afterwards noticing that Font Awesome is actually in the repos through the package `fonts-font-awesome` - but at v4.0.0)

![screenshot from 2015-11-29 21 30 06](https://cloud.githubusercontent.com/assets/1747643/11456551/6545ce32-96e0-11e5-839e-f1993af4a717.png)

And these are just icon based fonts - I imagine there are other open fonts devs may want to install. Could be too broad?

**Comment by didrocks** [comment]
Thanks for proposing this enhancement to Ubuntu Make @tschf.

Yeah, I'm a little bit mixed. I think Ubuntu Make should really focus on developer environments/tools and only that. If we elarge the scope too much, we just create pacman or other archs package management to always have latest installed. Restricting the scope to developer tooling enables us to have a great target, story, and having testable content.
Thoughts?

**Comment by tschf** [comment]
Yeah, that's a fair enough. I wondered if that would be the case.

I had a thought bubble, that if you were developing an app that was using some icons fonts, you would want them available on your system for either easier inspection in `Character Map`, or having the source files readily available to include in any web/other projects. 

I thought that may have fit into the premise of umake:

> Ubuntu Make is a project designed to enable quick and easy setup of common needs for developers on Ubuntu.
