### ISSUE TITLE
Slow and stopped downloading

### ISSUE THREAD

**Issue by Sreelal-c** [ubuntu/ubuntu-make#199]
on my ubuntu 15.10 system umake is downloading (vs code, firefox-dev etc) very slowly and after some times it stops downloading. The system doesnt have any other issues, browsing and downloading is fast.

**Comment by didrocks** [comment]
Thanks for reporting the bug and help Ubuntu Make to be better.

We just use the network connection (but only one thread, we don't do multiple threads to downloads). It shouldn't be that much an issue though for VSc or firefox-dev though. I can't reproduce here, the download is doing at a decent speed.

Do you mind doing a run adding -vv after umake while pasting the result here? That will help to see if anything has an issue in term of downloads.

**Comment by Sreelal-c** [comment]
This was caused by a system issue. After a restart umake is working fine.

**Comment by didrocks** [comment]
Thanks for the feedback!
