### ISSUE TITLE
Add Swift support

### ISSUE THREAD

**Issue by 8none1** [ubuntu/ubuntu-make#201]
Apple have opened their Swift language and have Ubuntu packages available:

https://swift.org/

https://swift.org/download/

Would be great to have this in Make.   They offer HTTPS downloads and signatures for the packages.

**Comment by didrocks** [comment]
Will work on it on Monday, thanks!

**Comment by didrocks** [comment]
Note that as per install instructions, we need clang to support swift. I'll check first if both distro version (14.04 LTS and 15.10+ are fine enough)

**Comment by didrocks** [comment]
Available now on 16.01.2!
