### ISSUE TITLE
[Webstorm] Can't parse the download URL from the download page.

### ISSUE THREAD

**Issue by jgoux** [ubuntu/ubuntu-make#202]
Hello,

when I try to install webstorm, I have this error : 
`ERROR: Can't parse the download URL from the download page.`

I'm using the `15.11.2` version.

Edit: It seems that they changed their download page URL extension, from `.jsp` to `.html`
Now the adress is : `https://www.jetbrains.com/webstorm/download/download-thanks.html?platform=linux`

**Comment by sethlivingston** [comment]
+1 and thanks, @jgoux

**Comment by didrocks** [comment]
Thanks for this bug report! Indeed, the JetBrains' website changed yesterday. I just pushed a fix for this. Expect a release in the coming hours (I'll just post here once done). Sorry for the bother!

Our tests confirmed the issue and the new few. Thanks again for filing up this bug report :)

**Comment by didrocks** [comment]
Just released! https://twitter.com/didrocks/status/675255501152763904 Thanks again for reporting this bug :)
