### ISSUE TITLE
Update URL for CLion (due to Jetbrains site update)

### ISSUE THREAD

**Issue by simos** [ubuntu/ubuntu-make#203]
Currently, the URL for CLion in umake is
https://www.jetbrains.com/clion/download/download_thanks.jsp?os=linux  (invalid)

The new URL to get CLion is 
https://www.jetbrains.com/clion/download/download-thanks.html
(https://download.jetbrains.com/cpp/clion-1.2.2.tar.gz)

**Comment by didrocks** [comment]
Thanks for this bug report! Indeed, the JetBrains' website changed yesterday. I just pushed a fix for this. Expect a release in the coming hours (I'll just post here once done). Sorry for the bother!

Our tests confirmed the issue and the new few. Thanks again for filing up this bug report :)

**Comment by didrocks** [comment]
Just released! https://twitter.com/didrocks/status/675255501152763904 Thanks again for reporting this bug :)
