### ISSUE TITLE
Update URL for PhpStorm (due to JetBrains site update)

### ISSUE THREAD

**Issue by hamzashezad** [ubuntu/ubuntu-make#204]
Current invalid URL: https://www.jetbrains.com/phpstorm/download/download_thanks.jsp?os=linux

Valid URL: http://www.jetbrains.com/phpstorm/download/download-thanks.html?platform=linux

This might even be a problem with other JetBrains packages too as their site has been updated.

**Comment by didrocks** [comment]
indeed! But it's already been fixed and released ;) see https://twitter.com/didrocks/status/675255501152763904.

Closing then :)
