### ISSUE TITLE
[Jetbrains] Error 404 when install jetbrains products

### ISSUE THREAD

**Issue by gperdomor** [ubuntu/ubuntu-make#205]
Hi...

Yesterday, jetbrains website was updated, and the downloads url changed, please solve this issue :D

**Comment by didrocks** [comment]
indeed! But it's already been fixed and released ;) see https://twitter.com/didrocks/status/675255501152763904.

Closing then :)

**Comment by gperdomor** [comment]
@didrocks thanks... I add the ubuntu-make ppa and now is working :D
