### ISSUE TITLE
Umake should list installable packages

### ISSUE THREAD

**Issue by didrocks** [Ubuntu/ubuntu-make#207]
Similar than issue #191, but adding a `umake list` command to list all installable packages on this machine.

I guess the output could be something like:

```
umake list
* android:
  - android-studio (default)
  - android-sdk
  - android-ndk (installed)
* ide:
…
```

Bonus point:
`umake list --all` listing all packages that are supported by Ubuntu Make, being installable or not (because we don't support the release, the architectures and such)

```
umake list
* android:
  - android-studio (default)
  - android-sdk
  - android-ndk (installed)
* ide:
 - awesome-ide (not installable on this machine)
…
```

**Comment by LyzardKing** [comment]
Published in master
