### ISSUE TITLE
New JETBrains site kills Ubuntu Make download

### ISSUE THREAD

**Issue by tankerkiller125** [ubuntu/ubuntu-make#211]
JetBrains did a site redesign as a result Ubuntu Make fails to download the files now.

**Comment by techdragon** [comment]
Are you getting the same error as this? 
```
umake ide pycharm-professional 
Choose installation path: /home/techdragon/.local/share/umake/ide/pycharm-professional
Downloading and installing requirements                                       |
ERROR: https://download.jetbrains.com/python/pycharm-professional-5.0.2.tar.gz couldn't finish download: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1749)
100% |########################################################################|
ERROR: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1749)
```

**Comment by brunnre8** [comment]
I can't install it either, but I get the following error message:
> ERROR: Can't parse the download URL from the download page.
The url which it tries is the following: https://www.jetbrains.com/pycharm/download/download_thanks.jsp?edition=comm&os=linux
(The link does indeed not work)

**Comment by tankerkiller125** [comment]
I just got a 404 with phpstorm however I may have a slightly outdated
version.

**Comment by didrocks** [comment]
That's correct! But it's already been fixed and released last Friday, just update to this new version ;) see https://twitter.com/didrocks/status/675255501152763904.

Closing then :)

**Comment by toby-1-kenobi** [comment]
When trying to install Rubymine I get this error

> ERROR: Can't parse the download URL from the download page.

Perhaps Jetbrains have changed their links again?
