### ISSUE TITLE
Download path for Jetbrains products has changed

### ISSUE THREAD

**Issue by flybuddy** [ubuntu/ubuntu-make#212]
The download path has changed.
For PHPStorm from https://www.jetbrains.com/phpstorm/download/ __download_thanks.jsp?os=linux__
to
https://www.jetbrains.com/phpstorm/download/ __download-thanks.html?platform=linux__

**Comment by didrocks** [comment]
That's correct! But it's already been fixed and released last Friday, just update to this new version ;) see https://twitter.com/didrocks/status/675255501152763904.

Closing then :)

**Comment by flybuddy** [comment]
Thanks! I installed umake from the main repository, not from ppa ... i'll make the switch to ppa :smile:

**Comment by didrocks** [comment]
Great! You will leave on the very latest :) Keep me posted if anything goes wrong!
