### ISSUE TITLE
Rust: can't find crate for `std` [E0463]

### ISSUE THREAD

**Issue by Zap123** [ubuntu/ubuntu-make#213]
Hello everyone, I'm new to Rust so as always I tried to use ubuntu-make to make my life simpler. I installed Rust with *umake rust*, and then tried to compile hello world but the compiler can't find the Rust Standard Library.
This is the compilation error:
```
src/main.rs:1:1: 1:1 error: can't find crate for `std` [E0463]
src/main.rs:1 fn main() {
              ^
error: aborting due to previous error
```
Environment variables are set as follows:
```
$ echo LD_LIBRARY_PATH 
/home/luca/.local/share/umake/rust/rust-lang/rustc/lib
$ echo $PATH
/home/luca/.local/share/umake/rust/rust-lang/rustc/bin:/home/luca/.local/share/umake/rust/rust-lang/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
I'm using Ubuntu 15.10 with ubuntu-make 15.12 and rustc 1.5.0 (3d7cd77e4 2015-12-04)
I wasn't been able to find a solution for this problem.

Thanks for this nice tool, I'm available to provide more information.

**Comment by jravetch** [comment]
@Zap123 Did you restart your terminal?

**Comment by Zap123** [comment]
Yes @jravetch , that error was after the reboot.

**Comment by jravetch** [comment]
@Zap123 I figured out the problem.  Looks like in Rust 1.5, they moved the std library out of rustc/lib.  If you look at the directory ./local/share/umake/rust/rust-lang, you'll see a directory rust-std-x86_64-unknown-linux-gnu.  The solution is either to symlink or move that folder to rustc/lib/rustlib.  That package has also separated to a different tar in http://static.rust-lang.org/dist/rust-std-1.5.0-x86_64-unknown-linux-gnu.tar.gz  @didrocks Any preference/thoughts on how to deal with this situation?

**Comment by didrocks** [comment]
@Zap123: Thanks for reporting this bug, sorry that you got that issue due to the new Rust release tarball. We'll get it fixed soon!

@jravetch: I would go with a symlink for now (will be easier in case they change in another Rust version later on). Do you want to handle that? Otherwise, I can do it today. Thanks for looking into it already!

**Comment by jravetch** [comment]
@didrocks If you don't mind taking it that would be great.  Happy to help test or review.

**Comment by didrocks** [comment]
Just pushed the above revision fixing the issue. Tests are passing here (waiting for our infra to confirm it passes on jenkins as well).

@Zap123: if you need that rust installation before next release, you can run Ubuntu Make from master pretty easily:
```
git clone https://github.com/ubuntu/ubuntu-make.git
cd ubuntu-make
bin/umake rust
```
Keep us posted! :)

**Comment by Zap123** [comment]
Thanks, it works now!

**Comment by didrocks** [comment]
thanks for the feedback! I'll cut a release near the end of week :)
