### ISSUE TITLE
Broken Jetbrain download links

### ISSUE THREAD

**Issue by Jingyu-Yao** [ubuntu/ubuntu-make#214]
Jetbrain recently updated their website and so various download links have been changed:

New download links:
- pycharm: https://www.jetbrains.com/pycharm/download/download-thanks.html?platform=linux&code=PCC
- idea: https://www.jetbrains.com/idea/download/download-thanks.html?platform=linux&code=IIC

**Comment by didrocks** [comment]
That's correct! But it's already been fixed and released on Friday the 11th, just update to this new version ;) see https://twitter.com/didrocks/status/675255501152763904.

Closing then :)
