### ISSUE TITLE
Add "Resume" and "Continue" capability

### ISSUE THREAD

**Issue by Ativerc** [ubuntu/ubuntu-make#215]
I was trying to install some software using ubuntu-make over a bad internet connection. The internet connection went down for a while. After regaining the connection, the download never "resume"d. 

I cancelled the download.

When I restarted the download, ubuntu-make didn't "continue" the download from where it left off, instead it started downloading it from the beginning.

Is it possible to add "resume" and "continue" capability to downloads on ubuntu-make?

**Comment by didrocks** [comment]
Hey @Ativerc, that's a very neat idea!

It's not that straightforward to implement as it depends if servers are supporting resuming, which is site-by-site dependent, but let's keep this task opened for the future!

Thanks again :)

**Comment by Tinche** [comment]
Honestly, I think this might be more trouble than it's worth. For example, how do we know if a URL still points to the same file?

**Comment by didrocks** [comment]
Yeah, that's a good remark, we need to save the state (maybe only when they propose a checksum?) to ensure this one didn't change as we have to save endPos anyway for the in progress download.

Then, come the question of cancelled downloads by the user, ensuring that we don't file up space, that the machine didn't reboot in between and such. So agreed, quite a hard task, let's see if anyone wants to pick it up (but for sure, not a top priority on the list) :)

**Comment by LyzardKing** [comment]
Is this still an issue?
If so a better thing to do could be to close the connection with an error if it stalls.
That way, instead of having the progress apparently frozen we can tell the user that the download failed.
Would a timeout work in this case?

**Comment by didrocks** [comment]
I guess a timeout without any new bytes coming in would be good enough, indeed! (we need to get some fake servers built around this for testing though). Then, we close the connection in error and everything should follow up :)

**Comment by Ativerc** [comment]
What would happens to the data that's been downloaded? Will it be deleted
from the user's PC automatically if the downloads fail?

**Comment by LyzardKing** [comment]
Does it create a partial file on disk at the moment?
I think the best thing to do is to restart the download. It is simpler and
it guarantees that you get the last version.

**Comment by Tinche** [comment]
If someone is on a laptop and loses connectivity we might go into an infinite loop. Maybe retry once?

After that just error out, exit with a documented error code (so people scripting can detect what happened).

With regards to cleaning up, hm. We use tempfile.NamedTemporaryFile(); according to the docs this file will be cleaned up as soon as it is closed. In case of errors we do close it: https://github.com/ubuntu/ubuntu-make/blob/master/umake/network/download_center.py#L186. Also the file will be in /tmp which apparently Ubuntu will clean on boot (http://askubuntu.com/questions/20783/how-is-the-tmp-directory-cleaned-up).

**Comment by LyzardKing** [comment]
It seemed to me that the file was temporary,  I wasn't sure. That's good.
Do you think we should try again after a timeout is reached?
We could set a timeout value in DownloadItem, then use the timeout error in
requests.get.
I started a branch in my fork for this,  but  I'm not too sure of what I've
done at the moment ;)

**Comment by didrocks** [comment]
Yeah, closing will definitively cleanup the file. I do think retrying is a trap. Let's first focus on closing the connexion properly for the rare case it happens, then, we can see if we want to implement an auto-retry feature.
