### ISSUE TITLE
Make firefox developer edition your default browser doesn't work

### ISSUE THREAD

**Issue by pierreozoux** [ubuntu/ubuntu-make#216]
I had to:

```
vi ~/.local/share/applications/firefox-developer.desktop
```
and replace this line:
```
Exec=/home/pierre/.local/share/umake/web/firefox-dev/firefox %u
```

I'd like to PR, but no idea where to start. The README is not helpful for me :/

**Comment by didrocks** [comment]
Ah, you're fully right, thanks for looking at this!

An easy way (if you don't want to git clone, run the tests and such), for such a small PR is to directly edit inline that file:
https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/web.py#L226:

You should just need to replace that line to add the %u (I would prefer "{} %u".format(os.path…)) if possible.
exec=os.path.join(self.install_path, "Code"),
Once that inline change done (after your clone the repo, you should be able to do a PR!

Hope that helps, looking forward to it :)

**Comment by pierreozoux** [comment]
Arf, to be honest, I'm not a python guy :/ I'll let you do it, I prefer, but happy that I could contribute a bit :)

**Comment by didrocks** [comment]
@pierreozoux: just pushed the fix! Thanks for the suggestion and for contributing to it this way :)
Tests can stay the same, and I hope more people will be able to enjoy firefox dev as their default browser thanks to you!

I'll cut a release with that fix in early January.
