### ISSUE TITLE
Update Android Studio

### ISSUE THREAD

**Issue by dikel** [ubuntu/ubuntu-make#217]
Hello, I installed Android Studio 1.5 via ubuntu-make. But now I get a message that there is a new version but when I click to update it opens a link to download. Can I update without downloading the new version from the site?

**Comment by didrocks** [comment]
Unfortunately not. We rely on upstream system to let them updating in place (as they are in the best position to do that). It seems that they discontinued the upgrade support between 1.5 and 2.0, so your best bet is to reinstall it fully (Ubuntu Make enable to do that in place).

Tell me if this reinstalls work for you ;)

**Comment by didrocks** [comment]
I assumed the reinstalled worked well. :)
