### ISSUE TITLE
Bad handling of low space on filesystem,

### ISSUE THREAD

**Issue by blurkis** [ubuntu/ubuntu-make#218]
It seems that ubuntu make has bad handling of the exception of lack of space.
While installing android studio on a more or less fresh installation of ubuntu 15.10 I could not install android studio. It dumped some strange errormessage which was lots of exceptions.  It did not actually say the drive was full.

After finding out my drive was full (to small partition for a ubuntu install, i found out.) I resized it with gparted, and after that; I could install android studio with no errors at all.
So it seems, I think, that ubuntu make has bad handling of the exception of lack of space.

**Comment by didrocks** [comment]
Thanks for reporting it as a bug as we discussed by email :)

A note for me for later:
- Need to check space error while downloading (should be already handled)
- Need to check while decompressing on target directory

**Comment by blurkis** [comment]
is there anything I can help with? Like, trying it in an virtual environment with little or no free space etc?
As said, I didnt save the error messages from ubuntu make before resizing the filesystem so as now, I cant reproduce. But im willing to create an virtual environment and try it again, if desired.

**Comment by didrocks** [comment]
Oh, I would be delighted if you can try to those configurations:
- almost file up /tmp, and ensure it's full while it's downloading (when the percentage goes from 0 to 100%)
- almost file up /home/<your_user> to ensure it's full while it's uncompressing the framework (when the progression bar bounces back and forth)
- bonus is if you are able to file up /usr before Ubuntu make is installing new packages (exactly when the percentage is at 0). This one is a little bit harder to reproduce I guess.

So, if you can at least test and report cases number 1 and 2, that would definitively rock and be of a great help! Thanks in advance :)
