### ISSUE TITLE
Error running medium tests

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#227]
When I try to run the go medium tests I get the following error:
```bash
[nose.plugins.manager] DEBUG: DefaultPluginManager load plugin nose_json = nose_json.plugin:JsonReportPlugin
[nose.plugins.manager] DEBUG: DefaultPluginManager load plugin cov = nose_cov:Cov
[nose_cov] DEBUG: nose-cov options
[nose_cov] DEBUG: nose-cov configure
F
======================================================================
FAIL: Install Go from scratch test case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jravetch/Projects/ubuntu-make/tests/large/test_go.py", line 72, in test_default_go_install
    self.assertEqual(output, "hello, world")
AssertionError: 'bash: warning: setlocale: LC_ALL: cannot [244 chars]orld' != 'hello, world'
- bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)hello, world
+ hello, world


----------------------------------------------------------------------
Ran 1 test in 8.670s

FAILED (failures=1)

```
When I run the rust medium tests, I get a similar error:
```bash
[nose.plugins.manager] DEBUG: DefaultPluginManager load plugin nose_json = nose_json.plugin:JsonReportPlugin
[nose.plugins.manager] DEBUG: DefaultPluginManager load plugin cov = nose_cov:Cov
[nose_cov] DEBUG: nose-cov options
[nose_cov] DEBUG: nose-cov configure
F..
======================================================================
FAIL: Install Rust from scratch test case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jravetch/Projects/ubuntu-make/tests/large/test_rust.py", line 77, in test_default_rust_install
    subprocess.check_output(self.command_as_list(cmd_list)).decode("utf-8").strip().split(":"))
AssertionError: '/home/user/.local/share/umake/rust/rust-lang/rustc/lib' not found in ['bash', ' warning', ' setlocale', ' LC_ALL', ' cannot change locale (en_US.UTF-8)\r\n/bin/bash', ' warning', ' setlocale', ' LC_ALL', ' cannot change locale (en_US.UTF-8)\r\nbash', ' warning', ' setlocale', ' LC_ALL', ' cannot change locale (en_US.UTF-8)\r\n/home/user/.local/share/umake/rust/rust-lang/rustc/lib']

----------------------------------------------------------------------
Ran 3 tests in 24.831s

FAILED (failures=1)
```

**Comment by didrocks** [comment]
Hey @jravetch, does this happens only with those medium tests or all of them?

First, ensure you are using latest docker container that I updated a couple of days ago to not use sshpass (`docker pull didrocks/docker-umake-manual`), and so, working with current ubuntu make master.

As you can see in https://jenkins.qa.ubuntu.com/job/udtc-trusty-tests/2624/label=ps-trusty-desktop-amd64-1,type=medium/ (and other runs), medium tests all pass well. Some here locally. I wonder if your configuration doesn't give different EOL for instance?

**Comment by jravetch** [comment]
Yep, I'm using the latest docker image with current master.  Dart and web are passing for me, but not rust, scala or go.  Wonder if tests asking for a 'Hello World' output are causing issues.  Do you think it might be an issue with zsh again?

**Comment by didrocks** [comment]
Yeah, as now we are isolated from the locale, can be zsh or the IFS or such that we are not overriding. That's weird though seeing that happening on medium tests though.

Do you mind trying this (sorry, as I can't reproduce :/):
* run in a bash session the tests
* start a guest session (to have a clean fresh config), clone the repo and try to run those tests?

**Comment by didrocks** [comment]
Hey @jravetch. Do you still see this or started to debug on it?

**Comment by jravetch** [comment]
@didrocks Hey sorry got busy with other things.  I tried running in a bash session, but got the same result.  Haven't tried the guest session yet.

**Comment by jravetch** [comment]
@didrocks Sorry for not responding in a such a long time.  After looking into this issue, I believe this can be easily fixed by setting the locale to en_UTF-8 in the Dockerfile as such:

```bash
update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX && \
locale-gen en_US.UTF-8 && \
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales && \
```

Can you give that a try and if tests are ok, I can make a pull request.

**Comment by didrocks** [comment]
Not sure I'll have time for trying it right away. Thanks for answering!

I'm unsure that would fix it fully though as you update local to set LANG=C, but the env is coming from the client (and works in certain case, like French -> English, even on non ascii characters as long as they are utf-8). Would rather worth a try with your configuration directly (you can tag the image locally or change its id in settings.py)

**Comment by jravetch** [comment]
@didrocks Looking at other dockerfiles, it's quite standard to set the locate to LANG=C and generate the en_us.UTF-8 locale when using the stock ubuntu 14.04 docker image.  This removes all warnings that the locale was not set.  This can accomplished by simply adding the following to the Dockerfile:

```bash
ENV LANG C.UTF-8
RUN locale-gen en_US.UTF-8
```

Success!  After I added those and rebuilt the image, all the medium tests ran perfectly.  I'm going to make a PR to add these to the Dockerfile.
