### ISSUE TITLE
Add support for the Light Table IDE

### ISSUE THREAD

**Issue by pjdelport** [ubuntu/ubuntu-make#231]
Home page: http://lighttable.com/

**Comment by pjdelport** [comment]
Related issue: #105 (Clojure support)

**Comment by didrocks** [comment]
Thanks for this suggestion! Sounds like a nice opportunity for anyone who wants to make a good first ubuntu make contribution :)

**Comment by LyzardKing** [comment]
LightTable is now in master

**Comment by Tankypon** [comment]
Should be closed I think

**Comment by didrocks** [comment]
Correct! done now :)
