### ISSUE TITLE
go1.5.3 download checksum mismatch

### ISSUE THREAD

**Issue by Paradiesstaub** [ubuntu/ubuntu-make#232]
When trying to download the newest go version using ubuntu-make I get the following error:

```
Choose installation path: /home/foobar/.local/share/umake/go/go-lang
Downloading and installing requirements                                      |
ERROR: https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz couldn't finish download: The checksum of https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz doesn't match. Corrupted download? Aborting.
100% |#######################################################################|
ERROR: The checksum of https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz doesn't match. Corrupted download? Aborting.
```

**Comment by didrocks** [comment]
You are indeed right! with the latest release of go (1.5.3 14 hours ago), they changed from sha1 to sha256. I just pushed a fix in trunk and will do a quick release today.

If you want to get the fix meanwhile, you can:
```
git clone ttps://github.com/ubuntu/ubuntu-make.git
cd ubuntu-make
bin/umake go
```

Sorry for the inconvience ;)

**Comment by Paradiesstaub** [comment]
Your commited fix works. Thanks for the great work your doing here!

**Comment by didrocks** [comment]
yw, thanks for reporting this :) (I'll close the bug a day after the release so that people can find a reference)

**Comment by didrocks** [comment]
I guess we can close it now :)
