### ISSUE TITLE
How to know the version of the package software

### ISSUE THREAD

**Issue by Alvarz** [ubuntu/ubuntu-make#235]
How can I know the version of the software to install, I mean how can I know the version of Eclipse or Unity3d Editor ?

**Comment by LyzardKing** [comment]
They are always the latest versions available on the official websites.
Eclipse: https://www.eclipse.org/downloads/
For the moment the unity3d editor for linux is on a forum page (http://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/)

**Comment by Alvarz** [comment]
Yeah, that's what i mean, how we can know the eclipse version in umake is the latest and the unity3d version isn't the latest build for linux?

We need some --version command I think

**Comment by didrocks** [comment]
If we don't deliver last version, we failed. The goal of the project is to always deliver latest and greatest from upstream. I don't think implementing for each framework a --version is doable or even desirable.
@LyzardKing removed the 2 hardcoded versions that we had, so we should be quite fine on that side.

**Comment by Alvarz** [comment]
ok, thanks for the reply and keep doing a great job!

**Comment by didrocks** [comment]
thanks ;)

I'm closing that bug report for now then, feel free to raise bugs if you notice that we don't deliver latest and greatest on any framework!
