### ISSUE TITLE
Differentiate between open-source/proprietary and free/paid software

### ISSUE THREAD

**Issue by Janghou** [Ubuntu/ubuntu-make#243]
I love the ease `ubuntu-make` offers to install updated dev-software, but as a Linux user I prefer to run free open-source software only.

Let `ubuntu-make` somehow indicates if a program is open-source/free before installation.

I would suggest:
- on installation window
- on list, --help

Now it feels like Windows (shareware): you can install easily but not use freely.

**Comment by didrocks** [comment]
Maybe not on installation, but yeah, good one for the incoming list option! Whoever wants to help on this will be more than welcome (once the --list option is available)

**Comment by Janghou** [comment]
I would prefer a warning on installation as well.

Be aware people will copy hints from **how-to`s/blogs/askubuntu** without using list or whatever:
`umake ide phpstorm` 

Maybe adding something like:
`umake ide --nonfree ide1`
`umake ide --paid phpstorm`
to differentiate between proprietary but no cost software (1st) and proprietary paid software (2nd).

any command without `--paid` or `--nonfree` will only install open-source software.
Also to honour  Debian or GNU tradition

**Comment by didrocks** [comment]
I can understand that some people would want that.
However, I'm not really sure this is really in the way we think about ubuntu make or what we want to promote (the warning is like "don't take that one" in asense). I guess people are coming for a task (like "installing <x>"), and so they just want to have it installed, without a warning or any additional block to press "enter".

Having it written down in --help or --list is already a way for people interested in the matter to fetch that information (in addition to the upstream website, of course, which should be the main information).

**Comment by Janghou** [comment]
`umake ide --nonfree ide1`
`umake ide --paid phpstorm`

Actually my above suggestion doesn't force any warning nor additional block to press enter.
Like said before I'm afraid most people will copy a `one-liner` from a `how-to`, so they don't see `--list` at all. 
Actually Linux is brilliant because you can install and use software easily, secure and free, without pulling your credit-card.

I can understand from a Vendor standpoint they prefer an easy install and 'Evaluate for free 30 days` button to show up. 

I'm not saying that it should be difficult to install `non-libre` software. Just be honest and transparent, make it clear before installation. Even the Ubuntu Software Centre does that.

**Comment by LyzardKing** [comment]
Closing since it's inactive.
