### ISSUE TITLE
Visual Studio Code disabled: website moved to client-side javascript only

### ISSUE THREAD

**Issue by overbid** [ubuntu/ubuntu-make#247]
Today when I ran `umake ide visual-studio-code`
I got ERROR: Download page changed its syntax or is not parsable

**Comment by didrocks** [comment]
Hey @overbid and thanks for reporting this bug!

Indeed, it seems that Microsoft changed the website overnight, hence you are getting this error. After looking at it for a little bit, I'm afraid I can't get a fix quickly for this: they moved to a pure client-side javascript that we can't handle for now and don't have good hooks for fixed urls as other ones.

For now (and this release), I just disabled the framework so that it's not offered as a choice as a band-aid solution. I'm retitling this bug report for making it clearer what the issue is.

You can only download and install it manually as such, for the time being, I'm afraid.

**Comment by tbroyer** [comment]
It looks like the links can be found in `https://code.visualstudio.com/scripts/download.js`; though there are 2 such links for each platform ("insiders" and "preview") and it would be hard to pick the right one in a forward-compatible way without actually running the script.
Let's hope they sort it out when exiting "beta".

BTW, did you get in touch with Microsoft about this?

**Comment by didrocks** [comment]
I did send an email when we provided the first support version, but didn't get any answer. If you have any contact, I'll be really interested :)

Yeah, I agree with your that parsing the script would be a fallback, but I'm afraid as well of a forward-compatible to ensure this doesn't break again.

**Comment by hoovercj** [comment]
@tbroyer: I saw your tweet. The team is very responsive to issues created on their repository so you might log something there: https://github.com/Microsoft/vscode/issues

**Comment by LyzardKing** [comment]
I had a look as well. If we can consider the downloads.js file stable we 
can use that. But it seems to me that it has only developer 
versions(preview and insiders). Or am I wrong?
The tar file that you download from the website 
(https://code.visualstudio.com/Docs/?dv=linux64) is missing.

**Comment by tbroyer** [comment]
@LyzardKing the `dv=linux64` triggers the download code from `download.js`, which will use the "preview" link ("insiders" link is used in the presence of an additional `build` parameter in the query-string)

@hoovercj Thought about it, but they made it clear on one issue that the "VS Code" product you download from code.visualstudio.com is not the same (not even the same license) as the `vscode` project (even though they use the same source code); so `vscode` is about the OSS project, and not directly related to the "product" from Microsoft (several issues about, e.g. "cannot install extensions when building from source" have been closed and link to that issue comment).
Specifically, see https://github.com/Microsoft/vscode/issues/1230 and https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005
As a Microsoftee (or soon to become one), do you think we should use that channel then?
(thanks for chiming in btw)

**Comment by hoovercj** [comment]
@tbroyer Regarding #1230, they did end up making [https://github.com/Microsoft/vscode/wiki/Previous-Releases](this).

They've been really responsive on both twitter and github, but I've been following their behavior pretty closely and it seems that they prefer to open issues about almost anything so it can be triaged and followed up on. If you're hoping to get a concrete answer from them I'd open an issue.

**Comment by didrocks** [comment]
@hoovercj Excellent! Thanks for the head's up. Do you think we should use that page as a stable (at least more stable) way to download existing versions?

Great to see that they are speeding up the responsivness and engagement with the community! :)

**Comment by tbroyer** [comment]
@didrocks Latest version is 0.10.8 (released a few days ago), and the page has just been updated (few hours ago) to include 0.10.6; so unfortunately no umake shouldn't use it.

**Comment by tbroyer** [comment]
Hey, just stumbled on https://github.com/Microsoft/vscode/issues/1084 (linked from 1230 actually): they do *have* permalinks (those form the `download.js` a priori) so actually umake doesn't even need to scrape any web page!

**Comment by didrocks** [comment]
Excellent finding @tbroyer!

Going to use this then (will work on that this evening or early afternoon if nobody beats me to it ;))

**Comment by LyzardKing** [comment]
I'm taking a shot at it.. can we hardcode those links then? Or parse the download.js?

**Comment by LyzardKing** [comment]
I tried with the links hardcoded (we can do that if they're permalinks, right?).
Another thing that is wrong is the icon (now called code.png instead of vscode.png)

**Comment by hoovercj** [comment]
@tbroyer awesome find, I hope that works for you guys.

**Comment by didrocks** [comment]
@LyzardKing: I think download_link should be the license, and then, we can use the traditional parser hook to always return true with the hardcoded links (as static urls) based on arch. If you want, I can give a quick commit to it, you review and modify tests, that works for you?

**Comment by LyzardKing** [comment]
Sound good! :)

**Comment by didrocks** [comment]
@LyzardKing: here are the commit swhich should bring that support, do you have time having a look at adapting (and reenabling the tests then?) I guess we can remove (as we are using now baseinstaller now) the additional tests in the medium test and just use traditional inheritance (but with multiple servers this time).

Tell me if you need any help! :)

**Comment by didrocks** [comment]
(and ensure you branch from https://github.com/ubuntu/ubuntu-make/tree/vsc-fix) ;)

**Comment by LyzardKing** [comment]
Looks good! Simple and clean. I'll have a look at the tests

**Comment by LyzardKing** [comment]
The tests work. I linked the second commit, but the ide tests should be there as well.

**Comment by didrocks** [comment]
Just released 16.02.1 with that fix! Thanks again to everyone involved in the discussion :)
