### ISSUE TITLE
IntelliJ stuff will soon need Java 8

### ISSUE THREAD

**Issue by Tinche** [ubuntu/ubuntu-make#249]
As per http://blog.jetbrains.com/pycharm/2016/02/pycharm-5-1-eap-is-open/

Do we have openjdk-8-jdk in the repos on all supported Ubuntu versions?

**Comment by LyzardKing** [comment]
Not in 14.04. (If this is the right place to look. I'm not running it any more)
http://packages.ubuntu.com/search?suite=trusty&searchon=names&keywords=openjdk-8

**Comment by LyzardKing** [comment]
I had a look at the openjdk issue a few days ago, since I wanted to install openjdk-8 as a requirement if available. It seems to me that if/when this actually happens (not in eap), we'll need to make pycharm available for distros with openjdk-8

**Comment by LyzardKing** [comment]
If we switch the dependency to openjdk-8-jdk on 14.04 it will be flagged as not installable. As soon as the --list option gets merged this will become

**Comment by didrocks** [comment]
I really wonder how much they can afford not running on 14.04 LTS out of the box. @Tinche I think you already contacted them in the past, as they aware that they won't be installable OOTB on 14.04 LTS due to lack of openjdk8?
@LyzardKing: the link you were looking for as well can be directly launchpad: https://launchpad.net/ubuntu/+source/openjdk-8 :)

On Ubuntu Make, we can always push it to the Ubuntu Make ppa itself (backporting the newer version from there), but I'm not a big fan of pushing this kind of major upgrade, even if they are opt-in :)

**Comment by LyzardKing** [comment]
Jetbrains releases a tarfile for the EAP versions that has the jdk included. Does something like that exist for the stable release?

**Comment by Tinche** [comment]
PyCharm 2016.1 is out. I upgraded by doing `umake ide pycharm-professional --remove; umake ide pycharm-professional`, it worked fine.

PyCharm now bundles its own Java:
```
tin@tin-desktop ~/.local/share/umake/ide/pycharm-professional/jre/jre> bin/java -version
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
openjdk version "1.8.0_76-release"
OpenJDK Runtime Environment (build 1.8.0_76-release-b32)
OpenJDK 64-Bit Server VM (build 25.76-b32, mixed mode)
```

Too bad they didn't use the fontfix version, now I have to manually change this or endure ugly fonts :) Anyway, the JRE/JDK deps can be removed, I think.

**Comment by LyzardKing** [comment]
Great. Do they include jayatana as well?
Is this valid for other intellij ides?

**Comment by Tinche** [comment]
On Jayatana, interestingly, yes:

```
tin@tin-desktop ~/.local/share/umake/ide/pycharm-professional> find . -iname '*ayatana*'
./license/jayatana_license.txt
./lib/jayatana-1.2.4.jar
```

but it's not used by default. Also, I don't think it actually works:
```
tin@tin-desktop ~/.local/share/umake/ide/pycharm-professional> set -x JAVA_TOOL_OPTIONS -javaagent:(pwd)/lib/jayatana-1.2.4.jar
tin@tin-desktop ~/.local/share/umake/ide/pycharm-professional> bin/pycharm.sh 
Picked up JAVA_TOOL_OPTIONS: -javaagent:/home/tin/.local/share/umake/ide/pycharm-professional/lib/jayatana-1.2.4.jar
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
Failed to find Premain-Class manifest attribute in /home/tin/.local/share/umake/ide/pycharm-professional/lib/jayatana-1.2.4.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

The Ubuntu one works though. It used to be blacklisted in pycharm.sh, but it's not any more.

Don't know about the other IDEs, any volunteers to check?

**Comment by Tinche** [comment]
Maybe I'm just setting the wrong JAR, the working one is called `/usr/share/java/jayatanaag.jar`.

**Comment by LyzardKing** [comment]
Yes I know it was blacklisted. We removed the dependency not too long ago.
It would be good to hear from someone at intellij to figure out what they
want to do going on.
For now we could remove the dependency from the ides we know have this.
As far as I know some eap versions have java included. Not all of them,  so
it would be good to be sure, just so we don't have to add and remove it for
every update.

**Comment by LyzardKing** [comment]
Closing since the jetbrains ides include a custom jre (as discussed in #282 )
Let's reopen if needed.
