### ISSUE TITLE
can't install eclipse

### ISSUE THREAD

**Issue by Yangliu1522** [ubuntu/ubuntu-make#257]
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 141, in get_sha_and_start_download
    res = download_result[self.sha512_url]
KeyError: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/2/eclipse-java-mars-2-linux-gtk-x86_64.tar.gz.sha512&r=1'

**Comment by Tinche** [comment]
Hello!

Could you paste the output of ``umake --version`` here, so we know exactly which version you're having issues with?

**Comment by Yangliu1522** [comment]
sorry 
$ umake --version
16.02.1

**Comment by aaronnew** [comment]
I have the same Error when use `umake ide eclipse` on Ubuntu 14.04 and umake version 16.02.1.

**Comment by LyzardKing** [comment]
Does it download anything if you open that link in a browser?

**Comment by nehrka** [comment]
Some Error here on 16.04 and umake --version 16.02.1

**Comment by LyzardKing** [comment]
Update umake from the ppa. The correct version now is 16.04.
If it still doesn't work let me know

**Comment by LyzardKing** [comment]
@Yangliu1522 Is this issue still present?

**Comment by Maxattax97** [comment]
I'm having a very similar error to this in version 17.03, directly from the PPA when trying to install `umake ide eclipse-cpp`:

```
Choose installation path: /home/bats/.local/share/umake/ide/eclipse-cpp
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 140, in get_sha_and_start_download
    res = download_result[self.sha512_url]
KeyError: 'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/neon/3/eclipse-cpp-neon-3-linux-gtk-x86_64.tar.gz.sha512&r=1'
Downloading and installing requirements                                                              |
```

I'm able to download this file from my browser.
