### ISSUE TITLE
Accepting Android Studio EULA

### ISSUE THREAD

**Issue by kemelzaidan** [ubuntu/ubuntu-make#258]
Accepting Android Studio EULA in pt-br l18n needs you to type `um(a)` what makes no sense at all!!!
It's even hard to understand what it wants you to type. That's what the prompt shows:

`[Eu aceito(um(a))/Eu não aceito(N)]`

```
$ umake --version && lsb_release -a
16.02.1
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

**Comment by didrocks** [comment]
Hey! Sorry that the translation doesn't make sense!

As we don't have any native pt speaker in our team, do you mind changing the translation yourself? Two ways:
- either you change in https://translations.launchpad.net//ubuntu-make? It should show up the languages configured and you can change existing translations.
- or (maybe easier) you can change it in https://github.com/ubuntu/ubuntu-make/blob/master/po/pt_BR.po, through a github PR?

I'll then merge it, thanks :)

**Comment by apprafael** [comment]
Hello,

I typed:

EU ACEITO

It's work!

**Comment by didrocks** [comment]
Excellent! closing then! :)

**Comment by didrocks** [comment]
Fixed in master.
