### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Lorandb** [ubuntu/ubuntu-make#260]
`umake --version
16.02.1`
Hi,
I am using umake to install eclipse, it's an awesome tool. But i didn't find a way to remove eclipse. Is there a way to remove the installed ide?

**Comment by didrocks** [comment]
Thanks for using ubuntu-make!

This is quite easy, just set --remove to the command line, like:
`umake --remove ide eclipse`

You can see all options via `--help` btw :)

**Comment by Lorandb** [comment]
thanks, i didn't see it. I was searching for over hours.
