### ISSUE TITLE
[Feature] Adding new Eclipse IDE

### ISSUE THREAD

**Issue by rosolko** [ubuntu/ubuntu-make#262]
Hello.
Do you think about adding new Eclipse IDE - [Che](https://www.eclipse.org/che)?
Thanks.

**Comment by LyzardKing** [comment]
It should be similar to the eclipse standard.
It has its own download page, that links to https://eclipse.com
We can't reuse the eclipse basic class, since there is no checksum file 
(it seems)

**Comment by LyzardKing** [comment]
@rosolko Is the eclipse che ide still a thing?
I can't seem to find it on their website

**Comment by rosolko** [comment]
@LyzardKing Yes, it's still rocks.
You can't find because of IDE has own [page](https://www.eclipse.org/che/) and [repo ](https://github.com/eclipse/che)

**Comment by LyzardKing** [comment]
Ah ok...
In the web page I was looking at the local install, but that has no reference to the eclipse ide.
The download link at the bottom of the page is the right one

**Comment by LyzardKing** [comment]
The only version of eclipse che now available is the docker image. So this installer is no longer needed.
If this is wrong please reopen.
