### ISSUE TITLE
Unicode/ascii character error with agreement when installing VSCode

### ISSUE THREAD

**Issue by Robin-Law** [ubuntu/ubuntu-make#263]
Environment: Ubuntu Wily, XFCE and LXDE, Crouton on Toshiba Chromebook 2

When attempting to install Visual Studio Code, there is a character in the agreement that is causing the script to throw unless one specifies a unicode LANG.

`(wily)user@localhost:~$ umake ide visual-studio-code

Choose installation path: /home/user/.local/share/umake/web/visual-studio-code

ERROR: Unhandled exception

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/ui/__init__.py", line 42, in display
    cls.currentUI._display(contentType)
  File "/usr/lib/python3/dist-packages/umake/ui/cli/__init__.py", line 63, in _display
    print(contentType.content)
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 74: ordinal not in range(128)`

Found that the 75th character in the agreement is indeed odd:

`MICROSOFT PRE-RELEASE SOFTWARE LICENSE TERMS
MICROSOFT VISUAL STUDIO CODE �`

Workaround:

Specify LANG when running:
`(wily)user@localhost:~$ LANG="en_US.UTF-8" umake ide visual-studio-code`

I see that a similar issue has been logged before, but fixed. It seems that Microsoft agreements are very prone to breaking the scripts.

**Comment by LyzardKing** [comment]
Hi!
Try having a look at #137 
What does this command return?
`env | grep LANG`
