### ISSUE TITLE
ERROR: You can't remove Visual Studio Code as it isn't installed

### ISSUE THREAD

**Issue by mrmanicou** [ubuntu/ubuntu-make#264]
Installed with 
`umake ide visual-studio-code`

Tried to uninstall immediately with:
`umake ide visual-studio-code --remove`

I get the message

> ERROR: You can't remove Visual Studio Code as it isn't installed

Am I missing something here?

**Comment by LyzardKing** [comment]
The version in github works.
They changed the license and the exec filename, so that should be the problem.

**Comment by zerkms** [comment]
Not sure if relevant but reinstalling (to get the newer version, not sure if there is a better way to do that) crashes with

```
[I Accept (a)/I don't accept (N)] a
Downloading and installing requirements                                                                                                          |
100% |###########################################################################################################################################|
Installing Visual Studio Code
ERROR: Unhandled exception                   #                                                                                                   |
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 411, in decompress_and_install_done
    self.post_install()
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 722, in post_install
    exec=self.exec_path,
AttributeError: 'VisualStudioCode' object has no attribute 'exec_path'
```

**Comment by LyzardKing** [comment]
Did you reinstall with the version from github or the release?
There have been a few changes in the VSCode download from microsoft.
They changed the exec filename, that's why you get that error.
We'll have a release out as soon as we fix a few tests.
You can download from git for the meantime.

**Comment by zerkms** [comment]
@LyzardKing I would wait until a new `umake` package is built, thanks

**Comment by LyzardKing** [comment]
As soon as there is a new release you can reinstall visual-studio-code.
That should fix these issues :)

**Comment by zerkms** [comment]
@LyzardKing great :-) Btw, am I missing something or there is really no way to `upgrade` a particular ide, but only to install it again? As well as there is no way to know if any of them (I have multiple ides from the `ide` category installed) have updates?

**Comment by LyzardKing** [comment]
It's not that easy. Some tools update themselves (Jetbrains, Eclipse, 
and others). For the others what we would be doing is essentially 
downloading the complete package again.
(https://github.com/ubuntu/ubuntu-make/issues/74)

One thing we could have is a --list-upgradable option, to see if there 
is anything that needs updating, but that would require parsing all the 
different websites.
