### ISSUE TITLE
Cannot install android-ndk

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ubuntu/ubuntu-make#265]
When I try to install android-ndk with
```
umake android android-ndk
```
I get:
```
ERROR: The checksum of http://dl.google.com/android/repository/android-ndk-r11-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
```

**Comment by LyzardKing** [comment]
The download page changed from .bin to .zip and from md5 to sha1.
I'm working on a fix.

**Comment by connelevalsam** [comment]
Yeah having the same ish. It's not fair changing things any how like that. Pissing me off. Gotta look for another way to install

**Comment by LyzardKing** [comment]
What version of umake do you have?
You need the latest (16.05).

**Comment by connelevalsam** [comment]
yea i'm using the latest

**Comment by LyzardKing** [comment]
It works for me. Could it be a redirection to a localized version of the webpage?
https://developer.android.com/ndk/downloads/index.html

**Comment by mantono** [comment]
I got the same, but for version r12b. If I download it manually it does not get corrupted and matches the correct sha1 sum.

**Comment by jcubic** [comment]
I'm using umake 16.05 and have the same error when calling:
```
sudo umake android --accept-license
```

**Comment by jcubic** [comment]
Grabbing the umake from github solved the issue.

**Comment by LyzardKing** [comment]
@jcubic As you can see in the readme the recommended version is in the ppa.
That version is now 17.03, yours, at 16.05 is outdated.
Updating will fix this issue.

**Comment by gauravdhiman** [comment]
@jcubic how to update umake to latest version from github. Instructions given on umake github page tell to install from ppa. Kindly share the steps to install it from github.

**Comment by LyzardKing** [comment]
To have the latest version from master always up to date you can install
the snap.
You can run: snap install ubuntu-make
Then the command to run is ubuntu-make.umake instead of umake.

**Comment by gauravdhiman** [comment]
I get below error when I install snap and try to install `ubuntu-make` using it.

```
gauravdhiman@gd-asus-501:~/proj/node/meteor/push-notify-app-1.5ver$ sudo snap install ubuntu-make
ZOE ERROR (from /usr/lib/snap/snap): error opening file (/usr/share/snap/Zoe/HMM/install)
ZOE library version 2013-02-16
gauravdhiman@gd-asus-501:~/proj/node/meteor/push-notify-app-1.5ver$ snap --version
ZOE ERROR (from /usr/lib/snap/snap): zoeParseOptions: unknown option (--version)
ZOE library version 2013-02-16
gauravdhiman@gd-asus-501:~/proj/node/meteor/push-notify-app-1.5ver$ 
```

**Comment by jcubic** [comment]
I didn't install `umake` from repo, I think (don't remember) I've cloned and run `umake` from directly (because I've only needed to run in once): 
```bash
git clone <repo>
./umake/bin/umake android --accept-license
```
