### ISSUE TITLE
installing webstorm not working

### ISSUE THREAD

**Issue by maxdeepfield** [ubuntu/ubuntu-make#267]
`ERROR: An error occurred while downloading https://www.jetbrains.com/webstorm/download/download_thanks.jsp?os=linux: 404 Client Error: Not Found`

**Comment by LyzardKing** [comment]
What version of umake are you running?
You can see it with "umake --version"

**Comment by maxdeepfield** [comment]
it seems I use umake that does not support --version :)
`umake: error: unrecognized arguments: --version`

**Comment by LyzardKing** [comment]
You should install an updated version.
We try to fix things every time a website changes sintax.
For Jetbrains we now use a different approach.
For the latest release you can add the ppa: ppa:ubuntu-desktop/ubuntu-make

**Comment by maxdeepfield** [comment]
Thank you for your help, updated ubuntu-make works very nice.
