### ISSUE TITLE
ERROR: Unhandled exception during installation of Idea Ultimate

### ISSUE THREAD

**Issue by maks1m** [ubuntu/ubuntu-make#268]
ubuntu 15.10, umake version 16.02.1
I had installed Idea 15 and during overriding it to version 2016.1 with `umake ide idea-ultimate`
I get such error

> Downloading and installing requirements                                       |
> 100% |########################################################################|
> Installing Idea Ultimate
> ERROR: Unhandled exception        #                                            |
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
>     function(_args, *_kwargs)
>   File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 411, in decompress_and_install_done
>     self.post_install()
>   File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 289, in post_install
>     exec='"{}" %f'.format(self.exec_path),
> AttributeError: 'IdeaUltimate' object has no attribute 'exec_path'

But Idea is downloaded correctly and I am able to run it installation folder.
Also I have the same issue with installing android on ubuntu 16.04.

**Comment by IrynaZahladko** [comment]
hi! try to change installation path. Do not use default and use not-hidden folder for it. It helped in my case. Good luck!

**Comment by didrocks** [comment]
You should use the Ubuntu Make ppa on both distros, which has the latest with the Idea and android fixes due to newer versions: https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ubuntu-make

I guess at some point, we'll add messages on error after checking that the ppa has a newer version! Tell me if that doesn't fix it for you and I'll reopen the bug.

**Comment by vivekpn** [comment]
I am also getting the same error for Ubuntu 16.04, Ubuntu Make Version 17.03 with `umake ide idea-ultimate`. Please feel free to ask if I can provide you any additional information.

**Comment by LyzardKing** [comment]
Hi. It should have been fixed with #447 
It's not released in the ppa yet, but if you install the snap you'll have the latest version from github.
Or you can (for now) remove idea-ultimate and then install.
