### ISSUE TITLE
Android Studio Unity launcher shows duplicate icons (Matching fails)

### ISSUE THREAD

**Issue by om26er** [ubuntu/ubuntu-make#270]
If I create desktop file for android studio from within android studio everything works great i.e. there is only one icon for android studio in the launcher, but if the icon is created by Ubuntu Make then there are two launchers shown in the launcher after android studio is started.

I compared the two desktop files and apparently the one that is created by android studio contains the line:
  StartupWMClass=jetbrains-studio

while the once created by umake contains:
  StartupWMClass=jetbrains-android-studio

**Comment by LyzardKing** [comment]
Hi!
That seems to be the only thing to fix then. Great job looking at it!
I wonder if we should let things that can create their own .desktop file deal with that.
@didrocks , what do you think?

**Comment by didrocks** [comment]
There is no way for us to get android studio creating on demand on icon, so yeah, ideally, if there was a way to ask it to create it, that would be great, in reality, this isn't working. We then have to create it ourself.

Does it make sense?

**Comment by LyzardKing** [comment]
It offers to create a launcher, but only when you start it the first time.
We'd have to start it automatically after a successful install.
Otherwise we can apply the change to the file we create

**Comment by didrocks** [comment]
Let's apply the change, doing it in a sec :)

**Comment by MikeChou** [comment]
I still got two icons in the launcher when running Android Studio.
The line in `android-studio.desktop` is:
`StartupWMClass=jetbrains-android`

Software versions:
Ubuntu: 16.10 clean install
Android Studio: 2.2.1
ubuntu-make: 16.05 from official repo of ubuntu 16.10

Any idea what might have caused this?

**Comment by MikeChou** [comment]
@didrocks 
https://github.com/ubuntu/ubuntu-make/commit/42799755b7717e3d7d767d4dc6cd79003be63d06
It should be `jetbrains-studio` instead of `jetbrains-android`
