### ISSUE TITLE
[Feature] Add terminal commands for each tool installed

### ISSUE THREAD

**Issue by rakshithravi1997** [ubuntu/ubuntu-make#272]
It would be great if I could have a terminal command for each tool that I install. For example, after I install Android Studio, I'd love to have the ability to launch Android Studio from a terminal window by typing "android-studio". This would be epic! Please implement this!

**Comment by LyzardKing** [comment]
Hi!
This already exists. You can see the links created in ~/.local/share/umake/bin
We use the name of the .desktop file as the command name

**Comment by rakshithravi1997** [comment]
Agreed. It does create links in ~/.local/share/umake/bin. I saw that, and I'm happy it puts all the executables in one place. But all I'm saying is, shouldn't it also place links in /usr/bin so that each application can be started from any folder?

**Comment by LyzardKing** [comment]
The links in ~/.local/share/umake/bin work the same. The folder is in PATH.

**Comment by rakshithravi1997** [comment]
So sorry. I did not know this exists. Forgive me. Delete this issue if possible please
