### ISSUE TITLE
Cannot use ubuntu make ppa because of "weak digest"

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ubuntu/ubuntu-make#273]
I added the ubuntu make repository:
```
sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
```
Now, when I run
```
apt-get update
```
I get:
```
W: gpgv:/var/lib/apt/lists/ppa.launchpad.net_ubuntu-desktop_ubuntu-make_ubuntu_dists_xenial_InRelease: The repository is insufficiently signed by key 399B698EEA9EF163B6F9A0F62CC98497A1231595 (weak digest)
```
I am not sure where the problem is and if this is the correct place to report it, tell me if I should report elsewhere :-).

**Comment by didrocks** [comment]
The issue here is that I didn't push any package to the ubuntu-make ppa for xenial. This will happen next Tuesday normally :) Meanwhile, the version without ppa (in the distribution proper) is the latest.

I'll keep you posted once next release is available!

**Comment by LyzardKing** [comment]
This should be fixed, right @didrocks ?
Or is there an issue with other versions of ubuntu?

**Comment by didrocks** [comment]
Indeed, this should be fixed as pushed a new version in the ppa some months ago. We'll do a new release for yakkety as well. This can be closed (please reopend if it's not fixed for you)
