### ISSUE TITLE
Unity3D Checksum Consistent Failure

### ISSUE THREAD

**Issue by TomAshley303** [ubuntu/ubuntu-make#274]
I have a solid Internet connection...

:~$ umake games unity3d
[sudo] password for user:
Choose installation path: /home/user/.local/share/umake/games/unity3d
Downloading and installing requirements                                                                                                                                                                  |
ERROR: http://download.unity3d.com/download_unity/linux/unity-editor-installer-5.4.0b10+20160317.sh couldn't finish download: The checksum of http://download.unity3d.com/download_unity/linux/unity-editor-installer-5.4.0b10+20160317.sh doesn't match. Corrupted download? Aborting.
100% |###################################################################################################################################################################################################|
ERROR: The checksum of http://download.unity3d.com/download_unity/linux/unity-editor-installer-5.4.0b10+20160317.sh doesn't match. Corrupted download? Aborting.

:~$ umake games unity3d
[sudo] password for user:
Choose installation path: /home/user/.local/share/umake/games/unity3d
Downloading and installing requirements                                                                                                                                                                  |
ERROR: http://download.unity3d.com/download_unity/linux/unity-editor-installer-5.4.0b10+20160317.sh couldn't finish download: The checksum of http://download.unity3d.com/download_unity/linux/unity-editor-installer-5.4.0b10+20160317.sh doesn't match. Corrupted download? Aborting.
100% |###################################################################################################################################################################################################|
ERROR: The checksum of http://download.unity3d.com/download_unity/linux/unity-editor-installer-5.4.0b10+20160317.sh doesn't match. Corrupted download? Aborting.

**Comment by TomAshley303** [comment]
A similar issue was once reported and fixed for the "Go" package where the hashing algorithm was changed: [https://github.com/ubuntu/ubuntu-make/issues/232](https://github.com/ubuntu/ubuntu-make/issues/232)

**Comment by LyzardKing** [comment]
The forum page we use hasn't changed the checksum.
I tried to see what it downloads and it gets the correct file and checksum.
If you can, try running umake -v games unity3d.
That prints out the debug notes.
You can stop it when the download starts, and you can see a line "INFO:
start downloading ...".
There you can see the checksum it's downloading
