### ISSUE TITLE
Webstorm install fails

### ISSUE THREAD

**Issue by jbhelfrich** [ubuntu/ubuntu-make#275]
umake install ide webstorm fails with
```
ERROR: https://www.jetbrains.com/webstorm/download/download_thanks.jsp?os=linux couldn't finish download: 404 Client Error: Not Found
ERROR: An error occurred while downloading https://www.jetbrains.com/webstorm/download/download_thanks.jsp?os=linux: 404 Client Error: Not Found
```
Presumably this is because the new version just launched.  The new download link is https://www.jetbrains.com/webstorm/download/download-thanks.html?platform=linux

**Comment by LyzardKing** [comment]
Hi! Seems like you're using an older version of umake.
For jetbrains we use a different system.
Check what version you have.
You probably should install the ppa to be sure you have the latest updates.

**Comment by didrocks** [comment]
Closing as it seems this is fixed (no feedback). Just for the record, we got a new release available in the same ppa: ppa:ubuntu-desktop/ubuntu-make.
