### ISSUE TITLE
[Feature] Add adb to path when installing android-sdk

### ISSUE THREAD

**Issue by rakshithravi1997** [ubuntu/ubuntu-make#278]
adb is definitely required in the $PATH when installing android-sdk as adb is a very frequently used item with android-sdk

There are 2 ways to solve this problem:
1. Link adb from the android-sdk folder to ~/.local/share/umake/bin
This would allow the user to do adb stuff from the terminal

But however my more preferred option would be:
2. Add android-tools-adb as a dependency to android-sdk.
This would install android-tools-adb when installing the android-sdk and would keep things clean. By keeping things clean I mean, consider this scenario: what if I have android-tools-adb already installed and adb was added to $PATH using the first option? This would create an ambiguity.
Therefore, I prefer adding android-tools-adb as a dependency. Please let me know what you guys think :)

**Comment by didrocks** [comment]
Hey! Thanks for reporting this feature request.

2 isn't an option, as newer Android Studio version (and so? I guess that can happen with different sdk version) did require newer vresion of adb that android-tools-adb package provided in the distro. It's thus better to add to the user's path the version from the current sdk folder.

We are adding to PATH `tools/` and `platform-tools/`, from the android sdk repository, and the last one is where adb normally lives, or am I missing something?

**Comment by rakshithravi1997** [comment]
I don't understand why we can't add android-tools-adb as a dependency. If a newer version of adb is required, then why not keep the universe repository updated with the latest version? So that way adding it as a dependency wouldn't be an issue....or maybe I don't understand something here?

As for linking it, wouldn't it suffice to just link adb from `platforms-tools/` to the `umake/bin/` folder? I thought it would be easier and more cleaner than to add `tools/` and `platform-tools/` to PATH...I could be wrong though

**Comment by didrocks** [comment]
On not updating: -> this is because once an Ubuntu release is done, we don't update to newer non bug-fix version as they are bringing new features, and can then, bring new breakages. There are few exceptions to this rules like browser, but 99% of the packages have a version set in stone as per distro policy for stability reason.

Symlinking isn't an option to `umake/bin` for upgrade and downgrade purpose. What happens when a new upgrade (which happens outside of Ubuntu Make) brings new tools? They won't have symlinks and thus wouldn't be accessible. Same with removal with a dangling symlink. What are you trying to sort out? We add both directory to PATH for the current user and track that (when you remove the framework, we remove them as well thanks to a special tag). We are doing that across frameworks, is that not working for you?

**Comment by rakshithravi1997** [comment]
Like I said, if I have `android-tools-adb` installed, and `platform-tools/` was added to PATH, wouldn't it create an ambiguity issue for the `adb` command? Moreover, we need to make sure the `platform-tools/adb` command is called for the `adb` command as this is the more latest version. If you can somehow sort that out, then cool! That would be awesome!

P.S. Off topic questions:
1. There's one thing about `umake` that I'm not sure about. Say a new version of `unity3d` or `android-studio` has been released, will `umake` notify me of it and allow me to upgrade with ease?
2. I'm a developer and would love to contribute. How can I help? I was thinking of making a GUI tool for `umake` but is there anything more important I could help with?

**Comment by didrocks** [comment]
I think adb -version would help, but yeah, I guess in your case, you can find that confusing. I don't have any good answer to this though, any more thoughts welcomed! I did check that adb doesn't have any hardcoded path and so, rely on $PATH for executing tools, so in that specific case, we are fine :)

Off topic answers:
1. We debated that for quite a while in various issues, you can have a look at https://github.com/ubuntu/ubuntu-make/issues/74 to get the context and look at the issues linked into it for pros and cons arguments.
2. Excellent! I tried to summarize the different kind of contributions to http://blog.didrocks.fr/post/How-to-help-on-Ubuntu-Developer-Tools-Center. I guess expanding supports with tests for things you care about is a great one, or just look at the list of issues and work on some!
The GUI is a possible one. I architectured the code to be compatible with different backends. "cli" is one of them. The whole code is async, using an event main loop and sending data. I'm sure some slights refactoring would be needed, but normally, you can even install multiple frameworks in parallel. Just a warning, this isn't a lightweight tasks if done properly and can be quite technically involved :)

Keep me posted, can't wait to see your first contributions to Ubuntu Make!
