### ISSUE TITLE
Install IDEA Ultimate and IDEA Community side-by-side with distinct .desktop files

### ISSUE THREAD

**Issue by tbroyer** [ubuntu/ubuntu-make#283]
IDEA Ultimate and IDEA Community both create a `jetbrains-idea.desktop` file. Maybe there's a reason for that but it would be to have distinct files so I could install both side-by-side (I have an Open Source license for Ultimate 15, would like to use Community 2016.1 to a) try the 2016.1 version and b) do non-opensource work).

According to https://github.com/JetBrains/intellij-community/blob/72f7a8bd5e65d664e1271b4bd89e7243d72ddaa4/platform/platform-impl/src/com/intellij/ui/AppUIUtil.java#L126 and https://github.com/JetBrains/intellij-community/blob/d39d057e04d9b510d710dcfda12b848a21327259/platform/platform-impl/src/com/intellij/ide/actions/CreateDesktopEntryAction.java#L153-L156, the Community Edition uses a `jetbrains-idea-ce` WMClass, and will (when asked) create a `jetbrains-idea-ce.desktop` entry (also tried it from a manually installed IDEA Community 2016.1, and that's indeed how it works).

I therefore suggest changing IDEA Community installation to create a `jetbrains-idea-ce.desktop` file instead of `jetbrains-idea.desktop`.

**Comment by LyzardKing** [comment]
I changed that in the openjdk-8 fork (not pushed to the pr yet).
I changed the idea one like you said, and the pycharm ones as well.
Ideally I think they should be like the ones that the ide creates on launch.
