### ISSUE TITLE
Visual Studio Code not parsable

### ISSUE THREAD

**Issue by bodzin89** [ubuntu/ubuntu-make#284]
Hi, guys! Today, I faced with problem that VSCode ide not download: 

> ERROR: Download page changed its syntax or is not parsable

Think trouble in links that UMAKE parsed.

**Comment by LyzardKing** [comment]
Hi.
It works on my end, what version of ubuntu-make do you have?

**Comment by bodzin89** [comment]
@LyzardKing, 16.01.2. Strange,cause my teammate says, that he have version 16.03 =/

**Comment by bodzin89** [comment]
Sorry, guys! I found problem - when I add repository, by default dist was "vivid", i change it and everything went ok!
