### ISSUE TITLE
[Question] Update tools

### ISSUE THREAD

**Issue by gperdomor** [ubuntu/ubuntu-make#285]
How can i update the current installed tools? Fir example from PhpStorm 10 to the new PhpStorm 2016.1?

**Comment by Tinche** [comment]
```umake ide phpstorm --remove && umake ide phpstorm``` is the best we can do for now. There's an open issue (#74) but nothing in the pipe so far so make this easier.

**Comment by gperdomor** [comment]
@Tinche thanks :D
