### ISSUE TITLE
Android studio installation error

### ISSUE THREAD

**Issue by rosolko** [ubuntu/ubuntu-make#288]
Hi,

After 2.0 [release](http://android-developers.blogspot.com.by/2016/04/android-studio-2-0.html) seems like something changed on download and installation flow.

When I use `umake android android-studio` and select destination folder console return an error:
`ERROR: We were expecting to find a license on the download page, we didn't.`

**Comment by LyzardKing** [comment]
Also the links for android-studio and android-sdk changed.
And dl.google.com is now running with https.
I'll try and fix it soon
