### ISSUE TITLE
[Feature] LiteIDE (golang ide)

### ISSUE THREAD

**Issue by dionysius** [ubuntu/ubuntu-make#291]
Any consideration on adding LiteIDE?
Project Source: https://github.com/visualfc/liteide

**Comment by LyzardKing** [comment]
This has a snap now.
Since the binary releases are not on github but sourceforge, it's a lot harder to add them to umake (as far as I can tell).

**Comment by LyzardKing** [comment]
The releases are on github now, so I would like to add liteide, but they depend on libpng12, not available any more in the repositories.
I that gets fixed it'll be added
The upstream issue is: https://github.com/visualfc/liteide/issues/462

**Comment by dionysius** [comment]
Thank you for your effort! Appriciate it

**Comment by LyzardKing** [comment]
I guess we can close for now and revisit if/when this will be fixed.
No point in keeping this issue open if the ide itself is never going to support new versions of ubuntu, right?
