### ISSUE TITLE
Enable Spring Tool Suite support

### ISSUE THREAD

**Issue by vpavic** [ubuntu/ubuntu-make#294]
I'm opening this issue to track the progress of re-enabling Spring Tool Suite support that was initially added in #240 and disabled in 9c76c31.

Although not my primary IDE, I use STS from time to time, and have recently attempted to install it using Ubuntu Make (version 16.04). This was quite confusing experience since [changelog](https://github.com/ubuntu/ubuntu-make/blob/master/debian/changelog) suggested STS was supported since `16.02` but `umake ide --help` said otherwise. This led me to inspect the project source and commit history and discover the commit that disables support.

Please document that STS support is disabled as this will potentially save time for some users.

**Comment by LyzardKing** [comment]
It should be added again with #430

**Comment by LyzardKing** [comment]
@vpavic It's merged back now!
