### ISSUE TITLE
umake android --accept-license

### ISSUE THREAD

**Issue by THUFIR** [ubuntu/ubuntu-make#296]
if you leave off the accept license, it doesn't work.  Please update wiki page.

**Comment by LyzardKing** [comment]
Hi.
Could you be more specific?
What are you trying to install?
There's been a change in the Android websites, and commit has fixed them
(#289).
I don't think it's been uploaded yet to the repository, but it's coming.

>

**Comment by viki77** [comment]
so , that is why when i tryed to install android studio i got this error : 
ERROR: A default framework for category Android was requested where there is none
usage: umake android [-h] {android-ndk} ...

**Comment by LyzardKing** [comment]
android-studio and android-sdk have been fixed in the commit.
That's why there is no default framework (should be android-studio)

**Comment by viki77** [comment]
how i should install android studio and the sdk ,now?

**Comment by LyzardKing** [comment]
Fixed in the new release (16.05)
