### ISSUE TITLE
Github doesn't recognize humanity

### ISSUE THREAD

**Issue by didrocks420** [ubuntu/ubuntu-make#299]
I am getting an error message about GitHub thinking I am not a human.

This is ironic since I made a feature suggestion about adding more Humanity to Ubuntu, #87 

I think GIthub should verify the humanity of the author of the following post since nothing they say makes sense:

https://github.com/ubuntu/ubuntu-make/issues/87#issuecomment-96516580

![humanity](https://cloud.githubusercontent.com/assets/11903487/8753505/967cda9e-2c79-11e5-8380-b20801cf9f9b.png)

**Comment by didrocks** [comment]
I don't think this is related to Ubuntu Make at all, closing.
