### ISSUE TITLE
IDE request

### ISSUE THREAD

**Issue by JurrianFahner** [ubuntu/ubuntu-make#300]
Is it also possible to add [Netbeans](https://netbeans.org/downloads/) to umake ide?

**Comment by LyzardKing** [comment]
Netbeans is already in umake.
Ubuntu 16.04 has removed openjdk-7. That might be the problem
There's been a commit to fix it adding openjdk-8 as a possible dependency. 
It's now fixed in master, and it will be in the next release of ubuntu-make

**Comment by LyzardKing** [comment]
Netbeans now installs in xenial, with umake version 16.05. Closing.
