### ISSUE TITLE
Visual studio code - wrong .desktop entry

### ISSUE THREAD

**Issue by ntun04** [ubuntu/ubuntu-make#304]
The program doesn't appear in menu because of  wrong entry in .desktop file (ubuntu 16.04). The program name is _code_ with small letter. The exec path in .desktop file is _Code_ with capital letter.

**Comment by LyzardKing** [comment]
This has already been changed some time ago.
You must have an older version of ubuntu-make.
Try installing the version from the ppa:
$ sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
$ sudo apt update
$ sudo apt install ubuntu-make

>

**Comment by ntun04** [comment]
I see. I thought the one in 16.04 is up-to-date with the ppa. Thanks.

**Comment by LyzardKing** [comment]
Wait. The one in the ppa should be fixed.
What version do you have?
If I'm not wrong the fix should have occurred in 16.03

**Comment by ntun04** [comment]
Sorry, I didn't say it clearly. I'm not using ppa. I using version 16.02.1 included in Ubuntu 16.04.

**Comment by LyzardKing** [comment]
Then if you use the ppa it will work.
