### ISSUE TITLE
Error1 Kotlin

### ISSUE THREAD

**Issue by TecnoHands** [ubuntu/ubuntu-make#305]
Hi, im try install Kotlin, but give me this error:

umake kotlin
Choose installation path: /home/******/.local/share/umake/kotlin/kotlin-lang
Downloading and installing requirements                                        |
ERROR: [Errno 1] Operación no permitida
100% |#########################################################################|
ERROR: Package requirements can't be met: [Errno 1] Operación no permitida

We need help. Thanks.

**Comment by LyzardKing** [comment]
What version of umake are you using? (run umake --version)
The new one (16.05) fixed some issues with ubuntu xenial (openjdk-8 dependency)

**Comment by andresrivas1506** [comment]
same with umake android
$ umake --version
16.05

**Comment by andresrivas1506** [comment]
work with `sudo umake <option>`

**Comment by LyzardKing** [comment]
umake will ask for the password if it is needed (es. to install dependencies).
@TecnoHands Are you still having this issue?

**Comment by TecnoHands** [comment]
@canonical-is  sorry but im change to Win10, i Dont have time to fight whit linux today haha

**Comment by TecnoHands** [comment]
@LyzardKing sorry but im change to Win10, i Dont have time to fight whit linux today haha

**Comment by didrocks** [comment]
No worry, closing then as nobody confirmed it :)
