### ISSUE TITLE
Arduino IDE installation error

### ISSUE THREAD

**Issue by robikovacs** [ubuntu/ubuntu-make#308]
I've tried to install Arduino IDE with umake and this happened:
`Downloading and installing requirements                                       |
ERROR: https://www.arduino.cc/download_handler.php couldn't finish download: 502 Server Error: Bad Gateway for url: https://www.arduino.cc/download_handler.php
100% |########################################################################|
ERROR: 502 Server Error: Bad Gateway for url: https://www.arduino.cc/download_handler.php
`

**Comment by connelevalsam** [comment]
https://github.com/ubuntu/ubuntu-make/issues/265 is the same ish. Was told t'was a change

**Comment by LyzardKing** [comment]
This was an issue with the arduino website earlier today.
The website seems to be working now. Do you mind trying again?

**Comment by robikovacs** [comment]
@LyzardKing you are right. It works now, thank you.
