### ISSUE TITLE
umake of eclipse no longer working

### ISSUE THREAD

**Issue by docbill** [ubuntu/ubuntu-make#309]
It looks like umake is now pulling java 8 instead of java 7...

JVM terminated. Exit code=13
/usr/bin/java
-Dosgi.requiredJavaVersion=1.7
-XX:MaxPermSize=256m
-Xms256m
-Xmx1024m
-jar /opt/eclipse//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
-os linux
-ws gtk
-arch x86_64
-showsplash /opt/eclipse//plugins/org.eclipse.platform_4.5.2.v20160212-1500/splash.bmp
-launcher /opt/eclipse/eclipse
-name Eclipse
--launcher.library /opt/eclipse//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so
-startup /opt/eclipse//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.appendVmargs
-exitdata 0
-product org.eclipse.epp.package.java.product
-vm /usr/bin/java
-vmargs
-Dosgi.requiredJavaVersion=1.7
-XX:MaxPermSize=256m
-Xms256m
-Xmx1024m
-jar /opt/eclipse//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar

**Comment by didrocks** [comment]
The release is out! This should be fixed in Ubuntu Make 16.09. You can download it from the Ubuntu Make ppa: https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ubuntu-make/ (on 14.04 LTS, 15.10, 16.04 LTS and yakkety). Do not hesitate to reopen the bug if that didn't fix it for you!

**Comment by docbill** [comment]
Success! Here is the build log:

[docbill/ubuntu-umake-eclipse build details](https://hub.docker.com/r/docbill/ubuntu-umake-eclipse/builds/blsv4lbbsjqdwg7etspabpk/)

As that might be useful to compare with if there are future regressions.

Thanks,

Bill

**Comment by vivekjib** [comment]
Sorry to bother, but still I am unable to install Eclipse using umake 16.09 version cloned directly from the master. 
What should I do ?

**Comment by didrocks** [comment]
@vivekjib do you mind pasting your logs (in a new bug report I guess), with umake ide eclipse -v ?
