### ISSUE TITLE
umake android possible broken?

### ISSUE THREAD

**Issue by Maokei** [ubuntu/ubuntu-make#310]
[I Accept (a)/I don't accept (N)] a
Downloading and installing requirements                                                                                                                                                                                                       |
ERROR: [Errno 1] Operation not permitted

**Comment by andresrivas1506** [comment]
+1

**Comment by andresrivas1506** [comment]
works for me with `sudo umake android`

**Comment by LyzardKing** [comment]
Do you have the permission to write to the folder you chose?

**Comment by Maokei** [comment]
Yeah full permission to write.

2016-05-18 17:00 GMT+02:00 Galileo Sartor <notifications@github.com>:

> Do you have the permission to write to the folder you chose?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ubuntu/ubuntu-make/issues/310#issuecomment-220054295>
>



-- 
-Rickard Johansson-
Matane

**Comment by Maokei** [comment]
I don't have any issues anymore after trying it out some more, android was
the only install I had problems with.

2016-05-21 23:22 GMT+02:00 Rickard Johansson <rickard.joh@gmail.com>:

> Yeah full permission to write.
>
> 2016-05-18 17:00 GMT+02:00 Galileo Sartor <notifications@github.com>:
>
>> Do you have the permission to write to the folder you chose?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ubuntu/ubuntu-make/issues/310#issuecomment-220054295>
>>
>
>
>
> --
> -Rickard Johansson-
> Matane
>



-- 
-Rickard Johansson-
Matane

**Comment by didrocks** [comment]
So, I guess that was a transient issue due to a lot of people downloading Android Studio during Google IO
