### ISSUE TITLE
Visual Studio Code isn't at its latest version.

### ISSUE THREAD

**Issue by UniK** [ubuntu/ubuntu-make#312]
> Ubuntu Make is a command line tool which allows you to download the **latest version** of popular developer tools on your installation[...] &Dagger;

The Visual Studio Code (`visual-studio-code`) is still at version 1.0.0,  although the **latest version** is 1.1.0.

I couldn't find any information on how to update/upgrade (e.g.: `umake update/upgrade`) the dev-tools installed with ubuntu-make to the **latest version** (as promised in Ubuntu Wiki &Dagger;). 

Can you please provide further information on how the "latest version"-promise suppose to work?

----
&Dagger; https://wiki.ubuntu.com/ubuntu-make
System: (Ubuntu 16.04 with ppa:ubuntu-desktop/ubuntu-make)

**Comment by LyzardKing** [comment]
Ubuntu Make lets you download the latest version.
At the moment it can't update tools.
Some have autoupdate (like intellij ides I think)
For the others at the moment you can reinstall, replacing the folder with the previous version.
You can have a look at #74.

**Comment by UniK** [comment]
Just for reference... the following will upgrade the installation to the latest version:
`$ umake ide visual-studio-code --remove && umake ide visual-studio-code`
