### ISSUE TITLE
Add option to install with no confirmation needed

### ISSUE THREAD

**Issue by igorbrites** [ubuntu/ubuntu-make#315]
I'm writing some scripts to automate environment development configuration in my company, and it would be great if umake doesn't need to confirm the folder of the installing IDE.

**Comment by didrocks** [comment]
You can go with it without confirming, as per:
`umake <category> <framework> <install_path>`
Does that solve your need?

Please run umake --help and that should give you some hints about the syntax :)

**Comment by igorbrites** [comment]
Works like a charm. umake --help doesn't show this option, unfortunately.

Thanks!
