### ISSUE TITLE
Android studio not being installed

### ISSUE THREAD

**Issue by mbtamuli** [ubuntu/ubuntu-make#316]
I just did a clean install of Ubuntu 16.04. At first it was not even showing android-studio. But I followed the instructions in #307 and now it is showing the android-studio option but it gets stuck at the point where it says downloading. I checked my network and there is no problem. Please, help?

![screenshot from 2016-05-20 06-31-25](https://cloud.githubusercontent.com/assets/10382077/15414067/a898d9f8-1e54-11e6-9459-f1414c994ed0.png)

**Comment by JarrodHenry** [comment]
Google I/O is currently going on, so demand is probably pretty high. I attempted to reproduce this bug and it started downloading after about 2 minutes.

**Comment by didrocks** [comment]
Are you still getting this issue or that was just a server load?

**Comment by mbtamuli** [comment]
@didrocks Will have to check.

**Comment by LyzardKing** [comment]
Not an issue anymore
