### ISSUE TITLE
Medium Tests fail

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#318]
Seeing the following error when running the medium tests:

`
ERROR: http://www.scala-lang.org/download/ couldn't finish download: HTTPConnectionPool(host='www.scala-lang.org', port=80): Max retries exceeded with url: /download/ (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
ERROR: An error occurred while downloading http://www.scala-lang.org/download/: HTTPConnectionPool(host='www.scala-lang.org', port=80): Max retries exceeded with url: /download/ (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
`

**Comment by jravetch** [comment]
@didrocks Any thoughts?

**Comment by didrocks** [comment]
No, I guess it's based on your configuration, just did another run:

$ ./runtests tests/medium/test_scala.py 
[nose.plugins.manager] DEBUG: DefaultPluginManager load plugin nose_json = nose_json.plugin:JsonReportPlugin
[nose.plugins.manager] DEBUG: DefaultPluginManager load plugin cov = nose_cov:Cov
[nose_cov] DEBUG: nose-cov options
[nose_cov] DEBUG: nose-cov configure
.
----------------------------------------------------------------------
Ran 1 test in 11.436s

OK
