### ISSUE TITLE
How to confirm when ide is exist and need continute quietly.

### ISSUE THREAD

**Issue by overbid** [ubuntu/ubuntu-make#321]
How do I do this in same way like --accept-license.

**Comment by didrocks** [comment]
There is unfortunately no facility for this right now. If you don't care and just want to reinstall, I would then just rm -rf to download that path and rerun umake.
Would that work for you?

**Comment by butla** [comment]
Checking if an IDE exists or if a new version of it is available would be really useful for managing IDE installations with Ansible (and that's what I'm doing). I guess that kind of ties in with #74.

**Comment by LyzardKing** [comment]
There's a different idea with the two projects.
We pulled from upstream directly, instead of rebuilding.
I'm closing since this problem is open in another issue and is being considered.
