### ISSUE TITLE
Firefox Developer Edition: Missing menu bar (File, Edit, …) at top 

### ISSUE THREAD

**Issue by jnachtigall** [ubuntu/ubuntu-make#322]
I have the problem as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1176610 At first I thought it would be a general Firefox problem, hence my [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1176610#c3) at this bug. But it turns out, that my Firefox Developer Profile does not even have a `ui.use_unity_menubar` setting in `about:config` (whereas Firefox 47 stable has this and it is set to `true`). 

I manually added `ui.use_unity_menubar` with `true` but still no menu bar when the window is full width (not fullscreen). 

Can you reproduce this that there are no menu bars? I think it is a Ubuntu and not a Firefox problem, and most likely because the Firefox ubuntu make ships is somewhat different from the customized Ubuntu Firefox.

**Comment by LyzardKing** [comment]
As far as I can tell this is not an ubuntu-make problem. The discussion seems to be here now: https://bugzilla.mozilla.org/show_bug.cgi?id=1301670

Closing as not pertinent to ubuntu-make
