### ISSUE TITLE
Firefox Developer Edition: 1. Too big Icon 2. visible under normal Firefox icon when opened

### ISSUE THREAD

**Issue by jnachtigall** [ubuntu/ubuntu-make#323]
![anim](https://cloud.githubusercontent.com/assets/3307404/15989346/70d114fe-3074-11e6-9a4f-97c7a536f60b.gif)

Two small nitpicks here:

**One:** At the beginning of the screencast: **Firefox Developer Edition icon is too big**. This is a UX inconsistency. Steps to reproduce:
1. Search for application "Firefox". 
2. Notice the difference in size between normal and developer editon. Icon of developer is way too big

**Two:** Later in the screencast I open the Developer Edition: When opening Firefox developer Editon, then the **edition window is attached to the normal firefox icon**. This is very irritating, especially when I run normal Firefox and Editon at the same time because I cannot easily differentiate the open windows.

**Comment by abdulhannanali** [comment]
@jnachtigall The second issue about the Firefox Developer Edition not being blue is not the issue specific to Ubuntu Make. I suppose if the first one too is, I just did a manual install of Firefox Developer Edition and even If I don't have the normal Firefox open, it gives the same icon the one with the orange in it. However, the internals are totally different.

**Comment by LyzardKing** [comment]
The second issue is solved.
The first one is an issue to raise with Mozilla.
At the moment I'll close this issue, since there's nothing regarding umake.
