### ISSUE TITLE
Automatic Update of Umake Software

### ISSUE THREAD

**Issue by JasoonS** [ubuntu/ubuntu-make#327]
Does Umake automatically update software? Is it something that you can set?

[Here](https://wiki.ubuntu.com/ubuntu-make) it says, under point three: "We want to ensure that the supported developer environment is always functional by always downloading the latest version from upstream."

To refine my Question, I want to know if you can explicitly define versions of software, and if you can view a list of available software versions? And if so, how you do this?

(Sorry if it seems very trivial to you guys here.)

**Comment by LyzardKing** [comment]
Hi.
Umake downloads the latest version available from the official websites.
It cannot download specific versions, except some ides that have the stable
and beta version.
The update is not supported by umake.
Some things (jetbrains ides and Firefox, not sure about others) have their
own updaters.
For the others you can reinstall when a new version is available, but it's
not something that umake does.
There's a discussion on the updates in a previous issue.
Hope this answers your question.

**Comment by JasoonS** [comment]
That answers my question perfectly. Thank you very much :)

**Comment by PranavBhattarai** [comment]
>  The update is not supported by umake.

This is a disappointment. 
There should have been a way/option for a user to automate this without having to go through all this bullsh..
