### ISSUE TITLE
about wireless connection

### ISSUE THREAD

**Issue by MASWOODKHAN** [ubuntu/ubuntu-make#333]
there is some problem in ubuntu 16.04 LTS version it connect with the wifi only and only when router placed very close to it whereas if i use another os like windows,fedora, they connect very easily upto large enough distance wifi router than ubuntu. I have searched every where but yet I am unable to remove this problem. I have HP-NOTEBOOK with Realtek Network Adapter.Even this problem was also in Ubuntu 14.04 LTS that's why  I installed 16.04 but it hasn't resolve yet.

**Comment by didrocks** [comment]
I think you want to raise the bug on launchpad against the ubuntu project. ubuntu-make is a tool for ubuntu for developer environment, so quite different from the bug you are looking after.

**Comment by MASWOODKHAN** [comment]
Sir ,then what i need to do.Could you suggest me please......

**Comment by didrocks** [comment]
Open a bug on launchpad.net against the ubuntu project.
