### ISSUE TITLE
vscode not on path

### ISSUE THREAD

**Issue by sudopluto** [ubuntu/ubuntu-make#334]
vscode is not added to path by default

**Comment by Tinche** [comment]
Can you try 'visual-studio-code' as the command?

**Comment by sudopluto** [comment]
Yup that works. I was used to "code" being added to the path, I didn't bother to look for anything else. My bad.

**Comment by Tinche** [comment]
I don't exactly know why it's not just 'code', but you can create an alias
or a symlink easily. :)

**Comment by LyzardKing** [comment]
We couldn't use the executable filename because all the eclipse versions use 'eclipse', Firefox web users 'firefox'. To do the same for all we decided to use the folder name, the install name. It wasn't more generic, but I understand it's not too clear
