### ISSUE TITLE
.profile not sourced until rebooting

### ISSUE THREAD

**Issue by tschf** [ubuntu/ubuntu-make#335]
I just installed nodejs through umake, and found it wasn't being added to the path after re-launching terminal. This is the output from the install:

```
trent@birroth:~$ umake nodejs
Choose installation path: /home/trent/.local/share/umake/nodejs/nodejs-lang
Downloading and installing requirements                                        |
100% |#########################################################################|
Installing Nodejs Lang
/usr/bin/env: ‘node’: No such file or directory                                |
|##############################################################################|
You need to restart your current shell session for your Nodejs Lang installation to work properly
Installation done
trent@birroth:~$ 
```

I interpreted `restart your current shell` as restarting the terminal (gnome-terminal), but found if I restart the terminal, my PATH is missing the nodejs path that was added to `~/.profile` as part of the installation (and as such, `node` still not on my path). 

Only after I restart my system do I find that the updated `~/.profile` is sourced. Is `shell` referring to my desktop session? Or is it likely I have a bad config somewhere and it should be sourced each time I launch (gnome-)terminal.

**Comment by didrocks** [comment]
`shell` is expected to more understood as a shell session.
Some programs always restart a new shell session when you open a new window. Some forks and reuse the current session like gnome-terminal (from gnome-terminal-server) and so on.
Maybe rephrasing would be a good idea, like "log back"

**Comment by tschf** [comment]
Yeah, sounds good. Or `re-login`? Not sure what's best! 

`You may need to log back in for your NodeJS installation to work properly`?

**Comment by didrocks** [comment]
Sounds good to me! I would accept a good patch changing this terminology + adapting tests ;)

**Comment by tschf** [comment]
Happy to do that. Just reviewing the tests folder (large|medium/test_nodejs.py), can't see exactly what I'd have to adapt, but will let you know if I get stuck. :-)
