### ISSUE TITLE
Umake working very slow 

### ISSUE THREAD

**Issue by InsaneNaman** [ubuntu/ubuntu-make#336]
I am unable to install Pycharm just because it is downloading very slow .My normal internet connetion speed is 20mbps but umake is downloading very slowly . 

I am currently using ubuntu 16.04

**Comment by didrocks** [comment]
Hey, thanks for trying Ubuntu Make!
This could be an issue on the intellij server side (for pycharm), Did you get that regularly or just randomly?

**Comment by InsaneNaman** [comment]
Sorry , For Late reply . I was busy in college stuff and also i didn't get notification . 
About the issue,i was getting it regularly but recent update have removed all the bugs and now its working fine with an awesome speed :) . Thanks
