### ISSUE TITLE
Rust Install Broken

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#337]
Rust seems to have changed their URL for the downloads page:

``
Rust Lang is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)] y
Choose installation path: /home/jravetch/.local/share/umake/rust/rust-lang
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/rust.py", line 98, in get_metadata_and_check_license
    link = (soup.find('div', class_="install")
AttributeError: 'NoneType' object has no attribute 'find'
``
The new URL is https://www.rust-lang.org/en-US/downloads.html

Since they added region selector, how do you want to handle this?

**Comment by samatjain** [comment]
Confirming; has been broken for the past month or so I think.

**Comment by unitumit** [comment]
I don't know if this is the right way, I am on Ubuntu 16.04, I was able to install Rust after editing the download URL in rust.py

sudo gedit /usr/lib/python3/dist-packages/umake/frameworks/rust.py

then changed line 60 saying "download_page="https://www.rust-lang.org/downloads.html" to " https://www.rust-lang.org/en-US/downloads.html"

**Comment by jravetch** [comment]
#339 Fixes this.  @LyzardKing @didrocks Can you please release a new version of umake with the fix?

**Comment by didrocks** [comment]
Sorry, I was on holidays for the past couple of days :) Sure, releasing a new version is on my plan this week (probably Thursday/Friday). Thanks to all of you for reporting and working on that one :)

**Comment by didrocks** [comment]
The release is out! This should be fixed in Ubuntu Make 16.09. You can download it from the Ubuntu Make ppa: https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ubuntu-make/ (on 14.04 LTS, 15.10, 16.04 LTS and yakkety). Do not hesitate to reopen the bug if that didn't fix it for you!
