### ISSUE TITLE
 umake -v ide eclipse not working

### ISSUE THREAD

**Issue by mKadiyan** [ubuntu/ubuntu-make#342]
umake -v ide eclipse
 umake -v ide eclipse-jee  

above commands  not working in version 16.05

below is the log

Choose installation path: /home/phenom/.local/share/umake/ide/eclipse
INFO: Start downloading DownloadItem(url='https://www.eclipse.org/downloads/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.eclipse.org
INFO: https://www.eclipse.org/downloads/ download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org/downloads/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None)] done
ERROR: Download page changed its syntax or is not parsable

**Comment by didrocks** [comment]
The release is out! This should be fixed in Ubuntu Make 16.09. You can download it from the Ubuntu Make ppa: https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ubuntu-make/ (on 14.04 LTS, 15.10, 16.04 LTS and yakkety). Do not hesitate to reopen the bug if that didn't fix it for you!

**Comment by mKadiyan** [comment]
Fixed !!!
