### ISSUE TITLE
Android install broken

### ISSUE THREAD

**Issue by Industrial** [ubuntu/ubuntu-make#346]
Hi.

The android install is broken;

```
Choose installation path: /home/tom/.local/share/umake/android/android-ndk
Terms and Conditions

...

[I Accept (a)/I don't accept (N)] a
Downloading and installing requirements                                                                                                                                                                |
ERROR: https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip couldn't finish download: The checksum of https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
100% |#################################################################################################################################################################################################|
ERROR: The checksum of https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
```

**Comment by LyzardKing** [comment]
It works on my end. Try running it again adding a -v after umake

**Comment by royepperson** [comment]
I just tried installing on Ubuntu 16.04 using umake [-v] android android-ndk with and without the -v.  I get the same checksum error either way. I tried this last night with the same results.....   Bummer.... have some android development I would like to do....

**Comment by LyzardKing** [comment]
With the -v option you can see what the checksum is, to check that it read
the correct thing.
There should be a release in the next few days

**Comment by royepperson** [comment]
Here is the information from -v

INFO: Start downloading DownloadItem(url='https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip', checksum=Checksum(checksum_type=<ChecksumType.md5: 'md5'>, checksum_value='170a119bfa0f0ce5dc932405eaa3a7cc61b27694'), headers=None, ignore_encoding=False, cookies=None) to a temp file
INFO: Starting new HTTPS connection (1): dl.google.com
Downloading and installing requirements
ERROR: https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip couldn't finish download: The checksum of https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
INFO: All pending downloads for [DownloadItem(url='https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip', checksum=Checksum(checksum_type=<ChecksumType.md5: 'md5'>, checksum_value='170a119bfa0f0ce5dc932405eaa3a7cc61b27694'), headers=None, ignore_encoding=False, cookies=None)] done
100% |#########################################################################|
ERROR: The checksum of https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
roye@roye-ubuntu:~$ umake -v android android-ndk

**Comment by LyzardKing** [comment]
As I thought...the checksum is actually correct..
There should be a release soon (next few days)
Or you could pull the repo and test master.

**Comment by royepperson** [comment]
Thanks for the feedback. I'm new to ubuntu/linux and github. I'm willing to
try/test a release when ready

**Comment by didrocks** [comment]
The release is out! This should be fixed in Ubuntu Make 16.09. You can download it from the Ubuntu Make ppa: https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ubuntu-make/ (on 14.04 LTS, 15.10, 16.04 LTS and yakkety). Do not hesitate to reopen the bug if that didn't fix it for you!

**Comment by ordinaryperson** [comment]
I'm getting this same error.
umake 16.11.1
ubuntu 16.04 LTS
android 2.3.0.8
checksum: 214cee47ef7a628c712ae618f5aab6c2a56a72aa479a50937d4cad5a0abf8435

"ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip doesn't match. Corrupted download? Aborting."

**Comment by LyzardKing** [comment]
@ordinaryperson 
It's a different error.
It's been fixed in master and will be in the next release.

**Comment by ordinaryperson** [comment]
@LyzardKing Awesome. Any idea when that is?

**Comment by LyzardKing** [comment]
We're trying to fix as many issues before the release. But should be soon

**Comment by aenertia** [comment]
Broken in artful again in artful - can we automate retrieval of checksums so when google/upstream repackage etc the script doesn't need to republished?

`
INFO: Installation ['libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386', 'openjdk-8-jdk'] pending                 |
INFO: Start downloading DownloadItem(url='https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip', checksum=Checksum(checksum_type=<ChecksumType.sha1: 'sha1'>, checksum_value='1383cfd47441e5f820b6257a1bdd683e0e980bc76c7f2027ef84dc2e6ad2f17f'), headers=None, ignore_encoding=False, cookies=None) to a temp file
Downloading and installing requirements
ERROR: https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip couldn't finish download: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip doesn't match. Corrupted download? Aborting.
INFO: All pending downloads for [DownloadItem(url='https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip', checksum=Checksum(checksum_type=<ChecksumType.sha1: 'sha1'>, checksum_value='1383cfd47441e5f820b6257a1bdd683e0e980bc76c7f2027ef84dc2e6ad2f17f'), headers=None, ignore_encoding=False, cookies=None)] done
100% |#############################################################################################################|
ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip doesn't match. Corrupted download? Aborting.
`

**Comment by LyzardKing** [comment]
There hasn't been a deb in a while, but you can install the snap, so you
always have the latest release and fixes directly from master.

As for the checksums, they have never been built in, they are read from the
download page. So the issue only arises when the page tags change.

**Comment by Lexoka** [comment]
I'm getting the same issue:

```
INFO: All pending downloads for [DownloadItem(url='https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip', checksum=Checksum(checksum_type=<ChecksumType.md5: 'md5'>, checksum_value='42aa43aae89a50d1c66c3f9fdecd676936da6128'), headers=None, ignore_encoding=False, cookies=None)] done
100% |###########################################################################################################################################################|
ERROR: The checksum of https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
```

I'm not sure why this issue keeps popping up, but having the option to ignore checksum mismatches might help.

**Comment by LyzardKing** [comment]
You're not running the latest version.
android-ndk has been modified a while back to check for sha1, not md5.
You need to install the ppa, as stated in the readme.
