### ISSUE TITLE
can't install firefox developer edition

### ISSUE THREAD

**Issue by maks1m** [ubuntu/ubuntu-make#347]
System: linux mint cinnamon 18
umake version: 16.05
if I try to: `umake web firefox-dev `
I got: `ERROR: Download page changed its syntax or is not parsable`

**Comment by LyzardKing** [comment]
It's been fixed in master and will land in the next update

**Comment by maks1m** [comment]
@LyzardKing thanks for the reply, do you know when the new release will roll out?

**Comment by LyzardKing** [comment]
I'd say as soon as we can check that everything is working properly ;)

**Comment by maks1m** [comment]
Ok, thanks :)
