### ISSUE TITLE
Unable to install Eclipse

### ISSUE THREAD

**Issue by vivekjib** [ubuntu/ubuntu-make#349]
$ ./umake --version
16.09

$ ./umake ide eclipse -v
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Android SDK as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Android Studio as it's not installable on this configuration.
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: libxtst6:i386 isn't installed
INFO: libxext6:i386 isn't installed
INFO: libxi6:i386 isn't installed
INFO: libxt6:i386 isn't installed
INFO: libxpm4:i386 isn't installed
INFO: libxmu6:i386 isn't installed
INFO: libgtk2.0-0:i386 isn't installed
INFO: libatk1.0-0:i386 isn't installed
INFO: libcairo2:i386 isn't installed
INFO: libexpat1:i386 isn't installed
INFO: libfontconfig1:i386 isn't installed
INFO: libfreetype6:i386 isn't installed
INFO: libglib2.0-0:i386 isn't installed
INFO: libice6:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libpng12-0:i386 isn't installed
INFO: libsm6:i386 isn't installed
INFO: libxau6:i386 isn't installed
INFO: libxcursor1:i386 isn't installed
INFO: libxdmcp6:i386 isn't installed
INFO: libxfixes3:i386 isn't installed
INFO: libx11-6:i386 isn't installed
INFO: libxinerama1:i386 isn't installed
INFO: libxrandr2:i386 isn't installed
INFO: libxrender1:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
INFO: libasound2:i386 isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Arduino as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Netbeans as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register CLion as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register DataGrip as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse CPP as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Eclipse PHP as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Idea as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Idea Ultimate as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PhpStorm as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PyCharm as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PyCharm Educational as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register PyCharm Professional as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register RubyMine as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register Spring Tools Suite as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't available on this platform
INFO: Don't register WebStorm as it's not installable on this configuration.
INFO: default-jre isn't installed
INFO: clang isn't installed
INFO: libicu-dev isn't installed
usage: umake ide [-h] {visual-studio-code,lighttable} ...
umake ide: error: argument framework: invalid choice: 'eclipse' (choose from 'visual-studio-code', 'lighttable')

**Comment by didrocks** [comment]
Thanks for your bug report and opening a new one ;)

The relevant info is:
```INFO: openjdk-7-jdk isn't available on this platform```
It seems you don't have access to either `openjdk-7-jdk` or `openjdk-8-jdk` packages from your install, do you mind running:
```
apt-cache policy openjdk-7-jdk
apt-cache policy openjdk-8-jdk
```

and write the results here? Which version of ubuntu are you running on?

**Comment by vivekjib** [comment]
$ apt-cache policy openjdk-8-jdk
openjdk-8-jdk:
  Installed: 8u91-b14-3ubuntu1~16.04.1
  Candidate: 8u91-b14-3ubuntu1~16.04.1
  Version table:
 *** 8u91-b14-3ubuntu1~16.04.1 500
        500 http://in.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://in.archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     8u77-b03-3ubuntu3 500
        500 http://in.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

But I have JAVA. This is not open jdk .

$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by didrocks** [comment]
the java you are selecting shouldn't be an issue here. It should meet the openjdk-8-jdk alternative requirement. @LyzardKing: you did work on that part IIRC, do you mind having a quick look?

**Comment by LyzardKing** [comment]
It seems like the openjdk-8 part is missing entirely.
You should see this in the log:
```
INFO: openjdk-7-jdk isn't available on this platform
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-8-jdk isn't installed
INFO: openjdk-7-jdk | openjdk-8-jdk isn't installed
```
Are you running from the ppa or from a source clone?

**Comment by vivekjib** [comment]
From source clone, cloned using master branch.

**Comment by LyzardKing** [comment]
Are you sure it's up to date? Try a pull of the repo or the version in the ppa

**Comment by vivekjib** [comment]
Yes, that was up to date. I made sure of it before opening a new issue. For clarification, you can see umake version in the first comment.

**Comment by cjmochrie** [comment]
I am experiencing a near identical issue with umake installed using apt.
```
$ umake --version
16.02.1
```

 All the same logs appear (open-jdk-7-jdk isn't installed etc.).

```
$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

This is a brand new ubuntu 16.04 install so perhaps there are other dependencies I'm missing?

**Comment by didrocks** [comment]
@cjmochrie: Hey! Yes, we mostly do some updates in our ppa when things are updating upstream.
Current version is 16.11.1. Instructions on how to add that ppa is on https://wiki.ubuntu.com/ubuntu-make. You should be able to install eclipse after this.
I think we should make those instructions clearer in some way when running ubuntu make without the ppa. (like a warning or so). Keep me posted if it fixes it under your environment.

**Comment by cjmochrie** [comment]
Awesome, thanks @didrocks - worked perfectly after using the ppa!
