### ISSUE TITLE
Upgrade to 16.09 from PPA - error registering using register-python-argcomplete3

### ISSUE THREAD

**Issue by nenomina** [ubuntu/ubuntu-make#350]
I'm getting this error for the last update from the PPA.
(Ubuntu 16.04 x64)

```
Setting up ubuntu-make (16.09~xenial1) ...
/var/lib/dpkg/info/ubuntu-make.postinst: 6: /var/lib/dpkg/info/ubuntu-make.postinst: register-python-argcomplete3: not found
dpkg: error processing package ubuntu-make (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 ubuntu-make
```

**Comment by didrocks** [comment]
Thanks for this bug report.

I'm a little bit puzzled, did you do anything when installing ubuntu-make, like force skipping dependencies? The package depends on `python3-argcomplete` (check if it's installed) which provides this script.
If that's the case, you can run: `which register-python-argcomplete3` to look if it's in `$PATH` (it should be in `/usr/bin/register-python-argcomplete3`) and report back the results here so that we can debug.

**Comment by nenomina** [comment]
Nope, it just came as an update yesterday, I guess.
I even remove it with purge and tried to reinstall it and I get the same error.
I checked the script that is mentioned in the error and I found this:
```

cat /var/lib/dpkg/info/ubuntu-make.postinst
#!/bin/sh
set -e

case "$1" in
    configure)
        register-python-argcomplete3 umake > /etc/bash_completion.d/umake
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Automatically added by dhpython:
if which py3compile >/dev/null 2>&1; then
	py3compile -p ubuntu-make -V 3.4-
fi

# End automatically added section


exit 0
```

I tried to run the script from console like:

> sudo register-python-argcomplete3 umake > /etc/bash_completion.d/umake

and I get 

> bash: /etc/bash_completion.d/umake: Permission denied

**Comment by didrocks** [comment]
That's normal that you are getting a permission denied (the redirect isn't run as root, contrary to the script).

You didn't answer on the `which register-python-argcomplete3` command and if you have the package installed though…

**Comment by nenomina** [comment]
> zulu@Darkstar:~$ which register-python-argcomplete3 
> zulu@Darkstar:~$ 
> 

> 
> sudo dpkg -l | grep python3-argcomplete
> ii  python3-argcomplete                         1.0.0-1.pgdg16.04+2

**Comment by didrocks** [comment]
The issue is in the python3-argcomplete package, you have a version which isn't the ubuntu one:
0.8.1-1ubuntu2. Did you add any ppa? `apt-cache policy python3-argcomplete` can help you telling from where it's coming from.

**Comment by nenomina** [comment]
>  apt-cache policy python3-argcomplete
> python3-argcomplete:
>   Installed: 1.0.0-1.pgdg16.04+2
>   Candidate: 1.0.0-1.pgdg16.04+2
>   Version table:
>  *** 1.0.0-1.pgdg16.04+2 500
>         500 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main amd64 Packages
>         500 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main i386 Packages
>         100 /var/lib/dpkg/status
>      0.8.1-1ubuntu2 500
>         500 http://ro.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
>         500 http://ro.archive.ubuntu.com/ubuntu xenial/universe i386 Packages

It's from the PostgreSQL PPA, it seems.

**Comment by didrocks** [comment]
ok, so you have an incompatible argcomplete version. I would recommend reinstalling the one from 16.04 archive, which is supported on the long term… then, postinst would work

**Comment by nenomina** [comment]
OK, I''l test it and if it's OK I'll close the issue, thanks for your time.

**Comment by diwu1989** [comment]
The postgres version of argcomplete seems to come along with a Postgres 9.6 install
Is it possible to make ubuntu-make compatible with the newer argcomplete?

**Comment by didrocks** [comment]
Thanks for digging this up! Indeed.
I won't have the time to work on this right now, but if anyone wants to contribute there, I don't think there is too much work to do. This could be a nice first contribution :)

**Comment by mbsaicharan** [comment]
Hi,
     Even I have the same issue. I have incompatible argcomplete version. How can I reinstall it again from 16.04 archive. Please provide me the exact commands as I'm a beginner working with Ubuntu.

**Comment by didrocks** [comment]
Remove the ppa you added (from the GUI I guess you added it with).
Then:
sudo apt install python3-arcomplete/xenial --force

**Comment by mbsaicharan** [comment]
Thanks it worked  +1:

**Comment by aftabry** [comment]
Hi i have same error ,which you solve it #350 but i can't resolve it .when ever i run any command no my terminal they give me same error ,actually i am newbie on ubuntu 16.04LTS.Please help me out and also check attachement.
thanks

**Comment by didrocks** [comment]
See my answer above, remove the postgres ppa (if you don't know how to do it, a quick google search should help you) and run the command I pasted above ^

**Comment by aftabry** [comment]
"

ok, so you have an incompatible argcomplete version. I would recommend reinstalling the one from 16.04 archive, which is supported on the long term… then, postinst would work
"

how can i do this.....?

**Comment by mbsaicharan** [comment]
Run the below command 
`sudo apt install python3-arcomplete`.
If it doesn't work then download the package from ubuntu archive and install it.
[http://packages.ubuntu.com/xenial/python3-argcomplete](url)

**Comment by blaze33** [comment]
Actually, if you need to keep the postgres ppa, you can put the following file in your apt preferences to de-prioritize `python3-arcomplete` from postgres in the update process:
```
$ cat /etc/apt/preferences.d/pgdg.pref
Package: *
Pin: release o=apt.postgresql.org
Pin-Priority: 500

Package:  python*
Pin: release o=apt.postgresql.org
Pin-Priority: 400
```
Then just reinstall `python3-arcomplete` and the Ubuntu version should be selected (0.8.1 for now instead of the incompatible 1.0.0).

**Comment by domanhtien2011** [comment]
@didrocks  thank you very much. After removing the ppa, and install the package that you have mentioned, it works for me.
