### ISSUE TITLE
superpowers fails to install

### ISSUE THREAD

**Issue by damauk** [ubuntu/ubuntu-make#355]
superpowers fails to install on Ubuntu 16.04. umake version 16.09

user@user:~ umake games superpowers
Choose installation path: /home/user/.local/share/umake/games/superpowers
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/games.py", line 251, in get_metadata_and_check_license
    logger.debug("Found download URL: " + download_url)
UnboundLocalError: local variable 'download_url' referenced before assignment

**Comment by LyzardKing** [comment]
@damauk This should fix your issue, they made separate repos for the app and core versions
Let me know if it works

**Comment by damauk** [comment]
@LyzardKing I replaced the old games.py with the new one and everything works perfectly.
