### ISSUE TITLE
nodejs environment path issue

### ISSUE THREAD

**Issue by Herudin** [ubuntu/ubuntu-make#361]
I have minimal xubuntu installation, just upgraded from xenial to yakkety. After running `umake nodejs` I have following in terminal:
`:~$ npm -v`
`The program 'npm' is currently not installed. You can install it by typing:
sudo apt install npm`
So I cd to ~/.local/share/umake/nodejs/nodejs-lang/bin/ and run `./npm -v` from there and I get:
`/usr/bin/env: ‘node’: No such file or directory`
It seems like environment path issue, because running it like
`:~$ PATH="$PATH:$HOME/.local/share/umake/nodejs/nodejs-lang/bin/" npm -v`
returns correct version.

**Comment by LyzardKing** [comment]
Did you logout/login after the install?

**Comment by Herudin** [comment]
Sure, I did.
I solved this problem by adding the following line to ~/.profile:
`PATH="$PATH:$HOME/.local/share/umake/nodejs/nodejs-lang/bin/"`
Now I can just type `npm -v ` in terminal and it works.
But I suppose this should be added during the installation of nodejs.

**Comment by LyzardKing** [comment]
...Is that not added!? Strange.
Could you tell me what version of umake you have (umake --version)
and show anything in .profile related to umake?

**Comment by LyzardKing** [comment]
It works properly for me, with the following lines in .profile:
# Ubuntu make installation of Nodejs Lang
PATH=/home/galileo/.local/share/umake/nodejs/nodejs-lang/bin:/home/galileo/.npm_modules/bin:$PATH

**Comment by Herudin** [comment]
`:~$ umake --version`
`16.09`
and
~:~$ cat .profile ~
`# Ubuntu make installation of Ubuntu Make binary symlink`
`PATH=/home/herudin/.local/share/umake/bin:$PATH`
`PATH="$PATH:$HOME/.local/share/umake/nodejs/nodejs-lang/bin/"`

The last line in .profile was added manually by me.
Could this be due to the fact that I installed ubuntu from minimal CD and set up minimal xfce environment with tasksel? Could some essential packages or script be missing?

**Comment by LyzardKing** [comment]
I'm not sure.
@didrocks Any ideas?

**Comment by didrocks** [comment]
I don't think package list could be affected. This could be due to your shell tool though. Which one ar you using? bash, zsh, dash, ksh?

**Comment by Herudin** [comment]
@didrocks I use bash, as it is in minimal ubuntu installation.
I'll try to reproduce this behavior in virtual environment (vbox) tomorrow.

**Comment by Herudin** [comment]
Well, I failed to reproduce it under different conditions in vbox. That must have been something with moon phase or maybe stars have been wrong. My laptop is really old, it actually might be affected by that stuff.
Closing as unrelated.

**Comment by matecode** [comment]
I have the the same problem, but my environment is kind of "special". Im usind the Linux Subsystem in Windows10 with Bash on Ubuntu. Everything is working fine except setting the PATH.
It is reproducable.
