### ISSUE TITLE
Error installing/upgrading go

### ISSUE THREAD

**Issue by garyLockyer** [ubuntu/ubuntu-make#362]
Crashes with the following.

Installing Go Lang
ERROR: A decompression to /home/gary/.local/share/umake/go/go-lang failed: unexpected end of data                                                                    #                       |
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 101, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.5/tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.5/tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib/python3.5/tarfile.py", line 243, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
ERROR: unexpected end of data

**Comment by tagplus5** [comment]
Same error ```umake go```

**Comment by didrocks** [comment]
Thanks for reporting this bug!

I did try to implement a band aid. It seems that the latest go tarball is slightly corrupted and tarfile python module can't read it correctly.

Note that I fallback reluctanctly to executing tar directly in that case. The decompression can take a little bit longer than usual in those case.

Please, tell me if that fixes it for you (it did certainly for me), via:
```
$ git clone https://github.com/ubuntu/ubuntu-make
$ bin/umake go
```
This should run the umake version directly from master!
Thanks

**Comment by nevsnode** [comment]
I can confirm that this fallback works. Thanks for the quick response! :+1:

**Comment by didrocks** [comment]
Happy that it worked for you! Thanks for confirming :)

**Comment by tagplus5** [comment]
its work

**Comment by garyLockyer** [comment]
The fix resoles the issue.
