### ISSUE TITLE
use of the dockerfile

### ISSUE THREAD

**Issue by boistordu** [ubuntu/ubuntu-make#363]
what's the use of the dockerfile here? you didn't seem to have configured any wdm in this docker... is it a container for a devbox or something?

**Comment by didrocks** [comment]
The docker file is used for medium testing, mocking a complete OS and network. We have pep8, small, medium and large tests.
I did blog more about it here if you are interested: http://blog.didrocks.fr/post/Ubuntu-Developer-Tools-Center%3A-how-do-we-run-tests.

Hope that answer your question! :)
