### ISSUE TITLE
problem with shortcut generation

### ISSUE THREAD

**Issue by boistordu** [ubuntu/ubuntu-make#365]
/home/boistordu/.local/share/umake/ide/pycharm-professional/bin/pycharm.sh that's the shortcut which is created. 
but I've ask to install it in /home/boistordu/psycharmpro

**Comment by didrocks** [comment]
waow, just confirmed the bug! I'll only be able to get to it by the end of next week though (+ look at the corresponding tests). Thanks for reporting it.

**Comment by didrocks** [comment]
Found it! The regression was in commit 524c921f. self.exec_path has been moved way upper that it should be, and an issue in the test asset was hiding it. Both are fixed in master now :) Thanks for the report!
