### ISSUE TITLE
ide idea problem

### ISSUE THREAD

**Issue by boistordu** [ubuntu/ubuntu-make#367]
Choose installation path: /home/boistordu/.local/share/umake/ide/idea
Downloading and installing requirements
ERROR: installArchives() failed                                               |
Subprocess output: 
Extracting templates from packages: 78%
Extracting templates from packages: 100%
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
Error in function: 
SystemError: E:Sub-process /usr/bin/dpkg returned an error code (2)

100% |########################################################################|
ERROR: Package requirements can't be met: installArchives() failed
Subprocess output: 
Extracting templates from packages: 78%
Extracting templates from packages: 100%
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
Error in function: 
SystemError: E:Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by boistordu** [comment]
same with idea-ultimate

**Comment by didrocks** [comment]
Thanks for this report! However, the issue here isn't an Ubuntu Make issue. It seems your apt database in a broken state (I'm sure apt install <anypackage> would produce the same result). This is because you don't have ldconfig and start-stop-daemon on your system (you probably removed those packages).

Ensure that your apt database is fixed, meaning `apt upgrade` should run without any error, and then, you can use ubuntu-make to install your frameworks.

I'm closing this report then, but do not hesitate to open any other issue impacting ubuntu make!

**Comment by boistordu** [comment]
well mon cher et tendre didrocks (puisque tu es français :p ),
```
sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
Donc on est bien d'accord que c'est peut-être une installation minimale d'uubntu mais néanmoins elle fonctionne correctement comme tu peux le voir. 
```
boistordu@x2go:~/ubuntu-make$ sudo ldconfig
boistordu@x2go:~/ubuntu-make$ 
```
tu vois donc bien que ldconfig existe et retourne quelque chose.

For english version: So as yo ucan see in the example above, maybe it's a minimal ubuntu installation but it seems to work nevertheless (I mean ldconfig and what you call start-stop-daemon which is systemd) So maybe it just can't find it because it's not looking at the good place...?

**Comment by boistordu** [comment]
So should I reopen a ticket or something?

**Comment by boistordu** [comment]
You know I could even grant you an access by X2GO if you want to test it yourself... It's really not that big of a deal

**Comment by didrocks** [comment]
we can continue on this one, this is a specific user issue for sure and not ubuntu make one (IRC would be best?)
```
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
Error in function:
SystemError: E:Sub-process /usr/bin/dpkg returned an error code (2)
```

-> regarde dans le PATH de l'utliisateur root (et pas sudo), je pense qu'il y a une config qui fait qu'apt n'arrive pas à trouver ldconfig, et donc que /sbin n'est pas dans ton $PATH de root.

**Comment by boistordu** [comment]
But I thought that ubuntu-make wasn't supposed to use root ? and why not use sudo ? I mean in your code?

anyway if I do printenv in the root user I have : 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by didrocks** [comment]
Ubuntu Make itself isn't. The hooks that are used by your apt database are used as root.

Your system has obviously something unusual. We can look at this together on IRC.
Another way would be, try install your ide with `umake -v`, note the list of packages it's trying to install. Then, try install them yourself with`apt install <those_package>`. You should get the same errors and will be easier to debug outside of ubuntu make.

**Comment by boistordu** [comment]
discord, jabber, IRC, telegram, mail what ever you like best just send me the info and I will connect to it. 

Installing netbeans at the moment of we speak and it's going according to normal install. I didn't know that we could install idea by apt, I will test it in a moment.

**Comment by boistordu** [comment]
```
de /usr/bin/jstatd (jstatd) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/bin/native2ascii to provide /usr/bin/native2ascii (native2ascii) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/bin/schemagen to provide /usr/bin/schemagen (schemagen) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/bin/wsgen to provide /usr/bin/wsgen (wsgen) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/bin/wsimport to provide /usr/bin/wsimport (wsimport) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode
Setting up netbeans (7.0.1+dfsg1-5ubuntu2) ...
Setting up icedtea-6-jre-cacao:amd64 (6b40-1.13.12-0ubuntu0.14.04.2) ...
Setting up icedtea-6-jre-jamvm:amd64 (6b40-1.13.12-0ubuntu0.14.04.2) ...
Setting up icedtea-netx:amd64 (1.5.3-0ubuntu0.14.04.1) ...
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/javaws to provide /usr/bin/javaws (javaws) in auto mode
update-alternatives: using /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/itweb-settings to provide /usr/bin/itweb-settings (itweb-settings) in auto mode
update-alternatives: warning: not replacing /usr/share/man/man1/itweb-settings.1.gz with a link
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/javaws to provide /usr/bin/javaws (javaws) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/itweb-settings to provide /usr/bin/itweb-settings (itweb-settings) in auto mode
update-alternatives: warning: not replacing /usr/share/man/man1/itweb-settings.1.gz with a link

```
you see ldconfig works perfectly.

**Comment by didrocks** [comment]
IRC: freenode, I'm didrocks there :)
I didn't ask to install netbeans, but the dependencies that ubuntu make install (hence `umake -v`), maybe the set of deps are slightely different and something else triggers the issue.

**Comment by boistordu** [comment]
I've add you to my list and I'm speaking to you right now, don't know if you received my message
