### ISSUE TITLE
Cannot install go 1.7.3, "unexpected end of data"

### ISSUE THREAD

**Issue by Samureus** [ubuntu/ubuntu-make#368]
```
$ umake --version
16.09
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

Gist with verbose output located at https://gist.github.com/Samureus/1c070cd818a8667bef4f72fb4d8f4fc3

**Comment by LyzardKing** [comment]
This should be fixed in master, you can try it if you want.
`$ git clone https://github.com/ubuntu/ubuntu-make`
`$ bin/umake go`

see #362

**Comment by Samureus** [comment]
Thanks and sorry, I hadn't checked the closed issues before posting, my bad.
