### ISSUE TITLE
Unable to install go 

### ISSUE THREAD

**Issue by tebruno99** [ubuntu/ubuntu-make#378]
I have run into an issue now for a while on several different ubuntu installs that makes installing go-lang not possible.  (Version: 16.09 on Ubuntu 16.10)

`tbruno@Rio:~$ umake go
Choose installation path: /home/tbruno/.local/share/umake/go/go-lang
Downloading and installing requirements                                                                                                                                         |
100% |##########################################################################################################################################################################|
Installing Go Lang
ERROR: A decompression to /home/tbruno/.local/share/umake/go/go-lang failed: unexpected end of data                                                                             |
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 101, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.5/tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.5/tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib/python3.5/tarfile.py", line 243, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
ERROR: unexpected end of data
|###############################################################################################################################################################################|
tbruno@Rio:~$`

**Comment by didrocks** [comment]
Hey @tebruno99. Correct! This is something due to the new golang tarball. See #374: I have a workaround in master that you can use.
I'll do a release with this fix by the end of the week.
