### ISSUE TITLE
Firefox Developer Edition can't be installed

### ISSUE THREAD

**Issue by tobiasboyd** [ubuntu/ubuntu-make#380]
```$ umake web firefox-dev
Choose installation path : /home/toby/.local/share/umake/web/firefox-dev
ERROR: Download page changed its syntax or is not parsable```

This is on 16.04.

**Comment by LyzardKing** [comment]
Do you have the latest version from the ppa?
If not you need to do:

```
sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
sudo apt-get update
sudo apt-get upgrade
```

**Comment by LyzardKing** [comment]
It's working in the current version. Reopen if there are other issues

**Comment by Babu-Ameex** [comment]
I am updated ubundu version
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

But still i am getting error while install "Firefox Developer Edition"

umake web firefox-dev
Choose installation path: /home/ameex/.local/share/umake/web/firefox-dev
ERROR: Download page changed its syntax or is not parsable
