### ISSUE TITLE
Aptana Studio

### ISSUE THREAD

**Issue by michaellee8** [ubuntu/ubuntu-make#381]
Would ubuntu-make support installation of more IDEs like bracket and Apatana Studio? These are some best of IDEs that can be installed on linux (ubuntu) as well.

**Comment by LyzardKing** [comment]
Aptana studio should be easy, since it has tarfiles in the github repo (You can replicate the installer for atom).
Brackets only releases debs, so that's harder to implement.

**Comment by LyzardKing** [comment]
Aptana hasn't had a release since Nov 14, 2014.
I don't think it can reasonably be added to umake.
I'll close for now, and we can revisit this if there's an active branch somewhere.
