### ISSUE TITLE
Support Rider IDE

### ISSUE THREAD

**Issue by aleks-sidorenko** [ubuntu/ubuntu-make#383]
Rider is a full featured, cross platform .NET IDE based on ReSharper and IntelliJ.
It is now in public preview, but soon will be released
https://blog.jetbrains.com/dotnet/2016/11/21/jetbrains-rider-public-preview/.
Let's make it available via umake!

**Comment by LyzardKing** [comment]
This should be easy enough.
You can replicate the generic jetbrains installer and test.

**Comment by aleks-sidorenko** [comment]
It seems so, but unfortunately Rider doesn't have the product code for now. At least I am unable to find it in https://www.jetbrains.com/updates/updates.xml

**Comment by LyzardKing** [comment]
The code is RD.
https://data.services.jetbrains.com/products/releases?code=RD&type=eap

**Comment by LyzardKing** [comment]
Fixed in #468
