### ISSUE TITLE
Add Crystal

### ISSUE THREAD

**Issue by GabrielTK** [Ubuntu/ubuntu-make#386]
Good Evening,
Can someone add [Crystal](https://crystal-lang.org/) or say how to do it??
Thank you,
Gabriel

**Comment by LyzardKing** [comment]
Hi @GabrielTK !
You can look at kotlin.py. That's another language pulled from github.
The only thing different is you'd have to add a check for the different architectures, but for that you can look at one of the ides.
Let me know if you can get it to work.
The we can look at the tests.
