### ISSUE TITLE
go fails to install

### ISSUE THREAD

**Issue by thibran** [ubuntu/ubuntu-make#391]
OS: Ubuntu 16.04.1 x86_64
ubuntu-make: 16.02.1

Executing `umake go` failed with:

`ERROR: A decompression to /home/foo/.local/share/umake/go/go-lang failed: unexpected end of data`

**Comment by didrocks** [comment]
Indeed, google website changed their API. We could only push new features and fixes to our ppa, please add it (instructions are in https://wiki.ubuntu.com/ubuntu-make) and you will get a working go install.

**Comment by LyzardKing** [comment]
Fixed in the latest releases
