### ISSUE TITLE
umake 16.11 version cannot find arguments  "android"

### ISSUE THREAD

**Issue by aboobakkar** [ubuntu/ubuntu-make#394]
Hi,
I Have read the article [umake](https://wiki.ubuntu.com/ubuntu-make) . 
![screenshot from 2016-12-20 15-22-08](https://cloud.githubusercontent.com/assets/6416738/21345941/39cd1b0c-c6c8-11e6-9751-b7a3d41cf989.png)
And type umake result get this above image.Not listed Android .

**Comment by sschuberth** [comment]
Your version of `umake` is probably outdated. What does `umake --version` show?

**Comment by LyzardKing** [comment]
Closing since related to an older version of umake.
Please reopen if the issue persists.
