### ISSUE TITLE
Cannot install rust 1.14

### ISSUE THREAD

**Issue by Samureus** [ubuntu/ubuntu-make#397]
It seems like they changed the download process again, now they are using rustup:
```
$ umake --version
16.11.1
$ umake -vv rust
#(cutting off noise)
Choose installation path: $HOME/.local/share/umake/rust/rust-lang
DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading DownloadItem(url='https://www.rust-lang.org/en-US/downloads.html', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.rust-lang.org
DEBUG: "GET /en-US/downloads.html HTTP/1.1" 200 91
DEBUG: Deliver download update: {'https://www.rust-lang.org/en-US/downloads.html': {'size': 91, 'current': 0}} of 91
DEBUG: Deliver download update: {'https://www.rust-lang.org/en-US/downloads.html': {'size': 91, 'current': 91}} of 91
INFO: https://www.rust-lang.org/en-US/downloads.html download finished
INFO: All pending downloads for [DownloadItem(url='https://www.rust-lang.org/en-US/downloads.html', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
DEBUG: Fetched download page, parsing.
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/rust.py", line 98, in get_metadata_and_check_license
    link = (soup.find('div', class_="install")
AttributeError: 'NoneType' object has no attribute 'find'
```

See https://www.rust-lang.org/en-US/install.html

**Comment by LyzardKing** [comment]
The page changed.
Also they switched from shasum to a gpg signature file.
I'm not sure nor have the time now to look at the signature, but since the file is  delivered via https I can change it to not require a signature.
If someone wants to properly fix this the swift downloader should help in this regard.

**Comment by LyzardKing** [comment]
@Samureus If you want to test it and download rust for the moment you can clone my repo, switch to the rust branch and run bin/umake rust from there.

**Comment by Tinche** [comment]
We should probably change our Rust functionality to just install rustup. Rustup is likely to be better for Rust management in basically every way, and Rust developers will be familiar with it from other platforms.

**Comment by Samureus** [comment]
@LyzardKing not a problem, I already got rustup running, though from playing with https://github.com/yyuu/pyenv myself, I agree with @Tinche that it might be easier to just check for rustup, if not found install it, if found then `rustup self update && rustup update`

**Comment by valmar** [comment]
I still have this as for today for rust 1.21 (Ubuntu 17.10 beta 2)

**Comment by LyzardKing** [comment]
@valmar What version of umake do you have?
You might need a newer version, since I can't replicate the issue.

**Comment by valmar** [comment]
Thanks for your quick reply.  Do you mean the version of umake?

It appears to be 16.11.1, the version in the Artful repositories (I am
testing 17.10 beta 2)

I got the error by trying:

$ umake rust
Choose installation path: /home/vmariani/.local/share/umake/rust/rust-lang
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/rust.py", line 98,
in get_metadata_and_check_license
    link = (soup.find('div', class_="install")
AttributeError: 'NoneType' object has no attribute 'find'
vmariani@cfeld-pcx19696-tb:~$

**Comment by LyzardKing** [comment]
The latest version is not the one in the main repo.
It's now distributed as a snap, as you can see in the readme.
There's an issue with the snap in artful, that should be fixed soon.
For now you could clone the main repo and run from master

**Comment by valmar** [comment]
Oh I am really sorry, my bad for not RTFM

However, I see that the ubuntu-make snap is a "classic" unsandboxed snap.
Some people (or at least I know 2-3 of them :-) , in addition to me) do not
feel comfortable installing unconfined snaps, so I think it would be good
to also have the latest version in the repository

Thank you and sorry again for wasting your time!

**Comment by LyzardKing** [comment]
Can I ask why you're not comfortable?
A classic snap has no less security than a traditional install

**Comment by valmar** [comment]
Sure. If I understand correctly, normal snaps have no access to the whole
system, while classic ones have.

Here:

**Comment by LyzardKing** [comment]
Yes, but you're saying that you prefer a classic Deb (from the repos).
That's not a snap.

**Comment by valmar** [comment]
Sorry, I posted an incomplete message by mistake

Here:

https://docs.snapcraft.io/reference/confinement

It says:

"A snap in classic confinement behaves as a traditionally packaged
application, with full access to the system. "

I understand that classic snaps are now manually reviewed, but without the
strict confinement, I don't feed comfortable installing snaps which could
contain libraries with vulnerabilities



On Tue, Oct 17, 2017 at 12:51 PM, Valerio Mariani <valerio.mariani@gmail.com
> wrote:

> Sure. If I understand correctly, normal snaps have no access to the whole
> system, while classic ones have.
>
> Here:
>
>
> On Tue, Oct 17, 2017 at 12:47 PM, LyzardKing <notifications@github.com>
> wrote:
>
>> Can I ask why you're not comfortable?
>> A classic snap has no less security than a traditional install
>>

**Comment by valmar** [comment]
Well, with classic debs, I trust that the packager (in Debian and Ubuntu)
has determined that the code is safe, and I trust the long and hard
procedure dictated by the packaging policy of Debian and Ubuntu. I trust
that the code has been tested in Debian and Ubuntu before I get it. Anyone
can instead create a snap, even I. So I don't like giving snaps full access
to the system

But with the strict confinement, I absolutely love snaps!

On Tue, Oct 17, 2017 at 12:54 PM, Valerio Mariani <valerio.mariani@gmail.com
> wrote:

> Sorry, I posted an incomplete message by mistake
>
> Here:
>
> https://docs.snapcraft.io/reference/confinement
>
> It says:
>
> "A snap in classic confinement behaves as a traditionally packaged
> application, with full access to the system. "
>
> I understand that classic snaps are now manually reviewed, but without the
> strict confinement, I don't feed comfortable installing snaps which could
> contain libraries with vulnerabilities
>
>
>
> On Tue, Oct 17, 2017 at 12:51 PM, Valerio Mariani <

**Comment by valmar** [comment]
Yes, I did not mean to say that I don't trust you guys personally!

It was more a consideration that applies to all classic snaps. I use snaps
but as a rule I try not to install classic ones. Obviously I want to use
the latest and greatest ubuntu-make, so I will make an exception for
ubuntu-make :-) ;)

Seriously, thank you for the quick answer even if I was in the wrong, and
for caring about my opinion of calssic snaps. Your work is really
appreciated

**Comment by LyzardKing** [comment]
No problem!
It's good that we can have discussions like this one.
If you want to know more about how snaps (classic or not) are uploaded to the store,
you can have a look at the snapcraft forum.

**Comment by valmar** [comment]
Thank you. By the way, as you said the current snap segfaults, but
installing rust using the master branch of this repo works perfectly

**Comment by LyzardKing** [comment]
Good to know!
Hopefully the snap issue can get fixed soon
