### ISSUE TITLE
Add support to Gogland (Go IDE)

### ISSUE THREAD

**Issue by dggonzalez1971** [ubuntu/ubuntu-make#398]
When available it would be interesting to add Gogland to the list of IDE'S. It is not yet officially available but an early version can be tested
https://blog.jetbrains.com/go/2016/12/15/announcing-gogland-brand-new-go-ide-from-jetbrains/?mkt_tok=eyJpIjoiWVRJek1qWmxOekUxTXpReCIsInQiOiJWanJ3STB1eXIxSUU5aXJ2NkpkNHVnZXo0NVRwZ1EwSlRtdHZVNWpzZ25pQUJPcnRcL2ROU2RZSXY0USs0K2FVUG9rbDJqcU4wWGZvdHI3R3gwejlSY1lHWlRzRnhvQXRPRU1EYjRTNlNrWHpSNE9YU01hN3R4ZEUreXJaR2VTakEifQ%3D%3D
Thanks

**Comment by LyzardKing** [comment]
This will be done once it's released in eap form (like for the recently released rider).
For now it needs an email to access the eap test version.
I'll close for now and we'll revisit at the right time

**Comment by Komzpa** [comment]
It's available:
https://www.jetbrains.com/go/download/#section=linux

**Comment by LyzardKing** [comment]
@Komzpa I know it's available in eap.
There's an open pull request. 
Unfortunately I can't get the medium(mock) tests to work, and I don't have too much time atm.
Help would be appreciated ;)
