### ISSUE TITLE
ModemManager conflicts with many embedded development tools

### ISSUE THREAD

**Issue by zyga** [ubuntu/ubuntu-make#4]
Many embedded (MSP430, AVR, PIC, ARM, etc) development tools use serial ports for communication or programming. The installed-by-default modem manager package performes active probing on *all* serial ports thereby often breaking time-sensitive bootup sequences with random AT commands.

I believe that using mobile modems should not be at odds with being an embedded engineering enthusiast or professional. I would like to suggest that we start working on SerialManager which would be in control of all the serial ports and could mediate with ModemManager (but also GPS tools, modem control tools, embedded programmers and other software that needs serial access) to prevent conflicts.

In the long term, I would like the out-of-the-box experience to be good for both casual users that wish to use their 3G modem dongle as well as developers that control a specialized test equipment over a serial line.

The shared component could provide a form of identity management to where traditionally there is none. It could also give advanced users a central point for management (permissions, meta-data, etc). Lastly it would be a layer that other, well-behaved software can talk to (all the programming tools, custom flashers, etc).

As a part of this effort I would like to work on Serial Manager and on patches to Modem Manager. I would like to invite anyone interested to join me to make Ubuntu, and other modern free software desktops, the best development environment anyone can ask for.

**Comment by didrocks** [comment]
After discussing, this should be done at the distro level rather than Ubuntu Make. Pinged the relevant maintainers. Closing for now.
