### ISSUE TITLE
ERROR: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by THUFIR** [ubuntu/ubuntu-make#404]
Literally just installed the OS:
```

thufir@doge:~$ 
thufir@doge:~$ umake ide eclipse
Choose installation path: /home/thufir/.local/share/umake/ide/eclipse
ERROR: Download page changed its syntax or is not parsable
thufir@doge:~$ 
thufir@doge:~$ umake ide netbeans
Choose installation path: /home/thufir/.local/share/umake/ide/netbeans
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 686, in parse_download_page_callback
    if not url_string:
UnboundLocalError: local variable 'url_string' referenced before assignment
thufir@doge:~$ 
thufir@doge:~$ umake --version
16.05
thufir@doge:~$ 
thufir@doge:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
thufir@doge:~$ 

```

**Comment by LyzardKing** [comment]
You need the latest version, 16.11.1.
You can add the ppa, so it'll always be up to date:

> sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
> sudo apt update
> sudo apt install ubuntu-make

**Comment by THUFIR** [comment]
ok, not a bug; thanks.  Trying to remove on Ubuntu:

`thufir@doge:~$ 
thufir@doge:~$ sudo apt purge ubuntu-developer-tools-center
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-argcomplete python3-gnupg python3-progressbar ubuntu-make
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  ubuntu-developer-tools-center*
0 upgraded, 0 newly installed, 1 to remove and 202 not upgraded.
After this operation, 22.5 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 170802 files and directories currently installed.)
Removing ubuntu-developer-tools-center (16.05) ...
thufir@doge:~$ 
thufir@doge:~$ 
thufir@doge:~$ 
thufir@doge:~$ umake ide eclipse
Choose installation path: /home/thufir/.local/share/umake/ide/eclipse
ERROR: Download page changed its syntax or is not parsable
thufir@doge:~$ 
`

If you know how to remove umake, that'd be helpful.  Thanks.
