### ISSUE TITLE
Not able to install softwares from center

### ISSUE THREAD

**Issue by jsroyal** [ubuntu/ubuntu-make#406]
After installation 16.04 LTS UBUNTU, I got a lot of error to use it.
Major error.
Software center does not work.
Here some screen-shots.
![screenshot from 2017-02-03 09-53-58](https://cloud.githubusercontent.com/assets/10773353/22579582/3cec210a-e9f7-11e6-82b4-5bbbbd9e71c7.png)
![screenshot from 2017-02-03 09-53-41](https://cloud.githubusercontent.com/assets/10773353/22579583/3cf51cb0-e9f7-11e6-9b71-1056afa12716.png)
![screenshot from 2017-02-03 09-53-33](https://cloud.githubusercontent.com/assets/10773353/22579584/3cf789e6-e9f7-11e6-8801-7ebfd4a25a4e.png)
![screenshot from 2017-02-03 09-53-27](https://cloud.githubusercontent.com/assets/10773353/22579585/3d02c40a-e9f7-11e6-9a89-f5a066d60893.png)
![screenshot from 2017-02-03 09-39-50](https://cloud.githubusercontent.com/assets/10773353/22579586/3d08488a-e9f7-11e6-88fe-fa2c3560131a.png)

**Comment by didrocks** [comment]
Hello @jsroyal. I'm sorroy to tell you that it's not the project you are looking for. Ubuntu-make is a command line tool project, not integrated with Ubuntu Software.
You need to open a bug against https://launchpad.net/ubuntu/+source/gnome-software with your content (use ubuntu-bug gnome-software to collect more infos).

Closing this bug then.

**Comment by jsroyal** [comment]
Thanks @didrocks I was looking the perfect place to report bug but sorry for that I misunderstood this repo.
But any way you give right direction to go about it.
thanks again.
