### ISSUE TITLE
jython and pip

### ISSUE THREAD

**Issue by THUFIR** [ubuntu/ubuntu-make#407]
It would be nice to be able to use jython and pip at the latest version.  Not sure that this is within or outside of what umake does.  See:

http://askubuntu.com/questions/880758/how-to-add-jython-jars-for-a-user-to-the-path-enviroment-variable
```

thufir@doge:~$ 
thufir@doge:~$ echo $PATH
/home/thufir/.local/share/umake/bin:/home/thufir/bin:/home/thufir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
thufir@doge:~$ 
thufir@doge:~$ export PATH="/home/thufir/jython/bin/:$PATH"
thufir@doge:~$ 
thufir@doge:~$ echo $PATH
/home/thufir/jython/bin/:/home/thufir/.local/share/umake/bin:/home/thufir/bin:/home/thufir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
thufir@doge:~$ 
thufir@doge:~$ jython --version
Jython 2.7.0
thufir@doge:~$ 
thufir@doge:~$ which pip
/home/thufir/jython/bin//pip
thufir@doge:~$ 
thufir@doge:~$ which jython
/home/thufir/jython/bin//jython
thufir@doge:~$ 
```

would've been easier to use umake, if it were an option.

**Comment by Davileal** [comment]
yes

**Comment by LyzardKing** [comment]
@THUFIR @didrocks 
Not sure about pip, but for jython we can download the standalone jar, add a version of openjdk-jre as a dependency, and include a launcher in umake/bin that will launch that jar with java -jar <standalone-version.jar>
