### ISSUE TITLE
Suggest: Datagrip and CLion.

### ISSUE THREAD

**Issue by srseven** [ubuntu/ubuntu-make#414]
Ubuntu Make has all Jetbrains IDE's except DataGrip which is a popular IDE for databases and CLion which is an IDE for C/C++. Can i expect they will be included in the near future?

**Comment by LyzardKing** [comment]
What version of umake do you have? The latest has both.
if you run umake --version you should get 16.11.1
If you don't have the latest version you should add the ppa

**Comment by srseven** [comment]
Thanks! I would you edit your [wiki](https://wiki.ubuntu.com/ubuntu-make) page so people get to know these are included.
