### ISSUE TITLE
Cannot install unity3d in umake --version 16.11.1

### ISSUE THREAD

**Issue by takahash** [ubuntu/ubuntu-make#415]
I want to install unity3d in ubuntu PC by umake. But I couldn't do it. This is Error Message.
```
$ umake games unity3d
Choose installation path: /home/takaken/.local/share/umake/games/unity3d
ERROR: Download page changed its syntax or is not parsable (url missing)
```

This is my umake version.
```
$ umake --version
16.11.1
```

**Comment by LyzardKing** [comment]
@takahash I can't really test this, but it should work from the pull request #416 
Let me know if you can try it out.

**Comment by takahash** [comment]
@LyzardKing Thank you for your information !!
I'll try the pulll request #416

**Comment by LyzardKing** [comment]
Great! If it works we can merge it then
