### ISSUE TITLE
Installation of Android Studio fails

### ISSUE THREAD

**Issue by kneth** [ubuntu/ubuntu-make#418]
Android Studio 2.3 has been released. And `umake android --accept-license` fails with invalid checksum (downloading release 162.3764568 of Android Studio) on Ubuntu 16.10.

**Comment by LyzardKing** [comment]
@kneth would you mind testing the version in the pr?

**Comment by kneth** [comment]
@LyzardKing I have applied the  patch to `android.py` (manually edited the file), and it worked fine. Thanks for the quick fix!

**Comment by LyzardKing** [comment]
Great! Thank you. I'll merge now that the tests work properly.

**Comment by SpacePotatoBear** [comment]
hi, I'm on ubuntu 17.04 and i'm getting this issue.

**Comment by SpacePotatoBear** [comment]
edit, installing ubuntu-make from an external repo fixed this. Disregard.
