### ISSUE TITLE
umake 16.11.1 can't install android 2.3.0.8 

### ISSUE THREAD

**Issue by tanakarock** [ubuntu/ubuntu-make#420]
Hi,
The android install is broken
ERROR: https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip couldn't finish download: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip doesn't match. Corrupted download? Aborting.
100% |#########################################################################|
ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip doesn't match. Corrupted download? Aborting.

because new version android studio using SHA-256 Checksums:
214cee47ef7a628c712ae618f5aab6c2a56a72aa479a50937d4cad5a0abf8435 

umake still use SHA1 checksums

umake android -v
INFO: Installation ['libncurses5:i386', 'libstdc++6:i386', 'zlib1g:i386', 'openjdk-8-jdk'] pending
INFO: Start downloading DownloadItem(url='https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip', checksum=Checksum(checksum_type=<ChecksumType.sha1: 'sha1'>, checksum_value='214cee47ef7a628c712ae618f5aab6c2a56a72aa479a50937d4cad5a0abf8435'), headers=None, ignore_encoding=False, cookies=None) to a temp file
Downloading and installing requirements
INFO: Starting new HTTPS connection (1): dl.google.com
ERROR: https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip couldn't finish download: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip doesn't match. Corrupted download? Aborting.
INFO: All pending downloads for [DownloadItem(url='https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip', checksum=Checksum(checksum_type=<ChecksumType.sha1: 'sha1'>, checksum_value='214cee47ef7a628c712ae618f5aab6c2a56a72aa479a50937d4cad5a0abf8435'), headers=None, ignore_encoding=False, cookies=None)] done
100% |#########################################################################|
ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip doesn't match. Corrupted download? Aborting.

**Comment by LyzardKing** [comment]
This is fixed in master since #419.
There will be a release soon enough. In the meantime you can clone the repo
