### ISSUE TITLE
Can´t install android checksum error

### ISSUE THREAD

**Issue by Loco123** [ubuntu/ubuntu-make#422]
Hello I have ubuntu 16.04 and install umake (version 16.11.1), when tried to install android studio an error abort the installation; it is look that the check sum is wrong.

ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/2.3.0.8/android-studio-ide-162.3764568-linux.zip doesn't match. Corrupted download? Aborting.

can you help me to install android?

SALUDOS!!!!!!

**Comment by LyzardKing** [comment]
This is fixed in master since #419.
There will be a release soon enough. In the meantime you can clone the repo
