### ISSUE TITLE
Consider using Travis CI cron jobs

### ISSUE THREAD

**Issue by sschuberth** [ubuntu/ubuntu-make#425]
Due to the nature of this project stuff might break without any changes to the project itself, but caused by upstream (e.g. if the location or content of a downloaded file changes). To capture such issues, looking into using [Travis CI cron jobs](https://docs.travis-ci.com/user/cron-jobs/) probably is a good idea.

**Comment by didrocks** [comment]
The issue is that we can't run medium and large tests in Travis CI. The first is requiring the use of a docker container (and they didn't enabled nested container as the tests are already running in a container). The second involves having a full graphical interface.

Any CI supporting this (we were using the Ubuntu CI and jenkins for this and running this regularly, but due to time constraints, I can't maintain it anymore) would be great!

**Comment by sschuberth** [comment]
Interesting. Looks like CircleCI 2.0, which is currently in beta, would allow this: https://circleci.com/docs/2.0/building-docker-images/

If you're still willing to host your own CI, https://concourse.ci/ might be an option.

**Comment by didrocks** [comment]
Would take any contribution bringing up one of this CI (preferably hosted) up to speed. It's "simply" a matter of having:
`./runtests` running (once you get all the deps and such working ofc ;))

**Comment by sschuberth** [comment]
I've requested beta access for CircleCI. Let's see how this goes.

**Comment by LyzardKing** [comment]
There seem to be also other services that offer hosted docker support.
It's not something I know much about, and I don't have much time atm..
But I was looking at these. They're all free with docker support for open source projects.
@sschuberth you might know more than me ;)
https://codeship.com/
https://buddy.works/
https://semaphoreci.com

**Comment by sschuberth** [comment]
Thanks for the list! Actually, I haven't used Docker-based CI myself yet.

**Comment by LyzardKing** [comment]
@sschuberth I've only ever used travis..and probably not in any sensible way...
The ideal thing would be to run the large test (as @didrocks said that would need a graphic interface)
The medium test would at least alert if our mock fails...
that would be reasonable enough, I'm not sure if anybody offers a full graphic interface for tests..
But yes, I really know nothing proper about CI, it's mostly curiosity.
Let me know if you find out more
