### ISSUE TITLE
Consider accelerating Ubuntu kernel with GPGPU/HSA

### ISSUE THREAD

**Issue by tiagmoraismorgado** [ubuntu/ubuntu-make#431]
**Greetings**

It would be awesome, if we could, within a sense, **accelerate Ubuntu kernel** with either **GPGPU/HSA**, using a **framework/API** such as **OpenCL**, by **Khronos group,** or even **muenster university SkelCl.**

**Looking forward
xx
T.**

**Comment by LyzardKing** [comment]
I don't think this has anything to do with ubuntu-make ;)
