### ISSUE TITLE
firefox-dev download fails

### ISSUE THREAD

**Issue by GeneralFailer** [ubuntu/ubuntu-make#433]
Error log:

ERROR: https://www.mozilla.org/en-US/firefox/developer/all couldn't finish download: HTTPSConnectionPool(host='www.mozilla.org', port=443): Max retries exceeded with url: /en-US/firefox/developer/all (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fae30055588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
ERROR: An error occurred while downloading https://www.mozilla.org/en-US/firefox/developer/all: HTTPSConnectionPool(host='www.mozilla.org', port=443): Max retries exceeded with url: /en-US/firefox/developer/all (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fae30055588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
ERROR: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ubuntu/ubuntu-make/releases (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fae3006fe48>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Version 17.03, Ubuntu 17.04
EDIT: Just in case, the OS is running in VirtualBox.

**Comment by LyzardKing** [comment]
I tried running a clean vm in virtualbox and it worked.
Could there be something not configured properly on your end?

**Comment by GeneralFailer** [comment]
Never mind, seems to be some unrelated network problem. Thanks for looking into it.
