### ISSUE TITLE
UMake breaks while installing Rust

### ISSUE THREAD

**Issue by GreenJoey** [ubuntu/ubuntu-make#439]
I just installed Ubuntu make in Ubuntu 16.04 to install the Rust tool-chain but the umake tool breaks while installing Rust. I works fine with other languages and tool-chains but it breaks in Rust.
Here is the screenshot
![umake bug on rust](https://cloud.githubusercontent.com/assets/19374280/24543528/9cbd011a-161d-11e7-9f47-19f198927e5c.png)

**Comment by LyzardKing** [comment]
@GreenJoey Could you include the version of umake?

**Comment by GreenJoey** [comment]
Okay I will give you version. As of yesterday, I upgraded to Ubuntu 16.10 and there has been no update to ubunut-make if I remember correctly

**Comment by LyzardKing** [comment]
As I said in the previous comment, you need to add the ppa repository, as specified in the readme.
https://github.com/ubuntu/ubuntu-make/blob/master/README.md#installing

**Comment by LyzardKing** [comment]
Closing as solved. Needed the PPA.
