### ISSUE TITLE
I am trying to understand the rationale for needing admin permissions.

### ISSUE THREAD

**Issue by hungrymonkey** [ubuntu/ubuntu-make#451]
>umake android
>[sudo] password for notadmin: 
>notadmin is not in the sudoers file.  This incident will be reported.

When I try to run umake as a normal user, the utility complains that I am not in the sudoers file.

I am trying to understand the rationale for needing admin permissions when the program install utilities in the user's home directory.

**Comment by LyzardKing** [comment]
Hi. It's simple really..
Umake installs the needed dependencies for you.
If they are not already in the system it needs admin permissions to install
them via apt.

**Comment by hungrymonkey** [comment]
Basically, this tool is useless for people on non admin accounts then.

Ok, I guess I will install android studio another way.

**Comment by LyzardKing** [comment]
You would need something with all the dependencies contained, like snaps/appimages/flatpak or something similar I guess.
There's no easy way to manage dependencies other than bundling them or relying in the system package manager

**Comment by hungrymonkey** [comment]
I just need it installed and accessible to a non admin account. I will just use a ppa in the meantime.

**Comment by LyzardKing** [comment]
That will have the same issue that umake has, it needs to install via apt

**Comment by hungrymonkey** [comment]
I have access to an account that can use apt. I am just using a different account without permission developing. I tried adding the path to my non admin dir. It complain about no permissions. Oh well.

 I just cant wait for flatpak/snap for solving binary distribution.

**Comment by LyzardKing** [comment]
I guess you could "su <name of apt-enabled-account>", then run umake normally.
I'm not sure, there might be a few symlinks to fix, if that's the case let me know, but it could work properly right away

**Comment by hungrymonkey** [comment]
Oh yea, I did try it. It kinda runs as a user and cannot download in another user's home director. 

I already decided on the ppa route.
> su powerfuluser
>Password: 

>$ umake android
>Choose installation path: /home/notadmin/.local/share/umake/android/android-studio

>[I Accept (a)/I don't accept (N)] a
>Downloading and installing requirements                                        |
>100% |#########################################################################|
>ERROR: Unhandled exception
>Traceback (most recent call last):
>  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
>    function(*args, **kwargs)
>  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 371, in download_and_requirements_done
>    self.decompress_and_install(fds)
>  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 382, in decompress_and_install
>    os.makedirs(self.install_path, exist_ok=True)
>  File "/usr/lib/python3.5/os.py", line 231, in makedirs
>    makedirs(head, mode, exist_ok)
>  File "/usr/lib/python3.5/os.py", line 231, in makedirs
>    makedirs(head, mode, exist_ok)
>  File "/usr/lib/python3.5/os.py", line 241, in makedirs
>    mkdir(name, mode)
>PermissionError: [Errno 13] Permission denied: '/home/notadmin/.local/share/umake'
>Installing Android Studio

**Comment by LyzardKing** [comment]
Ah ok... makes sense actually...
@didrocks It could be something to add to umake, a user switch for the dependency install
What do you think?

**Comment by didrocks** [comment]
I tihnk it's rare enough to have those type of accounts.

Maybe, we can list the list of packages that are needed to install. That way, @hungrymonkey can get that list, `su` to the user he desired, install them, and then, use umake which won't ask for admin permissions as all package dependencies are already installed.
