### ISSUE TITLE
Visual Studio Code: Error Installing

### ISSUE THREAD

**Issue by elson1996** [ubuntu/ubuntu-make#458]
The following error is obtained on trying to install Visual Studio Code on `Ubuntu 16.04 LTS` using Ubuntu Make version 17.03
```
ERROR: Unhandled exception                           #                         |
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 414, in decompress_and_install_done
    self.post_install()
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 754, in post_install
    exec=self.exec_path,
AttributeError: 'VisualStudioCode' object has no attribute 'exec_path'
```

**Comment by LyzardKing** [comment]
@elson1996 Are you updating an already installed instance of vscode?
If so it's a known issue, it's been fixed in #447 
It's not been released yet.
You can remove the previously installed version before reinstalling.
If you want you can try the snap (with the --classic flag), that is updated to follow the master branch

**Comment by LyzardKing** [comment]
@elson1996 Any updates?

**Comment by elson1996** [comment]
@LyzardKing Yes the bug seems to be same as #447 as the problem occurs since the installation directory was not empty. It works fine if I remove the installation directory before installation using umake

**Comment by LyzardKing** [comment]
Yes, so the solution is to either install the snap or 
simply remove the thing you are trying to install before the upgrade.
Closing since it's a known issue (we need a new release, 
but there's still some bug fixing that needs to be done)
