### ISSUE TITLE
Discourage language-specific package installation with sudo

### ISSUE THREAD

**Issue by stuartlangridge** [ubuntu/ubuntu-make#46]
When udtc moves on from Android to other development areas (specifically web development), it would be a good time to make Ubuntu work well out of the box with language-specific package managers. In particular, `sudo {pip,npm,gem} install` is a bad way to work -- system level belongs to `apt`. So, two thoughts:

1. distro-patch (possibly also upstream) pip, gem, npm, etc so that they warn when used as root/with sudo (possibly even require a --yes-really option or similar)
2. set up user accounts on the system so that, out of the box, `pip install XXX` or `gem install XXX` work correctly when run as a user (rather than failing because they can't write to /var/lib/gems or some other root folder)

**Comment by didrocks** [comment]
Now done in pip in vivid (can't backport that patch to latest LTS unfortunately). Upstream is also now working on a more usptream solution, but the ubuntu patch will stay until they get their solutions in trunk.

**Comment by didrocks** [comment]
checked that all other package managers (gem, bower, npm) have a sane user-only behavior by default.
