### ISSUE TITLE
Atom command line doesn't work after installation with umake

### ISSUE THREAD

**Issue by Peel40** [ubuntu/ubuntu-make#460]
Hi! 

I installed Atom using umake and now I can't run commands such as `atom` or `apm`. What can I do? I'm using Ubuntu 16.04.2 LTS.

![image](https://user-images.githubusercontent.com/12256669/27516987-fce90568-5991-11e7-97f3-0efb5377c2fc.png)

Thanks for your time,
Omar

**Comment by LyzardKing** [comment]
As noted in the issue template and the readme,
you need the latest version from the ppa.

**Comment by Peel40** [comment]
I already had the latest version from the ppa, I installed today from github instructions but I reinstalled atom, rebooted and now it is solved.

Thank you for you time,
Omar
