### ISSUE TITLE
PyImport_GetModuleDict: no module dictionary

### ISSUE THREAD

**Issue by brianally** [ubuntu/ubuntu-make#467]
Linux Mint 18.1

```sh
bally@pan ~ $ umake --version
17.03
bally@pan ~ $ uname -a
Linux pan 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
bally@pan ~ $ python --version
Python 2.7.12
```
I'm attempting to install Visual Studio Code but umake is complaining:

```sh
bally@pan ~ $ umake ide visual-studio-code
Choose installation path: /home/bally/.local/share/umake/ide/visual-studio-code [ENTER]
[SNIP]
[I accept (a)/I don't accept (N)] a
Downloading and installing requirements
ERROR: [Errno 1] Operation not permitted
100% |##################################[SNIP]
ERROR: Package requirements can't be met: [Errno 1] Operation not permitted
```

I was able to install Atom successfully, leading me to wonder whether the problem was Microsoft's. For the hell of it, i tried again, and this time i received a little more info:

```sh
[I accept (a)/I don't accept (N)] a
Downloading and installing requirements
ERROR: [Errno 1] Operation not permitted
100% |#########################################[SNIP]
ERROR: Package requirements can't be met: [Errno 1] Operation not permitted
Fatal Python error: PyImport_GetModuleDict: no module dictionary!

Current thread 0x00007f5bd34da700 (most recent call first):
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 573 in run
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 139 in run
  File "/usr/lib/python3/dist-packages/umake/__init__.py", line 131 in main
  File "/usr/bin/umake", line 9 in <module>
Aborted
```

I cloned master with the same (first) error, but not the Python complaint. 

```sh
ERROR: Package requirements can't be met: [Errno 1] Operation not permitted

Your currently installed version (17.03-54-gc386da6) differs from the latest release (17.03)
```

I immediately ran it again and this time received the same Python stack trace.

Any insight appreciated, of course.

**Comment by brianally** [comment]
Being an idiot, i posted this before thinking to update my packages. I did so, then tried again. The install went perfectly. :-/

After cursorily weeding out the obvious, i'm left with ~90 packages, one of which might be responsible for fixing this. (The only python-specific one was python-samba.) I can post the list if you'd like.

However, given that the error msg kept changing (the stack trace not always appearing) i'm wondering whether this is a Heisenbug, and that updating packages had nothing to do with it.

**Comment by tiagmoraismorgado** [comment]
**I would have a minor set of suggestions to do regarding this thread, that i don't have any warranty to fix the problem, but may work out**:

- _update all your packages with your package manager;_
- _install missing packages;_
- _run a recursive chmod 777;_
- _read the documentation again to check if you didn't miss any important step_

**I know that this will probably not be enough, but is my best advice under this specific situation**

**Comment by brianally** [comment]
"run a recursive chmod 777;"

That's terrible advice.

**Comment by LyzardKing** [comment]
You could try to run: umake -vv ide visual-studio-code
I'm not sure that it would report the error, but it might.

Also, the latest version is available as a snap, so using that might simplify things.
A part from this, you can check the dependencies, to see if something is missing, but it would be strange.

**Comment by brianally** [comment]
That might be helpful. But it's now installed and working fine.

It might be useful to keep this open for a little while in case someone else comes across this, but i'm fine with closing it.
