### ISSUE TITLE
Unicode error when installing visual-studio-code

### ISSUE THREAD

**Issue by coachmcguirk23** [ubuntu/ubuntu-make#471]
Versions:
umake = 17.03
ubuntu = 16.04

After running:
"umake ide visual-studio-code"

Error: UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 1658: ordinal not in range(128)

As per #137, I have also tried:
export LANGUAGE=C
umake web visual-studio-code

But I get the same error.

**Comment by LyzardKing** [comment]
Hi. Is this still an issue with the snap package?

**Comment by LyzardKing** [comment]
Closing since I can't replicate.
If there are more details please open the issue again
