### ISSUE TITLE
Installing python dependencies not working on a fresh clone 

### ISSUE THREAD

**Issue by levlaz** [Ubuntu/ubuntu-make#472]
Ubuntu Version: 16.04 LTS 
Umkake version: Master branch as of 9/24/2017 @ 6:00 PM PDT. 
Bzr version: Bazaar (bzr) 2.7.0 

Did a fresh clone of this repo. Followed the README. When it came time to install python dependencies, I get the following error message. 

```
(venv) ubuntu@lev:~/gh/ubuntu-make$ pip install -r requirements.txt 
Obtaining apt from bzr+lp:python-apt/@0.9.3.5#egg=apt (from -r requirements.txt (line 2))
  Checking out lp:python-apt/ (to revision 0.9.3.5) to ./venv/src/apt
bzr: ERROR: Not a branch: "bzr+ssh://bazaar.launchpad.net/+branch/python-apt/".
Command "bzr branch -q -r 0.9.3.5 lp:python-apt/ /home/ubuntu/gh/ubuntu-make/venv/src/apt" failed with error code 3 in None
```

I am not versed enough in bzr to do any meaningful troubleshooting. However, I am not able to see this branch on [LaunchPad](https://code.launchpad.net/python-apt/+branches) either, perhaps it was moved or renamed?

**Comment by LyzardKing** [comment]
In Ubuntu you should really install the Ubuntu packages, even for the python dependencies.
Come to think of it we should list them in the readme
..
For now you can find them in:
https://github.com/ubuntu/ubuntu-make/blob/master/debian/control

I am looking at a proper way to add the python apt bindings...

**Comment by LyzardKing** [comment]
@levlaz can you test one thing for me?
if in requirements.txt you were to replace the line:
`-e bzr+lp:python-apt/@0.9.3.5#egg=apt`
with:
`https://launchpad.net/ubuntu/+archive/primary/+files/python-apt_1.1.0~beta1build1.tar.xz; sys_platform == 'linux'`
That should install the correct python-apt version...
If you can try it out then let me know!
