### ISSUE TITLE
snap segfaults on artful

### ISSUE THREAD

**Issue by datzuma** [ubuntu/ubuntu-make#473]
Installed latest snap, and when I run it, it segfaults.

Y@X:~$ ubuntu-make.When umake 
Segmentation fault

Same snap tested on Ubuntu 16.04, no problems. When installed from repo, I'm faced with unmatched checksum with Andrdoi Studio, so I think that isn't an option.

**Comment by LyzardKing** [comment]
The issue has been reported in the snapcraft forum, if you can add your experience it might be useful to note that it's not a single issue.

https://forum.snapcraft.io/t/segmentation-fault-in-python-snap/2218

**Comment by datzuma** [comment]
Stupid me, didn't even thought that.. thanks. :)

**Comment by xanscale** [comment]
as workaround install umake from official repo to download all dependency and after clone master and use cloned version,

https://github.com/ubuntu/ubuntu-make/issues/483
