### ISSUE TITLE
Question: How looks release plan?

### ISSUE THREAD

**Issue by michaldo** [ubuntu/ubuntu-make#477]
Last release 17.03 was made 10 Mar 2017, more than half year ago. In the meantime new features were added (Maven support)
When next version will be released?
Is there any way to vote up for new release?

**Comment by LyzardKing** [comment]
The newer releases are snaps.
If you install the snap you'll always have the latest version, since it
pulls from master after every commit

**Comment by michaldo** [comment]
I installed with command 
sudo snap install --classic ubuntu-make

How run umake now?

**Comment by LyzardKing** [comment]
Now you can run it normally. You just need to call ‘ubuntu-make.umake‘
instead of ‘umake‘

**Comment by michaldo** [comment]
It does not work on my Linux Mint

michal@michal-desktop ~ $ snap version
snap       2.28.1
snapd      2.28.1
series     16
linuxmint  18.1
kernel     4.4.0-91-generic
michal@michal-desktop ~ $ snap list
Name         Version    Rev   Developer  Notes
core         16-2.28.1  3017  canonical  core
ubuntu-make  master     74    didrocks   classic
michal@michal-desktop ~ $ ubuntu-make.umake
ubuntu-make.umake: command not found

**Comment by michaldo** [comment]
It does not work on my Linux Mint

michal@michal-desktop ~ $ snap version
snap       2.28.1
snapd      2.28.1
series     16
linuxmint  18.1
kernel     4.4.0-91-generic
michal@michal-desktop ~ $ snap list
Name         Version    Rev   Developer  Notes
core         16-2.28.1  3017  canonical  core
ubuntu-make  master     74    didrocks   classic
michal@michal-desktop ~ $ ubuntu-make.umake
ubuntu-make.umake: command not found
