### ISSUE TITLE
Duplicate Icon for Visual Studio Code in Ubuntu 17.10

### ISSUE THREAD

**Issue by valmar** [ubuntu/ubuntu-make#481]
When Visual Studio code is installed and started in Ubuntu 17.10 using the current master branch, an icon is correctly added to Gnome. However, if you pin the icon on the Ubuntu Dock and click on it to start Visual Studio Code, a second icon appears at the bottom of  the Dock to manage the open windows of the running application.

The fix is rather easy: the following line should be added to the desktop file generated by ubuntu make

`StartupWMClass=Code`

**Comment by LyzardKing** [comment]
Great idea.
Do you want to open a pr with this change?
If you want to try the method used is ` get_application_desktop_file`,
that has a variable `extra`, where you can copy the additional parts of the desktop file.

**Comment by valmar** [comment]
I'll try, thanks for the hints!

**Comment by geajack** [comment]
This issue is still happening to me on Ubuntu 18.10. I tracked down the `.desktop` file in `/usr/share/applications` (assuming that's the correct one) and it has the line `StartupWMClass=Code` in it.

**Comment by LyzardKing** [comment]
Actually, if you have a .desktop file in /usr/share/applications, it means you installed vscode via apt (or a deb).
ubuntu-make holds all the .desktop files in /home/<user>/.local/share/applications.
