### ISSUE TITLE
[Request] Why not update ppa for artful ?

### ISSUE THREAD

**Issue by xanscale** [ubuntu/ubuntu-make#483]
actually there is not way to install android studio throught umake in ubuntu 17.10:

- official package 16.11.1 is outdated and not works downloads of files
- snap package not works because there is bug in snap - https://forum.snapcraft.io/t/segmentation-fault-in-python-snap/2218

since in one month there is not even the cause of the problem does not seem to be fast resolution, I suggest updating the ppa as an alternative method to install umake until snap becomes stable.

as workaround i found is to install umake from official repo to download all dependency and after clone master and use cloned version, but is not so easy

**Comment by LyzardKing** [comment]
I'm looking to set up the ppa as a daily report.
So at least we can have a new build every day there's an update in the repo.
I don't think it would work for more than once a day, but that should be good enough.
I'll keep this issue open as a reminder

**Comment by LyzardKing** [comment]
Ok, we now have a ppa again!
https://code.launchpad.net/~lyzardking/+archive/ubuntu/ubuntu-make

Test it and let me know...

**Comment by LyzardKing** [comment]
Closing since the ppa is now in the README
