### ISSUE TITLE
ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/3.0.0.18/android-studio-ide-171.4408382-linux.zip doesn't match. Corrupted download? Aborting.

### ISSUE THREAD

**Issue by THUFIR** [ubuntu/ubuntu-make#485]
While I haven't compiled umake directly, I think this is a bug:

https://askubuntu.com/questions/969080/error-the-checksum-of-https-android-studio-ide-zips-2-3android-studio-ide

The full log is here:

https://gist.github.com/anonymous/1d9a19bfb8ba25bfb1f3445d69621106

Looks like the checksum matches, then another umake user indicates it might be a bug.  Let me know what other info I can provide.  (Should be easily replicated or shown to work with that version/system info.)

**Comment by LyzardKing** [comment]
Can you check the version of Ubuntu and umake?

**Comment by mubdiur** [comment]
@LyzardKing 
I am also having the same  issue.
`umake --version` gives:
`16.11.1`

and `lsb_release -a` gives:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by LyzardKing** [comment]
@mubdiur Were you able to use the source version?
I'll close now, since the snap issue is known and has been raised in the snapcraft forum.

**Comment by 0xInfection** [comment]
Hi there,

Does this issue have a fix yet? I'm on `umake 18.09` and I still have this problem.

**Comment by LyzardKing** [comment]
umake 18.04 is very old now.. have you tried updating?
Also, what is the issue you're having? the previous issue is related to the snap version.
If this is not the case please open a new issue.

**Comment by 0xInfection** [comment]
Hey @LyzardKing, thanks for the quick reply. Right now, I'm running Ubuntu 20.04 LTS with all latest updates, installed `umake` via apt, i.e. from official source repos. So I guess that is what the latest version in the official ubuntu repo is. Running `umake android` gives something of a similar error.

**Comment by LyzardKing** [comment]
The version in the default repos is very old.. I should probably update it...
meanwhile you can use the snap (or the ppa)

**Comment by adeept** [comment]
Hello，

Thanks for your feedback.
 
If you are satisfied with our product and service, please leave us a positive feedback and review.
 
If you have any other questions, please feel free to contact us, we will do our best to help you.
 
Best!

2020-07-03 


Adeept Technical Support Team
Shenzhen Adeept Technology Co., Ltd.
E-mail: support@adeept.com
Website: www.adeept.com

   



发件人：Pinaki Mondal <notifications@github.com>
发送时间：2020-07-03 03:56
主题：Re: [ubuntu/ubuntu-make] ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/3.0.0.18/android-studio-ide-171.4408382-linux.zip doesn't match. Corrupted download? Aborting. (#485)
收件人："ubuntu/ubuntu-make"<ubuntu-make@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Hey @LyzardKing, thanks for the quick reply. Right now, I'm running Ubuntu 20.04 LTS with all latest updates, installed umake via apt, i.e. from official source repos. So I guess that is what the latest version in the official ubuntu repo is. Running umake android gives something of a similar error.

**Comment by adeept** [comment]
Hello,

May I ask which product have you purchased? And what is the specific problem. 
We look forward to receiving your email to solve the problem for you as soon as possible. Thank you.

Best!

2020-07-03 


Adeept Technical Support Team
Shenzhen Adeept Technology Co., Ltd.
E-mail: support@adeept.com
Website: www.adeept.com

   



发件人：Galileo Sartor <notifications@github.com>
发送时间：2020-07-03 04:21
主题：Re: [ubuntu/ubuntu-make] ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/3.0.0.18/android-studio-ide-171.4408382-linux.zip doesn't match. Corrupted download? Aborting. (#485)
收件人："ubuntu/ubuntu-make"<ubuntu-make@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

The version in the default repos is very old.. I should probably update it...
meanwhile you can use the snap (or the ppa)
