### ISSUE TITLE
Incorrect filename for Datagrip icon

### ISSUE THREAD

**Issue by hgarfer** [ubuntu/ubuntu-make#493]
The icon filename for Datagrip has changed, now instead of 'product.png' it is named 'datagrip.png',

**Comment by hgarfer** [comment]
Have created a pull request that fixes it here: https://github.com/ubuntu/ubuntu-make/pull/492

**Comment by LyzardKing** [comment]
Thanks! Can you update the mock file for the test as well?
In tests/data/server-content you can find a mock version of the tarfile and webpage.

**Comment by hgarfer** [comment]
Sorry about that, didn't see that file, fixed the test data in https://github.com/ubuntu/ubuntu-make/pull/492/commits/fc89e11c4c23e8d0e2fd963d61a6400f7ade83fa

Please let me know if I need to fix anything else
