### ISSUE TITLE
GPG error:  : Failed to fetch dl.google.com/linux/chrome Wrong sources.list entry or malformed file when apt-get update

### ISSUE THREAD

**Issue by Sathiyarajan** [ubuntu/ubuntu-make#495]
GPG error: http://www.apache.org 22x InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A278B781FE4B2BDA
W: Failed to fetch https://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
the above error is showing when i tried apt-get update in ubuntu 14.04

**Comment by LyzardKing** [comment]
This is an issue not related to ubuntu-make.
You have to check if there's a post about the chrome ubuntu ppa.
