### ISSUE TITLE
visual-studio-code

### ISSUE THREAD

**Issue by jackdyson31** [ubuntu/ubuntu-make#499]
Hi development team,

tried to download Visual Studio Code with umake 17.03 and:

umake ide visual-studio-code 
Choose installation path: <directory>
ERROR: https://code.visualstudio.com/License couldn't finish download: 404 Client Error: Not Found for url: https://code.visualstudio.com/License
ERROR: An error occurred while downloading https://code.visualstudio.com/License: 404 Client Error: Not Found for url: https://code.visualstudio.com/License

so I checked the website and indeed it is true - is there a fix?

Best

J

**Comment by LyzardKing** [comment]
Hi!
The url at the moment is not reachable, but still linked in the vscode
webpage.
For now you can accept the license with '--accept-license'.
That should skip the license download

**Comment by jackdyson31** [comment]
Hey, cheers for the quick reply, here is what I got:

umake ide visual-studio-code --accept-license

Choose installation path: <dir>
ERROR: https://code.visualstudio.com/License couldn't finish download: 404 Client Error: Not Found for url: https://code.visualstudio.com/License
ERROR: An error occurred while downloading https://code.visualstudio.com/License: 404 Client Error: Not Found for url: https://code.visualstudio.com/License

**Comment by LyzardKing** [comment]
It works now. Upstream fixed the webpage
Closing
