### ISSUE TITLE
Classic snaps are currently broken in 17.10

### ISSUE THREAD

**Issue by davclark** [Ubuntu/ubuntu-make#500]
It would be helpful to update the README for now. Relevant posts:

- https://forum.snapcraft.io/t/where-how-is-umake-installed-usage/2615/6
- https://forum.snapcraft.io/t/classic-snaps-failing-on-ubuntu-17-10/2324/50

**Comment by LyzardKing** [comment]
I did add in the README:
"If the snap does not work there is a daily build ppa:"

**Comment by hktr92** [comment]
Today, January 15, 2018, the snap issue persists.

Tried to install via PPA but fails, here's the link for apt output: https://pastebin.com/agD36HgU

lsb_release output:

    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 17.10
    Release:        17.10
    Codename:       artful

**Comment by LyzardKing** [comment]
Closing since it's not an issue with umake
