### ISSUE TITLE
ANDROID_HOME and ANDROID_SDK environment variables are not set

### ISSUE THREAD

**Issue by titobrasolin** [Ubuntu/ubuntu-make#502]
**ubuntu:** 14.04.5 LTS
**umake:** 17.03

In my opinion the problem is here:
https://github.com/Ubuntu/ubuntu-make/blob/master/umake/frameworks/android.py#L133

[add_env_to_user](https://github.com/Ubuntu/ubuntu-make/blob/master/umake/tools.py#L427) should be called only once (with a dictionary of environment variables) because it removes framework envs from user at every execution.

The debug messages look fine:
```
DEBUG: Adding
/home/theuser/.local/share/umake/android/android-sdk
to user's ANDROID_HOME for Android SDK
DEBUG: Adding $ANDROID_HOME to user's ANDROID_SDK for Android SDK
DEBUG: Adding $ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH to
user's PATH for Android SDK
```
Nevertheless, at the end only the PATH for Android SDK is written to .profile.

E.g. rust uses `add_env_to_user` correctly:
https://github.com/Ubuntu/ubuntu-make/blob/master/umake/frameworks/rust.py#L80

**Comment by titobrasolin** [comment]
I modified `android.py` like this:
```
class AndroidSDK(umake.frameworks.baseinstaller.BaseInstaller):
[...]
    def post_install(self):
        """Add necessary environment variables"""
        # add a few fall-back variables that might be used by some tools
        # do not set ANDROID_SDK_HOME here as that is the path of the preference folder expected by the Android tools
        # add "platform-tools" to PATH to ensure "adb" can be run once the platform tools are installed via
        # the SDK manager
        add_env_to_user(self.name, {"ANDROID_HOME": {"value": self.install_path, "keep": False},
                                    "ANDROID_SDK": {"value": self.install_path, "keep": False},
                                    "PATH": {"value": [os.path.join(self.install_path, "tools"),
                                                       os.path.join(self.install_path, "platform-tools")]}})
[...]
```
It now works as expected (variables cannot be defined in terms of each other because dictionaries are not sorted).

By the way, it seems that Android NDK has similar problems.

**Comment by LyzardKing** [comment]
Hi! Thanks for the contribution.
Could you make a PR with the change and run the tests?
As soon as I can I'll then test it and merge

**Comment by titobrasolin** [comment]
Ok @LyzardKing Just give me a day or two (I'm quite busy on different tasks right now).

**Comment by titobrasolin** [comment]
Hi @LyzardKing Here it is: #503 
I ran pep8 and small tests.
