### ISSUE TITLE
android studio will not install through make

### ISSUE THREAD

**Issue by nastybuttler322** [Ubuntu/ubuntu-make#504]
I have tried four times to download Android Studio through Ubuntu Make. I keep getting this:

December 9, 2016 [I Accept (a)/I don't accept (N)] a Downloading and installing requirements | ERROR: https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip couldn't finish download: The checksum of https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip doesn't match. Corrupted download? Aborting. 100% |#########################################################################| ERROR: The checksum of https://dl.google.com/dl/android/studio/ide-zips/3.0.1.0/android-studio-ide-171.4443003-linux.zip doesn't match. Corrupted download? Aborting.

The checksum never matches. I never have had a matching checksum for anything I have downloaded. Is there a way to go around this checksum issue so I can use this feature that Ubuntu says is awesome?

I am using the latest 17.10 version of Ubuntu, and the latest version of make.

**Comment by LyzardKing** [comment]
Are you using the version of umake from the new ppa?
If so, could you run umake -vv android android-studio?
That way we can see what checksums is parsed.

**Comment by nastybuttler322** [comment]
lol no. I followed the directions from Ubuntu's web site, on the developer page. I switched over to regular Debian since I posted this. Ubuntu has a lot more issues than not updating the website to reflect the change that caused this issue for me.
