### ISSUE TITLE
Add support to Godot Game Engine

### ISSUE THREAD

**Issue by mstuttgart** [Ubuntu/ubuntu-make#509]
It would be nice if support for Godot Game Engine. :smile: 

* https://godotengine.org/
* https://godotengine.org/download

This engine is opensource and free. Please consider it.

I can add support and send a PR, but I not find `ubuntu-make` docs.

**Comment by LyzardKing** [comment]
Hi! If you could start a Pr it would be great.
You can have a look at the games.py file, you add a class there.
As an example to copy you can look at the SublimeText class in ide.py (that is the simplest, and it seems to be the use case here).
After that is set up You need to add entries in tests (both medium and large.) I'll help with that!
Let me know if you get it running!

**Comment by mstuttgart** [comment]
Thanks @LyzardKing. I'm going to start working on it.

**Comment by LyzardKing** [comment]
Let me know if you need any help
