### ISSUE TITLE
Add support for Ren'Py

### ISSUE THREAD

**Issue by Dekedro** [Ubuntu/ubuntu-make#515]
Hi, it would be great to have support for Ren'Py - visual novel engine. It's open source and there are archives to download in their page:

https://www.renpy.org/
https://www.renpy.org/latest.html

I'm not familiar with python but I can try to make PR

**Comment by LyzardKing** [comment]
Hi! It could fit in the games.py file.
If you want to have a look at it, it should be fairly easy.
You can look at the Stencyl class in that file.
You can then replace the name, url (use: https://www.renpy.org/latest.html), requirements, and the regex to find  the tarfile.
If you need help let me know

**Comment by Dekedro** [comment]
After some consideration, decided to use renpy from official ubuntu packages: https://packages.ubuntu.com/source/xenial/renpy. I think that it is not efficient to duplicate work.
