### ISSUE TITLE
android android-ndk md5sum error

### ISSUE THREAD

**Issue by Goddard** [Ubuntu/ubuntu-make#518]
Trying to install android gave me an error on kubuntu 16.04

Downloading and installing requirements                                                                                                          |
ERROR: https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip couldn't finish download: The checksum of https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip doesn't match. Corrupted download? Aborting.
100% |###########################################################################################################################################|
ERROR: The checksum of https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip doesn't match. Corrupted download? Aborting.

**Comment by Goddard** [comment]
yes thanks, it works with the ppa now.

**Comment by LyzardKing** [comment]
No problem. Closing now
