### ISSUE TITLE
Firefox Dev icons moved and desktop shortcut missing StartupWMClass

### ISSUE THREAD

**Issue by HarlemSquirrel** [Ubuntu/ubuntu-make#520]
I noticed that the last Firefox Dev update seems to have broken my desktop icon on GNOME. The icon was blank. 

I opened my desktop shortcut to find `StartupWMClass` missing. The `Icon=` pointed to a non-existent file. 

I looked through `~/.local/share/umake/web/firefox-dev/` and found the icons in a new place. 

```
$ find ~/.local/share/umake/web/firefox-dev -name *.png
~/.local/share/umake/web/firefox-dev/browser/chrome/icons/default/default16.png
~/.local/share/umake/web/firefox-dev/browser/chrome/icons/default/default128.png
~/.local/share/umake/web/firefox-dev/browser/chrome/icons/default/default32.png
~/.local/share/umake/web/firefox-dev/browser/chrome/icons/default/default64.png
~/.local/share/umake/web/firefox-dev/browser/chrome/icons/default/default48.png
```

I updated my desktop shortcut...
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Firefox Developer Edition
Icon=/home/USERNAME/.local/share/umake/web/firefox-dev/browser/chrome/icons/default/default128.png
Exec=/home/kem2028/.local/share/umake/web/firefox-dev/firefox %u
Comment=Firefox Aurora with Developer tools
Categories=Development;IDE;
Terminal=false
StartupWMClass=Firefox Developer Edition
```

And viola! Back in business.

**Comment by LyzardKing** [comment]
The icon has been fixed in the last commit, so an install should fix that..
StartupWMClass is still there in my install...
Try reinstalling, that should fix any inconsistencies.

**Comment by HarlemSquirrel** [comment]
After a reinstall, I lost the desktop icon altogether. I got it back by replacing `Exec=` and `TryExec=` with

```
Exec=/home/USERNAME/.local/share/umake/web/firefox-dev/firefox %u
```

**Comment by LyzardKing** [comment]
When I reinstalled I got the correct docker icon.
Did you update from the ppa? The new version was released today..

**Comment by HarlemSquirrel** [comment]
An install from master seems to leave me without an entry in GNOME at but
the .desktop file is in the correct place.

Kevin McCormack
Full Stack Web Developer
HarlemSquirrel.github.io

**Comment by HarlemSquirrel** [comment]
I was installing using `bin/umake` from the master branch of this repo. I just added the ppa and updated my install, reinstalled firefox-developer and it broke my desktop icon again.

**Comment by LyzardKing** [comment]
an install from the ppa or master (they are the same at this point) work properly for me...
What has it broken on you desktop icon?
Is the path in the .desktop file correct?

**Comment by HarlemSquirrel** [comment]
It seems to be the `TryExec=` line

Kevin McCormack
Full Stack Web Developer
HarlemSquirrel.github.io

**Comment by LyzardKing** [comment]
That shoud point to the actual executable file, while exec points to the link.
Can you verify that on your system?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by HarlemSquirrel** [comment]
`TryExec` does point to the actual executable file. The next line `Exec=firefox-developer` appears to be OK as well but GNOME complains 

```
(gnome-software:3398): As-WARNING **: failed to rescan: Failed to parse /home/USER/.local/share/applications/firefox-developer.desktop file: cannot process file of type application/x-desktop
```

**Comment by LyzardKing** [comment]
Is it the same after a restart?
If you install firefox-dev, then restart (or logout...)

**Comment by LyzardKing** [comment]
If that doesn't work, try simply adding %u to the Exec line...

**Comment by LyzardKing** [comment]
You're right! I had to reinstall the system to see that...Sorry!
The path is wrong...
it should have been corrected to /home/galileo/.local/share/umake/web/firefox-dev/browser/chrome/icons/mozicon128.png

**Comment by LyzardKing** [comment]
...the source is fine...might be an issue with launchpad...

**Comment by LyzardKing** [comment]
Closing since this works now.
