### ISSUE TITLE
redis server is not working properly

### ISSUE THREAD

**Issue by rashmitpankhania** [Ubuntu/ubuntu-make#528]
![screenshot from 2018-02-17 19-00-12](https://user-images.githubusercontent.com/24410731/36341467-d6dd3752-1414-11e8-9d7d-44ebba948190.png)
tried it with also without terminal

**Comment by LyzardKing** [comment]
Is this issue related to ubuntu-make?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
