### ISSUE TITLE
Android Studio download page changed, breaking udtc

### ISSUE THREAD

**Issue by castrojo** [ubuntu/ubuntu-make#53]
I saw Android Studio hit 1.0 and tried this: 

```
Android Studio is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)] y
Choose installation path: /home/jorge/tools/android/android-studio
ERROR: Download page changed its syntax or is not parsable
```

**Comment by Luke-SF** [comment]
This is still happening... and is this really the recommended way of upgrading Android Studio? I saw no upgrade option or working upgrade option in IDE.

**Comment by LyzardKing** [comment]
It should be fixed in the recent builds..
Do you have the ppa set up?
