### ISSUE TITLE
Add Support for Godot

### ISSUE THREAD

**Issue by monyarm** [Ubuntu/ubuntu-make#531]
The Godot downloads give you a zip file that contains a folder with an executable and a dll (if you choose the MONO version), it would be great to have it added to ubuntu-make

**Comment by LyzardKing** [comment]
Godot is distributed as an appimage (I believe).
Appimages have their own way to add .desktop files and configuration.
So unless we decide to add appimages I believe this should not be added.
I would be interested in a simple tarfile for godot though...

**Comment by monyarm** [comment]
Actually Godot is distributed as a zip

**Comment by LyzardKing** [comment]
Yes, but in the zip there's an appimage.

**Comment by monyarm** [comment]
The regular file contains just a single executable (which I guess must be the app image you're referring to), while the mono version also contains a few dlls

**Comment by LyzardKing** [comment]
Could you ask the upstream devs if it's an appimage?
Then we can figure out where to go from there

**Comment by monyarm** [comment]
Well I checked and they have feature requests for adding appimages, and also unofficial appimage builds, so I don't think it is an appimage.

**Comment by LyzardKing** [comment]
You can try to add it to umake then!
It shouldn't be too difficult...being on github you can look at the atom downloader...
