### ISSUE TITLE
umake breaks the system installing redundant packages

### ISSUE THREAD

**Issue by Suncatcher** [ubuntu/ubuntu-make#537]
Don't know whether it is related to umake itself or to eclipse package in umake I just post it here, as I am totally newto umake.
I am trying to install eclipse and get these errors:

![screenshot_2018-03-29_14-10-53](https://user-images.githubusercontent.com/6388034/38085950-33334cf2-335b-11e8-95d2-8de388043eb2.png)

Why umake wants to install `openjdk8` and `ca-certificates` packages disregard they **already** exist in the system?
Though I have oracle java not openjdk, but umake probably should detect that avoiding installing conflicting packages.

**Comment by Suncatcher** [comment]
And what about `ca-certificates`? Why it is not detected?

**Comment by LyzardKing** [comment]
It must have not been installed, umake only runs the install.
It's like running apt install ca-certificates...

**Comment by Suncatcher** [comment]
Well, smth is definitely wrong with the installation process

![image](https://user-images.githubusercontent.com/6388034/38093393-7bfd58ca-3373-11e8-9889-eccbe512b59b.png)

**Comment by Suncatcher** [comment]
Well, after reboot it worked.

**Comment by LyzardKing** [comment]
Yes, after some of the installs a login is required to update the PATH.

**Comment by Suncatcher** [comment]
And even detected my oracle jdk, and omitted openjdk. Cool! Dunno the first trial failed.

**Comment by LyzardKing** [comment]
the ca-certificates is an issue with the apt install, not umake. If it pops up again we'll revisit this, or ask somebody on the ubuntu desktop team.
