### ISSUE TITLE
android-studio ERROR: Download page changed its syntax or is not parsable (url missing)

### ISSUE THREAD

**Issue by lrslei** [ubuntu/ubuntu-make#541]
As the package seems not to work when installed with snap classic option, I tried with both ppa:lyzardking and this git version, but when I try to install android studio with the "android" option it always gives me:

"ERROR: Download page changed its syntax or is not parsable (url missing)"

Is there anything I can edit to make it work?

**Comment by LyzardKing** [comment]
Hi.
Google changed the website layout, so it broke umake...
It's fixed now, as of https://github.com/ubuntu/ubuntu-make/commit/53fab20d83f5e88e346ab055d2cb331c07613769

You can use the git version right now, or wait the next pull to the ppa
