### ISSUE TITLE
snap version questtion

### ISSUE THREAD

**Issue by freedomDR** [ubuntu/ubuntu-make#544]
I install it through snap., when I use it the hint is required version is ubuntu-make==**18.5**, actually I throught ubuntu-make.umake --version the answer is 18.05. Is it conflicting?

**Comment by LyzardKing** [comment]
It shouldn't be conflicting, it's just snap being snap and cropping 18.05 to 18.5 I think...
Are you getting an error?
Can you use the snap? We're generally having issues with it...

**Comment by freedomDR** [comment]
no, when I install android studio, the problem is **pkg_resources.DistributionNotFound: The 'Ubuntu-Make==18.5' distribution was not found and is required by the application**

**Comment by LyzardKing** [comment]
I'm fixing this now...but due to a segfault in the snap it might still not work.
Were you using the previous version of the snap?
If not it might be better for you at the moment to use the ppa..
(I'll rebuild the snap now to be sure)

**Comment by freedomDR** [comment]
I'm using the lasted version in ubuntu18. I will try to install from ppa. That should have no problem. Thank you

**Comment by LyzardKing** [comment]
The version issue should now be fixed.
The issue regards the internal version of the ubuntu-make package being normalized, we can ignore it since the user facing version is the correct one, and use the correct one when python is importing the package
