### ISSUE TITLE
Unable to install Maven using umake.

### ISSUE THREAD

**Issue by dmuylwyk** [ubuntu/ubuntu-make#545]
Hi!

I am unable to install Maven using umake. Here are the details:

- umake version 18.05
- Ubuntu 16.04 LTS
- I've tried using both the snap and ppa versions of umake
- I've cloned the umake repository

This is what I get when I try to install Maven:

```
~ $ umake maven
Choose installation path: /home/dmuylwyk/.local/share/umake/maven/maven-lang
ERROR: Download page changed its syntax or is not parsable
```

I'd like to use to umake to install the latest version of Maven (apt gives me only 3.3.9). Is this a known issue? Is there a fix available/coming?

Also: I use umake for installing/updating IntelliJ IDEA, and for that it works flawlessly. Thanks!!

D.

**Comment by LyzardKing** [comment]
Pushing the fix now...You'll see it in the ppa

**Comment by LyzardKing** [comment]
Fixed in https://github.com/ubuntu/ubuntu-make/commit/5200889aea9e9f59935b57bebfbc138bf0b18fee

**Comment by dmuylwyk** [comment]
Brilliant. Thank you!
