### ISSUE TITLE
Add CONTRIBUTING.md with helpful tips for newcomers

### ISSUE THREAD

**Issue by patsevanton** [ubuntu/ubuntu-make#552]
Please add instruction to will add package to ubuntu-make

**Comment by LyzardKing** [comment]
What do you mean? Do you need help with adding the beaver program #551 ?

**Comment by LyzardKing** [comment]
Closing. Discussion will eventually continue on #551

**Comment by patsevanton** [comment]
I dont see  instruction to will add package to ubuntu-make.
This is issue about add instruction to will add package to ubuntu-make

**Comment by LyzardKing** [comment]
I guess we should add a CONTRIBUTING.md with a brief explanation of the file structure.
With an simple example of how to add a framework to ubuntu-make...

**Comment by patsevanton** [comment]
And link CONTRIBUTING.md to readme.md
