### ISSUE TITLE
Snap version of Ubuntu Make is broken - unable to install application (netbeans, etc)

### ISSUE THREAD

**Issue by N0rbert** [ubuntu/ubuntu-make#554]
Steps to reproduce:
1. Install Ubuntu Make as Snap on Ubuntu 18.04 LTS with
   
       $ snap refresh 
       All snaps up to date.
       $ snap install ubuntu-make --classic
       ubuntu-make master from 'didrocks' installed

       $ snap list ubuntu-make 
       Name         Version  Rev  Tracking  Developer  Notes
       ubuntu-make  master   367  stable    didrocks   classic

1. Try to install Netbeans with `umake`

       $ which umake 
       /snap/bin/umake

       $ umake ide netbeans 
       [sudo] password for user: 
       Choose installation path: /home/user/.local/share/umake/ide/netbeans

       $ ubuntu-make.umake ide netbeans
       Choose installation path: /home/user/.local/share/umake/ide/netbeans

Expected results:
* Snap version of Ubuntu Make works as APT-one.

Actual results:
* Snap version of Ubuntu Make is broken, users can't install applications with it.

Notes:
1. First seen on [AskUbuntu when user tried to install NetBeans with it](https://askubuntu.com/q/1040049/66509). Then in comments to the answer we have discovered, that this behavior is documented on official [Ubuntu Make Wiki page](https://wiki.ubuntu.com/ubuntu-make).
1. So I created [self-answered question](https://askubuntu.com/q/1040380/66509) to recommend users to use Ubuntu Make from APT-repository. But it is temporarily solution. 

Please consider to fix Snap version of Ubuntu Make.

**Comment by LyzardKing** [comment]
As you can read in the readme, the snap doesn't always work.
That's why there's a daily PPA.
At the moment I cannot figure out why the snap segfaults in newer ubuntu releases.
It mightbe fixed with the newer core18 (snaps based on 18.04 instead of 16.04)

**Comment by LyzardKing** [comment]
@N0rbert Try the --edge snap. It should work as a snap.
Plus I need testers to confirm that it works on other systems (not mine and not vms ;))
I just built and uploaded the amd64 version, so x86_64 is the only supported architecture..for the moment...

**Comment by N0rbert** [comment]
@LyzardKing Thank you for the response!

Testing on clean fully updated Ubuntu 18.04 LTS amd64 VirtualBox guest (without *proposed* updates).

```
beaver@bionic:~$ snap --version
snap    2.32.9+18.04
snapd   2.32.9+18.04
series  16
ubuntu  18.04
kernel  4.15.0-22-generic

beaver@bionic:~$ snap refresh 
All snaps up to date.

beaver@bionic:~$ snap info ubuntu-make | tail -n5
channels:                 
  stable:    master (429) 13MB classic
  candidate: ↑                 
  beta:      ↑                 
  edge:      master (450) 13MB classic

beaver@bionic:~$ snap install ubuntu-make --classic --edge
ubuntu-make (edge) master from 'didrocks' installed

beaver@bionic:~$ which umake 
/snap/bin/umake

beaver@bionic:~$ umake --version
18.05+snap450

beaver@bionic:~$ umake ide netbeans 
[sudo] password for beaver: 
Choose installation path: /home/beaver/.local/share/umake/ide/netbeans
beaver@bionic:~$ umake ide arduino
WARNING: Arduino is now in the electronics category, please refer it from this category from now on. This compatibility will be dropped in the future.
WARNING: Arduino is now in the electronics category, please refer it from this category from now on. This compatibility will be dropped in the future.
Choose installation path: /home/beaver/.local/share/umake/ide/arduino
beaver@bionic:~$

beaver@bionic:~$ ubuntu-make.umake ide netbeans
Choose installation path: /home/beaver/.local/share/umake/ide/netbeans
beaver@bionic:~$ ubuntu-make.umake ide arduino
WARNING: Arduino is now in the electronics category, please refer it from this category from now on. This compatibility will be dropped in the future.
WARNING: Arduino is now in the electronics category, please refer it from this category from now on. This compatibility will be dropped in the future.
Choose installation path: /home/beaver/.local/share/umake/ide/arduino
beaver@bionic:~$ 


```

So it does not work on 18.04 LTS. Tested on two clean VMs - MATE and GNOME.

**Comment by N0rbert** [comment]
Yes, I'm ready to test snap-file.

**Comment by LyzardKing** [comment]
This is the snap, it will also install core18.
https://we.tl/1Fhtp5oUBc
Let me know if it works!
As far as I can tell the official support for core18 on build.snapcraft.org is coming, so that would enable automatic builds again if this works

**Comment by N0rbert** [comment]
$ snap install --dangerous --classic ./ubuntu-make_master_amd64.snap 
ubuntu-make master installed

$ snap list 
Name                 Version           Rev   Tracking  Developer      Notes
core                 16-2.32.8         4650  stable    canonical      core
core18               0.1               19    stable    canonical      base
software-boutique    18.04.0-5b99b84   31    stable/…  flexiondotorg  classic
ubuntu-make          master            x1    -         -              classic
ubuntu-mate-welcome  17.10.23-e4f4c4c  169   stable/…  flexiondotorg  classic

$ ubuntu-make.umake --version
18.05+snapx1

$ ubuntu-make.umake ide arduino
...
$ ubuntu-make.umake ide netbeans
...
$ ubuntu-make.umake --list-installed
arduino: The Arduino Software Distribution
	path: /home/beaver/.local/share/umake/ide/arduino
netbeans: Netbeans IDE
	path: /home/beaver/.local/share/umake/ide/netbeans

So it works on 18.04 LTS! Thank you!
