### ISSUE TITLE
Can't install on 18.04

### ISSUE THREAD

**Issue by Luke-SF** [ubuntu/ubuntu-make#567]
On new install of 18.04, I noticed it does not work installing Android Studio. I tried the Snap, apt-get, and the ppa and upgrade, and apt-get. 
Entering
`umake android`
gives a message, "Choose installation path" in ~/.local... and press enter and it returns to the $ shell.

**Comment by LyzardKing** [comment]
Hi. Can you try and run:
umake -vv android
To get a debug log

**Comment by Luke-SF** [comment]
Ok. It ends in:

Choose installation path: /home/username/.local/share/umake/android/android-studio
DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading DownloadItem(url='https://developer.android.com/studio/index.html', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): developer.android.com

**Comment by LyzardKing** [comment]
I can't replicate this issue,
@Luke-SF is it still happening to you?
if so it might have been an issue with the upstream website.

**Comment by MS10** [comment]
Hi, I'm using a fresh install of "Linux Mint 19" and I'm getting a similar issue.
That's debug output:
[https://pastebin.com/bAcm1hPU](url)
Could you help me?

**Comment by LyzardKing** [comment]
@MS10 what version of ubuntu-make are you running?

**Comment by MS10** [comment]
@LyzardKing version: 16.11.1

**Comment by MS10** [comment]
@LyzardKing I'm using now version 18.05 and it is working now. Thank you!

**Comment by LyzardKing** [comment]
Closing since it seems to be fixed in the last release
