### ISSUE TITLE
problem of ubunt-make 16.04 install arduino

### ISSUE THREAD

**Issue by eungee** [ubuntu/ubuntu-make#569]
~~$ arduino
/usr/bin/arduino: lilne 19: cd: /usr/share/arduino: No such file or directory
Error: could not find or load main class processing.app.base

i dont know how to solve this problem...

**Comment by LyzardKing** [comment]
version 16.04 is not the latest.
You have to install from the ppa

**Comment by LyzardKing** [comment]
@eungee Is this an issue with ubuntu-make?we don't install anything to /usr
With ubuntu-make everything is in the home directory by default.
Could you give more informations about the issue?
