### ISSUE TITLE
Make scriptable by adding command line args or env vars in place of prompts

### ISSUE THREAD

**Issue by marblepebble** [ubuntu/ubuntu-make#57]
Related to the idea about making docker containers, it would be easier to achieve this (and may be useful in other scenarios) if there was a way of specifying things like the install path and licence acceptance as command line args (eg. umake android --install-path=/tools/android --accept-licence).

I tried echo -e '\na\n' | umake android in a dockerfile, and it didn't work so well - ended up installed into "/-e ". (Explicitly entering a path rather than accepting the default didn't work either, I didn't get to the bottom of why not.)

**Comment by didrocks** [comment]
Thanks for the bug report!

Indeed, this will be needed and was in my head once we'll go to the docker container path for installing softwares.

Note that --install-path isn't needed as you can already: umake android /tools/android for instance :) (but we'll need the switch for accept license in the android case, as you told)
