### ISSUE TITLE
umake won't create launcher icons.

### ISSUE THREAD

**Issue by ThanosFisherman** [ubuntu/ubuntu-make#571]
I tried do install android studio and intellij via umake on linux mint 19 but I realized there is not a launcher icon on start panel as it used to be on linux mint 18.3.

Could this be a bug or am I missing something?

I use the `ppa:lyzardking/ubuntu-make` to install umake.

**Comment by LyzardKing** [comment]
The ppa is correct.
Could you check if the path for the icon in the .desktop file (in ~/.local/share/applications)
points to the icon?
I can't test it myself at the moment, but they might have changed the icon filename.

**Comment by ThanosFisherman** [comment]
I'm sorry I just realized that the launcher icon wouldn't show up until I restarted my system.

After rebooting the "Programming" Category was created and any other launchers are now created normally without any further reboots. The path in .desktop also points to the correct icon.

You can close the issue if you like. Maybe this was a linux mint-related glitch.

**Comment by LyzardKing** [comment]
The first time you run umake you have to then reinstall
for the system to read the changes in ~/.profile
It should have suggested you reboot though..
