### ISSUE TITLE
Eclipse Install ERROR: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by mchtower** [ubuntu/ubuntu-make#572]
I'm using Ubuntu 17.10 and I've installed the latest version (18.05) of make 

However, when I run umake ide eclipse I get the following error message:

ERROR: Download page changed its syntax or is not parsable

Any help resolving this would be appreciated

**Comment by LyzardKing** [comment]
it's been solved in #564 
It should be merged soon
