### ISSUE TITLE
Lighttable IDE missing library causes missing font in file dialogue boxes

### ISSUE THREAD

**Issue by dbresourcesltd** [ubuntu/ubuntu-make#573]
Ubuntu 18.04.1 LTS
umake --version: 18.05-43-gdf6d6d3
uname -a: Linux nnn 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lighttable ide installed via umake has the square character font issue in file dialogue boxes, Cloning from https://github.com/ArchI3Chris/LightTable-Square-Fix and moving libpango into ~/.local/share/umake/ide/lighttable fixes it (note although git it for arch this is generic).

Missing library then or dependency?

**Comment by LyzardKing** [comment]
As far as I can tell the version of libpango in the 18.04 repos is not supported by lighttable.
The previous ones should work, so it might work properly on 16.04 for instance.
There's not really much we can do about it...
https://github.com/LightTable/LightTable/issues/2343

**Comment by mhvelplund** [comment]
The newest version of the binary downloaded from the homepage has the same issue.

**Comment by LyzardKing** [comment]
There has been some work upstream, but there hasn't been any updated binary.
You need to contact upstream and ask them to provide a binary version with the latest updates..
