### ISSUE TITLE
Error in default android-studio.desktop configureation can be solved

### ISSUE THREAD

**Issue by KokeCacao** [ubuntu/ubuntu-make#576]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
Umake Version: 18.05

The default .desktop setup is
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Icon=/home/koke_cacao/.local/share/umake/android/android-studio/bin/studio.png
TryExec=/home/koke_cacao/.local/share/umake/android/android-studio/bin/studio.sh
Exec=android-studio
Comment=Android Studio developer environment
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-studio
```

However, it does not work and give me an error: an error has occurred.
But this configuration can solve the problem:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Icon=/home/koke_cacao/.local/share/umake/android/android-studio/bin/studio.png
Exec=/home/koke_cacao/.local/share/umake/android/android-studio/bin/studio.sh
Comment=Android Studio developer environment
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-studio
```

**Comment by LyzardKing** [comment]
Hi @KokeCacao 
Did you restart/logout after the install?

**Comment by KokeCacao** [comment]
> Hi @KokeCacao
> Did you restart/logout after the install?

Indeed, no. But how does it matter in ubuntu?

**Comment by LyzardKing** [comment]
ubuntu-make adds a folder (.local/share/umake/bin) to the PATH.
In that folders are the symlinks to the installed programs, so that you can 
start them from the terminal for example.
So if you restart/logout it will read the change to the PATH and then the .desktop file will work

**Comment by KokeCacao** [comment]
Thanks a lot.
