### ISSUE TITLE
Not updating build

### ISSUE THREAD

**Issue by programmin1** [ubuntu/ubuntu-make#581]
I've been trying to reinstall update over very old Android sdk setup... it gives an error and apparently it will not install newer Umake on my 14.04 laptop?

```
$ umake android
Android Studio is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)] y
Choose installation path: ~/tools/android/android-studio
ERROR: Download page changed its syntax or is not parsable (url missing)

Your currently installed version (17.03) differs from the latest release (18.09)
Many issues are usually fixed in more up to date versions.
To get the latest version you can read the instructions at https://github.com/ubuntu/ubuntu-make


$ sudo snap install ubuntu-make --classic
ZOE ERROR (from /usr/lib/snap/snap): zoeParseOptions: unknown option (--classic)
ZOE library version 2006-07-28

```

**Comment by LyzardKing** [comment]
The snap is currently not working.
We are waiting for changes on the build.snapcraft.io system (the core18 integration)
As for the ppa, it doesn't have the build for 14.04 since there are some packages needed that are missing from the repos.

**Comment by programmin1** [comment]
That makes sense, same thing on an Ubuntu 18 system.
What does that mean for installing Android studio with umake on 14.04?

**Comment by LyzardKing** [comment]
At the moment you could pull from git and run bin/umake in the repo...
(if you have python3-argcomplete installed from the old ppa)
I'm waiting for snapcraft to be updated to version 3.0 so I can get the snap fixed..

**Comment by programmin1** [comment]
Thanks. When will the latest update be up?

**Comment by LyzardKing** [comment]
The ppa linked in the readme.md has the latest successful build from master, but again, not for trusty.
The snap is waiting for the new snapcraft release.
The official ppa (aka the older one) has the proper releases.

**Comment by LyzardKing** [comment]
@programmin1 
Just out of curiosity...does the snap work on 14.04 if you only install that and not the deb?

**Comment by programmin1** [comment]
Nope...
```
$ sudo snap install ubuntu-make --classic
snap "ubuntu-make" is already installed, see 'snap help refresh'
$ sudo snap refresh
All snaps up to date.
```

**Comment by LyzardKing** [comment]
what error do you get?

**Comment by programmin1** [comment]
Right now I get
$ sudo snap install ubuntu-make --classic
error: cannot communicate with server: Post http://localhost/v2/snaps/ubuntu-make: dial unix /run/snapd.socket: connect: no such file or directory

How long until this issue is fixed and Ubuntu-make is usable again??

**Comment by LyzardKing** [comment]
If you run from the repo it should work..
pull the latest git master and run bin/umake
(you need to have the dependencies installed
