### ISSUE TITLE
When the installation fails it redownloads everything again

### ISSUE THREAD

**Issue by Xerus2000** [ubuntu/ubuntu-make#582]
I wanted to install an application into /opt but realised too late that I didn't yet give myself all permissions in it. The download completed, but after downloading the installation failed. 
When I then started umake again with the exact same parameters, it started downloading everything all over again. I think it should be more robust in such cases and look for completed downloads in /tmp (maybe using the checksum) since I now have to wait multiple minutes due to my slow internet connection...

**Comment by LyzardKing** [comment]
That might not be easy to implement.
You'd need to keep track of the version available on the website and compare with the one in tmp.
So you pull the newer one.
It was discussed a while back in https://github.com/ubuntu/ubuntu-make/issues/215

**Comment by Xerus2000** [comment]
But it's not about continuing interrupted downloads and not about keeping track of versions. I simply want an easy way to retry the installation _of an already fully downloaded package_.

**Comment by LyzardKing** [comment]
Even in that case, I need to be able to verify the validity of the
downloaded part.
How do I know that it's complete, and that it's the latest version?
I could download the checksum first and use that, but some frameworks don't
have a checksum.
I'd have to keep somewhere the list of tmp files, so I know which one to use

**Comment by Xerus2000** [comment]
well, it could keep a little text file next to the downloaded file in tmp, storing whether it is finished, and then read that and use the file if applicable when trying to install again.

**Comment by LyzardKing** [comment]
The file you say would have to live in the user's .local/umake folder, and
be basically a log of the operations..

**Comment by Xerus2000** [comment]
no why would it? It is just a hint to umake that this file was already full downloaded. Once tmp is emptied, the downloaded file is cleared and the hint as well, which is the ideal behaviour.

**Comment by LyzardKing** [comment]
At the time being this is too complex to implement properly.
If there are suggestions and implementations that you would like to push to umake please open a discussion.
