### ISSUE TITLE
Idea desktop shortcut not working

### ISSUE THREAD

**Issue by Xerus2000** [ubuntu/ubuntu-make#583]
KDE Neon 5.14, umake 18.05

When installing Intellij IDEA Ultimate via umake, it generates a `.desktop` file that launches `jetbrains-idea`, however, even after reinstalling, this command does not exist. I have now manually edited the launcher to link to `LOCATION/bin/idea.sh`. Is something wrong on my computer or is this a problem in the application?

**Comment by LyzardKing** [comment]
Did you logout before trying?
After you install you have to logout and back in to enable the new symlinks

**Comment by Xerus2000** [comment]
Ah I see now. I thought I had logged out in between, but apparently not ^^
