### ISSUE TITLE
bin/umake web firefox-dev fails

### ISSUE THREAD

**Issue by Sitiomovil** [ubuntu/ubuntu-make#591]
Hi! i Have a little issue. 
I've been execute the following commands:
$ git clone https://github.com/ubuntu/ubuntu-make
$ cd ubuntu-make
$ bin/umake web firefox-dev

But the ouput is:
```
Installing Firefox Dev
/home/umatias/.local/share/umake/web/firefox-dev/firefox                       |
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/tmp/ubuntu-make/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/tmp/ubuntu-make/umake/frameworks/baseinstaller.py", line 458, in decompress_and_install_done
    self.post_install()
  File "/tmp/ubuntu-make/umake/frameworks/web.py", line 127, in post_install
    extra="StartupWMClass=Firefox Developer Edition"))
  File "/tmp/ubuntu-make/umake/tools.py", line 320, in create_launcher
    with open(launcher_path, "w") as f:
PermissionError: [Errno 13] Permiso denegado: '/home/umatias/.local/share/applications/firefox-developer.desktop'
```
What can I be doing wrong?

Thanks in advance

**Comment by LyzardKing** [comment]
I can't replicate the issue.
It looks like you don't have access to your .local folder. could you verify that you have access to `/home/umatias/.local/share/applications/`?

**Comment by Sitiomovil** [comment]
For any reason, I had not full access to applications/ folder. My Fault. Many thanks for the fast reply!
