### ISSUE TITLE
Add Getting Started Documentation

### ISSUE THREAD

**Issue by sabrehagen** [ubuntu/ubuntu-make#596]
Despite reading the README.md thoroughly, I am left finding it very hard to get started using `ubuntu-make`. I would advise adding an end-to-end tutorial for setting up a machine from scratch. This seems to be what most people want to use this project for, but there is no documentation clearly stating how to do so. Thanks!

**Comment by LyzardKing** [comment]
Do you think this would be clear enough without adding too much text?

## Usage

To run the tool and install a framework use the following command:

```sh
umake <category> <framework>
```

For example you can install the Atom editor by running:

```sh
umake ide atom
```

Some categories have default installs, like Android Studio, so you can simply run:

```sh
umake android
```

You can use `--help` to get more information and change the verbosity of the output with `-v`, `-vv`.

You can find the available frameworks with the --list command.
