### ISSUE TITLE
installing android checksum failure for sdk-tools-linux

### ISSUE THREAD

**Issue by Goddard** [ubuntu/ubuntu-make#598]
This is for the snap version of umake.

I then run 

> umake android

This is then the error
Downloading and installing requirements                                              |

> ERROR: https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip couldn't finish download: The checksum of https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip doesn't match. Corrupted download? Aborting.

**Comment by LyzardKing** [comment]
Hi, thanks for the reminder...
The fix is working on my system and it'll be pushed in a few days at most

**Comment by LyzardKing** [comment]
@Goddard The change should be live now.
If you're using the snap you can wait for me to promote to stable or refresh to edge
