### ISSUE TITLE
Add support for the rest of JetBrains IDEs

### ISSUE THREAD

**Issue by Tinche** [ubuntu/ubuntu-make#60]
Idea Ultimate, PyCharm Commercial Edition, PhpStorm, RubyMine, WebStorm, CLion.

As far as I remember they actually display the license themselves when started for the first time, so no problems there. This should be very easy with the Idea/PyCharm support we already have, assuming the hashes are located in their usual places.

I'll do this myself, one by one, but if anyone else wants to contribute this would be a great opportunity.

**Comment by syndbg** [comment]
I would like to try my luck with adding PyCharm Commercial Edition and RubyMine.

However I'll wait a bit to see where your PR #65 is going. It'll surely help me along the way.

**Comment by didrocks** [comment]
And merged!

If you need any help on where and how to start, feel free to ask! #65 is a great way to start, indeed, as you have large and medium tests into it :)

**Comment by Tinche** [comment]
Hi, @syndbg,

here's what I suggest:

1. implement the actual code
2. test manually that it works
3. write the accompanying large test, check that it passes

Now you just need to write a medium test. These tests are a little more complex since they use a special customized Docker environment. The medium test you want is basically a large test executing against a fake (our) web server, serving fake (our) files. For the medium test, I suggest:

1. scrape the download/thank you page for the product you're working on, save it in the appropriate place in the server-content directory
2. edit it to point to a fake filename
3. create the fake file by using an actual download, then stripping out libraries and stuff from it until it's ~100kb. Then replace the startup script with a similar one from our PyCharm/Idea dummy files. Also add the fake-java.sh script.
4. generate a sha256 checksum into an appropriate file (filename + ".sha256)

That's my workflow for these. Good luck!

**Comment by syndbg** [comment]
Thanks for the heads-up!  I've set up my dev venv and I will try and implement the PR in a day or so.

**Comment by didrocks** [comment]
All but CLion are now in master. CLion is opened for a great contribution, taking the other ones already merged as an example :)

**Comment by praetore** [comment]
I would like to see CLion in there :D

**Comment by tony** [comment]
I see CLion now, but not  CLion Professional yet.

**Comment by LyzardKing** [comment]
There's only one version of CLion. 
The version we install has a 30 day trial license.
Is this what you meant?
