### ISSUE TITLE
umake web firefox-dev does not install required libgtk3 dependency 

### ISSUE THREAD

**Issue by lestephane** [ubuntu/ubuntu-make#601]
Using the latest version of ubuntu-make

```bash
$ umake --version
18.09+snap498
```

And the following Vagrantfile

```vagrant
config.vm.define "firefox2", autostart: false do |firefox|
    firefox.vbguest.auto_update = false
    firefox.vm.box = "ubuntu/bionic64"
    firefox.vm.provision "shell", inline: <<-SHELL
        snap install ubuntu-make --classic
        sudo -H -u vagrant bash -c "
        umake web firefox-dev --lang en-us \\"\\${HOME}/.local/share/umake/web/firefox-dev\\" # ubuntu-make/issues/79
        echo \\"export PATH=\\${PATH}:\\${HOME}/.local/share/umake/bin\\" >> \\"\\${HOME}/.bashrc\\"
        "
    SHELL
end
```
Launching firefox fails

```bash
$ vagrant up firefox2
==> firefox2: Running provisioner: shell...
    firefox2: Running: inline script
    firefox2: ubuntu-make master from Didier Roche (didrocks) installed
...
    firefox2: Downloading and installing requirements
    firefox2: Installing Firefox Dev
    firefox2: /home/vagrant/.local/share/umake/web/firefox-dev/firefox
    firefox2: Installation done
$ vagrant ssh firefox2 -- -X
$ firefox-developer
XPCOMGlueLoad error for file /home/vagrant/.local/share/umake/web/firefox-dev/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

The head scratcher is this output by umake 

```text
firefox2: Downloading and installing requirements
```

Which is clearly not the case. Non technical users won't know how to install the dependency, so I decided to put it out there, to shed some light on whether this is by design or by omission.

**Comment by LyzardKing** [comment]
I guess this is tied to vagrant, since in a normal envoronment libgtk3 would be already installed.
In your configuration does firefox run in an empty vm?

**Comment by lestephane** [comment]
It starts from the base "ubuntu/bionic64" as mentioned. That image has no x11 packages installed.
My expectation is that ubuntu-make, like snapd install, or apt-get install just 'gets it done', installing whatever is required.

Firefox is now available through snap now, so this becomes less of an issue. Is ubuntu-make going to be superseded by snap?

**Comment by lestephane** [comment]
I see, well at least the trace of our discussion may give people pointers, if the ubuntu-make team feels this is working as designed, they can always close it. I moved on to snaps myself.
