### ISSUE TITLE
Add VSCodium

### ISSUE THREAD

**Issue by igorlakic** [ubuntu/ubuntu-make#602]
Would it be possible for someone to add [VSCodium](https://vscodium.com/) into umake? 
I assume that wouldn't be hard to do because VSCodium ([link](https://github.com/VSCodium/vscodium/releases) with binaries) is basically VSCode but without telemetry inside the binary package.

Thanks in advance!

**Comment by LyzardKing** [comment]
I think vscodium could be added. Since it's hosted on github it should be easy to set up if you want to have a go at it

**Comment by LyzardKing** [comment]
Closed with 20bd97239f8babcc2f031a4948d7883dba6be077
