### ISSUE TITLE
Unable to install android with umake

### ISSUE THREAD

**Issue by shrkamat** [ubuntu/ubuntu-make#604]
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

uname -a
Linux kamath 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

git clone https://github.com/ubuntu/ubuntu-make
cd ubuntu-make
./bin/umake --version
19.06-2-g484643b

```
./bin/umake -v android
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: clang isn't installed
INFO: android-sdk-platform-tools-common isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: libevent-dev isn't installed
INFO: libevent-openssl-2.0-5 isn't installed
INFO: libevent-openssl-2.1-6 isn't installed
INFO: libevent-openssl-2.0-5 | libevent-openssl-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 isn't installed
INFO: libevent-pthreads-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 | libevent-pthreads-2.1-6 isn't installed
INFO: libyaml-dev isn't installed
INFO: llvm isn't installed
INFO: libgc-dev isn't installed
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: libjpeg62 isn't installed
INFO: mono-devel isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jre isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jre isn't installed
INFO: clang isn't installed
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: clang isn't installed
INFO: android-sdk-platform-tools-common isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: libncurses5:i386 isn't installed
INFO: libstdc++6:i386 isn't installed
INFO: zlib1g:i386 isn't installed
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: libevent-dev isn't installed
INFO: libevent-openssl-2.0-5 isn't installed
INFO: libevent-openssl-2.1-6 isn't installed
INFO: libevent-openssl-2.0-5 | libevent-openssl-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 isn't installed
INFO: libevent-pthreads-2.1-6 isn't installed
INFO: libevent-pthreads-2.0-5 | libevent-pthreads-2.1-6 isn't installed
INFO: libyaml-dev isn't installed
INFO: llvm isn't installed
INFO: libgc-dev isn't installed
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: libjpeg62 isn't installed
INFO: mono-devel isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jre isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jre isn't installed
INFO: clang isn't installed
Choose installation path: /home/shrkamat/.local/share/umake/android/android-studio
INFO: Start downloading DownloadItem(url='https://developer.android.com/studio/index.html', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): developer.android.com
INFO: https://developer.android.com/studio/index.html download finished
INFO: All pending downloads for [DownloadItem(url='https://developer.android.com/studio/index.html', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
ERROR: Download page changed its syntax or is not parsable (url missing)
INFO: Starting new HTTPS connection (1): github.com
INFO: Starting new HTTPS connection (1): github.com

Your currently installed version (19.06-2-g484643b) differs from the latest release (19.06)
Many issues are usually fixed in more up to date versions.
To get the latest version you can read the instructions at https://github.com/ubuntu/ubuntu-make

**Comment by LyzardKing** [comment]
It's not a pretty fix, but removing the checksum verification it works in the last commit.
I'll leave this open to remind myself to add it back.

**Comment by LyzardKing** [comment]
This should be properly fixed, reintroducing the checksum, in a commit that is testing now.
I'll close since this does not apply any more.
