### ISSUE TITLE
Add terraform support

### ISSUE THREAD

**Issue by aleks-sidorenko** [ubuntu/ubuntu-make#605]
`terraform` is very popular tool nowadays for most of the backend developers and devops.
And it is updated quite often making us do a lot of extra work to update it.
So it would be really nice to have `terraform` support in `umake`.

**Comment by LyzardKing** [comment]
Welcome back @aleks-sidorenko!
I've never used terraform, but it seems to be released as zip files on their download page.
Do you feel like adding this to umake yourself? If you need anything let me know!

**Comment by aleks-sidorenko** [comment]
@LyzardKing thanks, yes I am going to work on this.
Should I create new category for those tools like `devops` or something?
