### ISSUE TITLE
installing unstable beta IDE version instead of latest stable

### ISSUE THREAD

**Issue by kristofgiber** [ubuntu/ubuntu-make#606]
I have been using these commands to auto-install pycharm-community's latest stable version on ubuntu 16.04 and it worked until now. But since a few days ago it now installs Pycharm-Community 2019.2 beta. Is this an intended change?

These are the commands I use:
```
add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
apt-get update
apt-get install --assume-yes ubuntu-make
yes | env -u SUDO_UID -u SUDO_GID umake ide pycharm "/home/pycharm-community"
```

**Comment by LyzardKing** [comment]
I can't replicate.. if I run umake ide -vv pycharm I get the 2019.1.3 download.
Do you still get the error?

**Comment by kristofgiber** [comment]
No, since yesterday it switched to 2019.2 to me and it was not beta any more. So it's not replicable at the moment. But to avoid inconsistent behavior in he future, we want to pin our pycharm version that umake installs. Is there a way to specify the version or can this feature be added?

**Comment by LyzardKing** [comment]
That's not a supported use, since it would be harder to implement.
It might be possible to add n explicit url install, but I'm not sure.

**Comment by LyzardKing** [comment]
The configuration we set, the packages we install, are tied to the latest version, so adding "archived" versions might be complex, and add possible errors. For now I don't think it's really needed, but if there are any ideas on how to add this in a sensible way please open an issue for that :)

**Comment by LyzardKing** [comment]
One thing you could do is add your own custom framework in ~/.umake/frameworks
That would be available to you like one of the defaults (for example you could call it pycharm-2019.1, so as to not override the normal one.

**Comment by kristofgiber** [comment]
@LyzardKing thank you. I would do so but I am not familiar with the inner works of umake and not sure how to start with it or even propose any ideas about it. I just imagined that if umake pulls the installation files for the latest IDE version from a certain URL then one could just add a --version flag that pulls an earlier version from the corresponding URL and then the rest of the installation  process would just go however umake installs the latest version (which I'm not familiar with).
