### ISSUE TITLE
Error installing maven

### ISSUE THREAD

**Issue by vipseixas** [ubuntu/ubuntu-make#608]
Trying to install maven yields this error:

`ERROR: https://www.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz.sha512 couldn't finish download: 404 Client Error: Not Found for url: https://www.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz.sha512
`

This file really doesn't exist in this address but there is a apache-maven-3.0.5-bin.tar.gz.sha1 there...

Ubuntu version: 18.04.2
umake version: 19.06 && 19.06-12-gdddb7a4 (master)

P.S.: Edited `umake/frameworks/maven.py` and changed `checksum_type=ChecksumType.sha265` to `checksum_type=ChecksumType.sha1` and it worked.

**Comment by LyzardKing** [comment]
Thanks for the debug!
I'll add the change and update the tests in a couple of days.

On 2 August 2019 21:11:21 CEST, Vinicius Seixas <notifications@github.com> wrote:
>Trying to install maven yields this error:
>
>`ERROR:
>https://www.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz.sha512
>couldn't finish download: 404 Client Error: Not Found for url:
>https://www.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz.sha512
>`
>This file really doesn't exist in this address but there is a
>apache-maven-3.0.5-bin.tar.gz.sha1 there...
>
>Ubuntu version: 18.04.2
>umake version: 19.06 && 19.06-12-gdddb7a4 (master)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubuntu/ubuntu-make/issues/608

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LyzardKing** [comment]
The framework was incorrectly installing an older version of maven..so the issue was a different one.
It's fixed now.
