### ISSUE TITLE
[FEATURE] Transition Snap App from Classic to Strict Confinement

### ISSUE THREAD

**Issue by NWRichmond** [ubuntu/ubuntu-make#609]
Installing ubuntu-make with Snap prompted a warning associated with the "classic" confinement level, which prompted me to read [this high-level overview of Snap confinement models](https://snapcraft.io/blog/demystifying-snap-confinement).

It seems like transitioning to the Strict confinement model would be a win for end-users.

**Comment by LyzardKing** [comment]
A strict confinement is not compatible with ubuntu-make.
The program needs to be able to interact with apt to install the necessary dependencies.
Also the frameworks installed via ubuntu-make need to be accessed by the user, and it can't be done in a strict snap.

On 3 August 2019 16:28:07 CEST, Nick Richmond <notifications@github.com> wrote:
>Installing ubuntu-make with Snap prompted a warning associated with the
>"classic" confinement level, which prompted me to read [this high-level
>overview of Snap confinement
>models](https://snapcraft.io/blog/demystifying-snap-confinement).
>
>It seems like transitioning to the Strict confinement model would be a
>win for end-users.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubuntu/ubuntu-make/issues/609

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NWRichmond** [comment]
Thank you for the explanation, which makes good sense. Seeing as the warnings from snapd gave me pause about whether or not ubuntu-make would be safe to install (surely I'm not the only one?), would it make sense to include that information in the README or some other documentation?

**Comment by LyzardKing** [comment]
Closing for now.
The reasons for a classic snap should be clear enough.
If it's needed there are many articles related to the classic snap nature of umake
