### ISSUE TITLE
GO ide?

### ISSUE THREAD

**Issue by dggonzalez1971** [ubuntu/ubuntu-make#61]
That ide can be used after installing GO from umake? the Eclipse plugin ?.
https://github.com/GoClipse/goclipse

 Thank You

**Comment by didrocks** [comment]
That can be a good one, opening that one for contribution.

Thanks for the suggestion!

**Comment by geosoft1** [comment]
You can consider this project to build a complete environment for golang programming including git support.
[https://github.com/geosoft1](https://github.com/geosoft1)

**Comment by LyzardKing** [comment]
goclipse has to be installed from eclipse as an addon/plugin
Closing because it's not something umake can really do.
One would use umake to install eclipse, then add the plugin.
