### ISSUE TITLE
Install without sudo

### ISSUE THREAD

**Issue by cdfh** [ubuntu/ubuntu-make#610]
## Summary

When running `umake` as a non-root user, I'm prompted to enter a password for sudo.

## Steps to reproduce

$  git clone https://github.com/ubuntu/ubuntu-make
$ cd ubuntu-make
$ bin/umake ide eclipse-cpp
[sudo] password for cdfh: 

## Discussion

I'm a new user to ubuntu-make, but I understand from documentation that it's meant to be run as a normal user and that it will install within the user's home directory. With this in mind, why does it need to sudo at all?

I'm reporting this as a bug for the following reasons:

a) it shouldn't need to sudo if only making local installs

b) if it _does_ need to root permissions, then it should fail with a suitable "permission denied" message, rather than asking for the user's password.

Regarding the second point: it's poor form for a program other than `sudo` to ask for a user's password as it creates an attack vector. I presume that running `umake` invokes `sudo` and so it's `sudo` not `umake` asking for my password, but I have no way of knowing this. While I trust `sudo` with my password, I wouldn't necessarily choose to disclose this password to a third-party application. Linux/Unix has a long history of tools that will fail if run with insufficient permissions (cp, for example, doesn't run `sudo` if it doesn't have sufficient permissions), and I would strongly advocate `umake` adhering to this philosophy.

## Desired behaviour

Either for `umake` to not require root at all, or, to fail with a reason ("permission denied to write to ..."). Ideally in the latter case, it might suggest to the user a fix, e.g., "Package XYZ required; run sudo apt-get install XYZ to fix."

**Comment by LyzardKing** [comment]
Ubuntu make installs the necessary dependencies, and for that it needs to run as root.
The program can then run apt with the python module and install what's needed.

**Comment by cdfh** [comment]
Right, but I still see that as a bug for the reasons above.

I would strongly advocate umake either failing (with a message indicating the unmet dependencies), _or_ succeeding by installing the dependencies at a user level rather than a system level.

My use-case is that I have an untrusted regular user who wants to run umake but doesn't have permission to sudo. I can't simply install the unmet dependencies on the user's behalf because umake doesn't communicate which they are.

Currently we have 3 package managers on ubuntu: apt, snap, and umake. However, so far as I can make out, none of those allow a regular user to install their own packages locally (i.e., within their home). Given that umake is designed to be run as a regular user and installs the target package locally, I feel that the side-effect of implicitly installing the dependencies globally represents a bug.

Perhaps umake could accept a flag such as --dry-run that would instruct the user on which packages it will attempt to install via apt, so that these can be satisfied externally should the user desire it. Even then, my belief is that umake calling sudo itself still represents a bug (I would much prefer to call umake with sudo than for umake to call sudo itself; sudo will pass the local user in the environment, so umake can still target the local user). However, implementing a --dry-run feature would nevertheless satisfy my use case while also increasing the accessibility of umake (a dry-run feature is standard on most package managers).

**Comment by LyzardKing** [comment]
It's not a bug, being that it's the intended use, so failing is not an option.
One thing that I could be open to is to add an option, like --depends, that would list the dependencies for a framework. The user in your case could be instructed to run that and install the dependencies manually...

**Comment by cdfh** [comment]
I would certainly be in favour of adding `--depends` and think it would be a strong addition to umake.

Unrelated to the discussion on `--depends` (which I confer is certainly a feature request and not a bug), my personal belief is that it would be preferable for umake to require being run as sudo and then to install on behalf of $SUDO_USER, rather than to run sudo itself. I think this would strengthen umake by making it more consistent with existing unix tools (`make install` being quite a fitting example). Other than umake, I can't think of a single non-GUI tool that itself runs sudo instead of failing if not run as sudo by the user.

**Comment by LyzardKing** [comment]
What umake does, only in case it needs to install dependencies, is restart as sudo, reverting back to the user once the files have to be written to disk.
I believe this is the easiest way for the user, and does not create a security risk.

**Comment by cdfh** [comment]
It depends on your perception; umake may be written in a secure way, but it's creating what I believe is a dangerous precedence where it becomes acceptable common practice to ask the user for their password. Normally, the user only has to remember that `sudo` and their normal login screen are secure, and that anything else should never ask their password. But now, the user has to remember that `umake` is also secure. If chrome asks my password, is that also secure? How about a chrome extension?

But anyway, it's certainly your prerogative on whether you change the behaviour, so I'll sign off here. But I might challenge you to name a single other widely-deployed command-line utility that runs `sudo` on behalf of the user, as if umake is the only one, then it perhaps suggests a compelling case to change umake's behaviour. 

Regardless of the `sudo` issue, I remain firmly in favour of your proposal to add `--depends`; I think it will be very beneficial to umake.

Thanks for following up on my issue/feature request :-)

**Comment by LyzardKing** [comment]
As I said, umake is restarting with sudo, so it's sudo that is authenticating the password, not umake itself.
If there are dependencies that need installing umake will close and run as sudo umake ...
It's doing exactly what you say it should ;)
https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/__init__.py#L244
