### ISSUE TITLE
Provide a mechanism/option for users to update stable apps without going through annoying process.

### ISSUE THREAD

**Issue by PranavBhattarai** [ubuntu/ubuntu-make#614]
I know Linux users are forced to be a nerd, but I think there should be **an option**  for those users who want to have an automatic update when there available.

How hard is this anyway?!

Uninstalling and reinstalling a new version takes time. And Time is money.

The only reason I don't use **Snap** is that they are slow in comparison to apt, .deb, PPA, etc.

**Comment by LyzardKing** [comment]
@PranavBhattarai It's not as easy as it seems,
There's an open PR (#506)that needs help if you would like to contribute.
As for why it hasn't been added yet there's a brief explanation in #74
