### ISSUE TITLE
"umake android" gives errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by carycode** [ubuntu/ubuntu-make#620]
Can we somehow fix ubuntu-make so people can install Android Studio in only 2 or 3 commands?

The instructions
at https://wiki.ubuntu.com/ubuntu-make
seem to say that I can get Android Studio installed
on Ubuntu 18.04 LTS in only 2 commands.

Those 2 commands suggested by the wiki (and the output on my Ubuntu 18 box) are:

```
$ snap install ubuntu-make --classic
ubuntu-make master from Didier Roche (didrocks) installed

$ umake android
[sudo] password for david: 
Choose installation path: /home/david/.local/share/umake/android/android-studio
ERROR: Download page changed its syntax or is not parsable (url missing)
```

details and first attempts to fix
----

That is the same error message
"ERROR: Download page changed its syntax or is not parsable"
as a previously reported issue:
https://github.com/ubuntu/ubuntu-make/issues/328
but I suspect this is a different (but perhaps similar) problem, not a regression.

```
$ uname -a
Linux david-VirtualBox 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ umake --version
19.06+snap627
```

which seems to be the latest version (https://github.com/ubuntu/ubuntu-make/releases tells me the latest version is 19.06).

I tried cloning the latest version of ubuntu-make from this github repository,
then using that to install Android Studio,
but I get a different error:

```
$ sudo apt install git
$ git clone https://github.com/ubuntu/ubuntu-make
$ cd ubuntu-make
$ bin/umake android
Traceback (most recent call last):
  File "bin/umake", line 27, in <module>
    from umake import main
  File "/home/david/Downloads/junk/ubuntu-make/umake/__init__.py", line 30, in <module>
    from .ui import cli
  File "/home/david/Downloads/junk/ubuntu-make/umake/ui/cli/__init__.py", line 22, in <module>
    import argcomplete
ModuleNotFoundError: No module named 'argcomplete'
$
```

I thought that would be easy to fix, so I followed the instructions at
https://stackoverflow.com/questions/50551997/python3-unable-to-import-argcomplete-package
and ran
```
$ python3 -m pip install argcomplete
/usr/bin/python3: No module named pip
$ sudo apt install python3-pip
$ python3 -m pip install argcomplete
Successfully installed argcomplete-1.11.1

$ bin/umake android
Traceback (most recent call last):
  File "bin/umake", line 27, in <module>
    from umake import main
  File "/home/david/Downloads/junk/ubuntu-make/umake/__init__.py", line 30, in <module>
    from .ui import cli
  File "/home/david/Downloads/junk/ubuntu-make/umake/ui/cli/__init__.py", line 27, in <module>
    from progressbar import ProgressBar, BouncingBar
ModuleNotFoundError: No module named 'progressbar'
```

so apparently it's gotten a little bit further, but now I feel like I'm playing whack-a-mole.
Is there a better way to install Android Studio?

Good luck!

**Comment by LyzardKing** [comment]
The fix was available in the snap edge branch.
Now it has been promoted to stable, so if you update the snap it'll work
