### ISSUE TITLE
upgrading to 20.04 from 19 is stuck on step

### ISSUE THREAD

**Issue by ORESoftware** [ubuntu/ubuntu-make#626]
I am not sure where to file this ticket, but my updgrade appears to be stuck here:

![Screenshot from 2020-05-07 11-41-54](https://user-images.githubusercontent.com/11139560/81332413-e9f62a80-9057-11ea-919b-92ee341cf601.png)

**Comment by LyzardKing** [comment]
This is the program "ubuntu-make", so not here :wink:
but you should probably run `ubuntu-bug update-manager`
so the system can collect the relevant information then notify the upstream developers on launchpad
