### ISSUE TITLE
Add support for AMD GPU drivers

### ISSUE THREAD

**Issue by jqadev** [ubuntu/ubuntu-make#628]
Dear Team, especially @didrocks ,

a few years ago AMD GPU proprietary driver with GUI was included in Ubuntu like Nvidia one nowadays. 
Currently AMD releases GPU proprietary driver only without GUI and Ubuntu doesn't include it, only Nvidia proprietary driver.
Of course, Ubuntu includes Mesa drivers but as an ex-user of the old pre-GCN GPU remembering AMD GPU proprietary driver included in Ubuntu I would like to have an option today with a new GPU cards to choose between AMD proprietary driver offering the best performance for now and AMDVLK and Mesa like I can between Nvidia proprietary driver and Nouveau.

Inclusion of AMD proprietary driver and AMDVLK next to Mesa could give users better accessibility of AMD drivers offering the best performance and easy choice.
Is there a chance to include AMD GPU proprietary driver and AMDVLK in Ubuntu like Nvidia and Nouveau?

**Comment by LyzardKing** [comment]
This is the repo for the ubuntu-make developer setup tool, to report a bug in Ubuntu proper you shoud open it in the relevant page in launchpad, or on the discourse forum (https://discourse.ubuntu.com/)
