### ISSUE TITLE
Sailfish and Tizen Support

### ISSUE THREAD

**Issue by SreelalChalil** [ubuntu/ubuntu-make#63]
Both sailfish Os and Tizen recommends developers to install sdk on ubuntu. Adding ubuntu make support will be worth it.

**Comment by didrocks** [comment]
Thanks for your suggestion! I guess that one can be a nice way for a new contributor to start helping on Ubuntu Make. Tagging as such :)

**Comment by LyzardKing** [comment]
Sailfish sdk is a .run based on qtcreator.
tizen has tizen studio, that also downloads a cli installer.
So at the moment it would be difficult to include in umake
