### ISSUE TITLE
Fix java.lang.IllegalArgumentException with android sdkmanager

### ISSUE THREAD

**Issue by lanzorg** [ubuntu/ubuntu-make#631]
This is how I installed android-sdk from ubuntu-make:

```sh
# Install the default-jdk package.
sudo apt install -y default-jdk

# Install the ubuntu-make package.
sudo add-apt-repository -y ppa:lyzardking/ubuntu-make
sudo apt install -y ubuntu-make

# Install the android-sdk package.
umake android android-platform-tools "${HOME}/.local/share/umake/android/android-platform-tools" --accept-license
umake android android-sdk "${HOME}/.local/share/umake/android/android-sdk" --accept-license
source "${HOME}/.profile"
yes 'y' | sdkmanager 'platforms;android-29'
sdkmanager --update
```

But I have this error (even with sdkmanager --version):

```sh
java.lang.IllegalArgumentException
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
```

**Comment by LyzardKing** [comment]
Did you try a logout?
It's a strange issue.. if it persists it might be a missing dependency, although I believe that the sdk contains all the java libraries needed

**Comment by lanzorg** [comment]
Yes, I tried logout and reboot.

It seems I have the same issue than in this stackoverflow question:
https://stackoverflow.com/questions/60440509/android-command-line-tools-sdkmanager-always-shows-warning-could-not-create-se

**Comment by LyzardKing** [comment]
It seems to be an issue with the android tools, not umake, or is the variable missing?

**Comment by lanzorg** [comment]
Here's how to make sdkmanager work with umake:

```sh
# First install android-sdk with umake.
umake android android-sdk "${HOME}/.local/share/umake/android/android-sdk" --accept-license

# We have to move the tools directory to cmdline-tools.
mkdir "${HOME}/.local/share/umake/android/android-sdk/cmdline-tools"
mv "${HOME}/.local/share/umake/android/android-sdk/tools" "${HOME}/.local/share/umake/android/android-sdk/cmdline-tools"

# Now sdkmanager is working.
"${HOME}/.local/share/umake/android/android-sdk/cmdline-tools/tools/bin/sdkmanager" --update

# TODO: Change the PATH to make sdkmanager available directly.
```

Here is the working file architecture:

![](https://framapic.org/zPyXpPLypQeb/Ret6r9BuszDx)

I don't know why Google did't fix that yet?  
But, it could be easy to implement this workaround into umake.

**Comment by adeept** [comment]
Hello,

Pls tell  the specific name of the product. 

Best!

2020-06-10 


Adeept Technical Support Team
Shenzhen Adeept Technology Co., Ltd.
E-mail: support@adeept.com
Website: www.adeept.com

   



发件人：lanzorg <notifications@github.com>
发送时间：2020-06-10 16:19
主题：Re: [ubuntu/ubuntu-make] Fix java.lang.IllegalArgumentException with android sdkmanager (#631)
收件人："ubuntu/ubuntu-make"<ubuntu-make@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Here's how to make sdkmanager work with umake:
# First install android-sdk with umake.
umake android android-sdk "${HOME}/.local/share/umake/android/android-sdk" --accept-license

# We have to move the tools directory to cmdline-tools.
mkdir "${HOME}/.local/share/umake/android/android-sdk/cmdline-tools"
mv "${HOME}/.local/share/umake/android/android-sdk/tools" "${HOME}/.local/share/umake/android/android-sdk/cmdline-tools"

# Now sdkmanager is working.
"${HOME}/.local/share/umake/android/android-sdk/cmdline-tools/tools/bin/sdkmanager" --update

# TODO: Change the PATH to make sdkmanager available directly.
Here is the working file architecture:

I don't know why Google did't fix that yet?
But, it could be easy to implement this workaround into umake.

**Comment by LyzardKing** [comment]
Fixed in commit https://github.com/ubuntu/ubuntu-make/commit/a1b1011a8953f07e23f813d93deafb9c15aa40d6
