### ISSUE TITLE
There is no ANDROID_SDK reference anymore

### ISSUE THREAD

**Issue by lanzorg** [ubuntu/ubuntu-make#632]
It seems Google changed ANDROID_SDK to ANDROID_SDK_ROOT:
https://developer.android.com/studio/command-line/variables#android_sdk_root

It seems using ANDROID_HOME only is enough.

**Comment by LyzardKing** [comment]
Thanks for the tip @lanzorg 
Could you test on your system if removing the ANDROID_SDK variable the programs (android sdkmanager, android studio) still work normally?

**Comment by lanzorg** [comment]
Removing the ANDROID_SDK variable works without any issues with this workaround:
https://github.com/ubuntu/ubuntu-make/issues/631#issuecomment-641827149

I can use sdkmanager, avdmanager and so on.
I didn't test android-studio though.

**Comment by LyzardKing** [comment]
But if we leave the variable does it work without the workaround?
I'm a bit confused by this change.. I'll test it in the next few days, but every piece of information you're giving me is very helpful.

**Comment by lanzorg** [comment]
I still have the java.lang.IllegalArgumentException error without moving the tools directory.

Archlinux users "fixed" this by creating a new package:
* https://aur.archlinux.org/packages/android-sdk/#pinned-733171
* https://aur.archlinux.org/packages/android-sdk-cmdline-tools-latest/

**Comment by lanzorg** [comment]
You should remove the deprecated android-sdk and use commandlinetools-linux for umake.
https://gist.github.com/ilkerfindik/a009da1fbc63fe0da7454b4098402e28#file-android-sh-L68

**Comment by LyzardKing** [comment]
Fixed in https://github.com/ubuntu/ubuntu-make/commit/a1b1011a8953f07e23f813d93deafb9c15aa40d6
