### ISSUE TITLE
Trouble starting eclipse-cpp

### ISSUE THREAD

**Issue by JohnBlood** [ubuntu/ubuntu-make#636]
I just installed Ubuntu Make from snap and used it to install `eclipse-cpp`. However, after it was installed, I was unable to launch it from the terminal by typing `eclipse` or `eclipse-cpp`. There was also no entry in the menu. I had to navigate to the folder where it was installed to launch it.

**Comment by LyzardKing** [comment]
Hi. Thanks for reporting this issue.
Could you verify that a file `eclipse-cpp.desktop` exists in `.local/share/applications`
and that the files for icon and try-exec exist?
