### ISSUE TITLE
Downloads folder is not opening

### ISSUE THREAD

**Issue by akshayprog** [ubuntu/ubuntu-make#638]
Make sure you try the following before submitting the issue, thank you!

- Check that umake is the latest version (https://github.com/ubuntu/ubuntu-make/releases)
- If you're not running the latest development version of Ubuntu, or a flavor based on it, add the ppa as described in the README.

Maybe the bug is fixed in the master branch? If you have all dependencies installed, you can run `umake` easily from it:

```
$ git clone https://github.com/ubuntu/ubuntu-make
$ cd ubuntu-make
$ bin/umake <your-command>
```

If all this doesn't solve the problem you're having, please submit the issue including the version of ubuntu and umake itself.
**my ubuntu version is 20.04.1**
![ubuntu issue](https://user-images.githubusercontent.com/65034321/91849274-6e109580-ec79-11ea-9325-279c9adf1c8d.png)

**Comment by akshayprog** [comment]
Do i have to reinstall ubuntu in my pc

**Comment by LyzardKing** [comment]
This is not an issue with ubuntu-make (a project to automate the installation of development toolkits and ides)
but with Ubuntu the distro. I suggest you report an issue with the integrated apport tool (`apport-bug nautilus`) or in the Ubuntu forum, at https://discourse.ubuntu.com/

**Comment by akshayprog** [comment]
Thanks, for your help
