### ISSUE TITLE
Screenshotting will freeze the dock (taskbar)

### ISSUE THREAD

**Issue by OliverPetrovic** [ubuntu/ubuntu-make#652]
Hello,
I am not sure if I can report it here, but one bug has annoyed the hell out of me:
Steps to reporduce: Open settings, appearance and turn on auto-hide-dock.
Then use Ctrl+Shift+PrtSc to do a cropped screenshot while the task bar is hovered by mouse (expanded).
It will lag the task bar and the icons will not be clickable.

I have the latest amd64 build, but it has been happening on older versions also.
- Then you can only use Super+Tab to switch between apps, or Super to search & start an app.
You need to restart pc in order to fix it. (Until you will attempt to do a screenshot again)

Thank you!

**Comment by LyzardKing** [comment]
Hi. This is the repository for the ubuntu-make project, a program to setup common tools for developers on Ubuntu.
You should probably write a post on https://discourse.ubuntu.com/ where the Ubuntu desktop team can reply

**Comment by OliverPetrovic** [comment]
Oh, okay, I will post it there.
Thank you :))
