### ISSUE TITLE
Django Installation

### ISSUE THREAD

**Issue by effattoma** [ubuntu/ubuntu-make#653]
mkdir fileName
cd fileName
sudo apt install python3-pip
pip install virtualenv
python3 -m virtualenv virtualEnvName 
ls
source virtualEnvName/bin/activate
pip3 install django==2.2.10
django-admin startproject ProjectName
cd ProjectName
python manage.py migrate
python3 manage.py runserver
python3 manage.py createsuperuser

(pip install djangorestframework
pip install django-cors-headers
python3 manage.py makemigrations
python3 manage.py migrate)

**Comment by LyzardKing** [comment]
This is not related to the ubuntu-make project.. We do not support a django installer.
