### ISSUE TITLE
Unable to install RStudio - the checksum doesn't match

### ISSUE THREAD

**Issue by N0rbert** [ubuntu/ubuntu-make#655]
This week I tried to install RStudio using `ubuntu-make` on two machines - with Ubuntu 18.04 LTS and Ubuntu MATE 21.04.
I started with version from [the PPA](https://launchpad.net/~lyzardking/+archive/ubuntu/ubuntu-make).
It fails with 

```
$ umake ide rstudio
Choose installation path: /home/h/.local/share/umake/ide/rstudio
Downloading and installing requirements                                                                                                              |
ERROR: https://download1.rstudio.org/desktop/xenial/amd64/rstudio-1.4.1106-amd64-debian.tar.gz couldn't finish download: The checksum of https://download1.rstudio.org/desktop/xenial/amd64/rstudio-1.4.1106-amd64-debian.tar.gz doesn't match. Corrupted download? Aborting.
100% |###############################################################################################################################################|
ERROR: The checksum of https://download1.rstudio.org/desktop/xenial/amd64/rstudio-1.4.1106-amd64-debian.tar.gz doesn't match. Corrupted download? Aborting.
```

Using version from master branch does not fix the issue. 
Also I have a suggestion about using deb-package instead of tar.gz.

**Comment by LyzardKing** [comment]
Thanks for the notification @N0rbert 
The checksum used on the website changed.
It should be fixed soon in master.

**Comment by LyzardKing** [comment]
It should be up now. Let me know if it works!

**Comment by N0rbert** [comment]
Thanks, @LyzardKing !

Now It installs normally. 
It tries to start on Ubuntu 18.04 LTS. But then shows the error in the interface:

> The R session process exited with code 127.
>
>ERRORS
>/home/use/.local/share/umake/ide/rstudio/bin/rsession: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
>
> ![rstudio18](https://user-images.githubusercontent.com/309456/115994347-46db4f80-a5df-11eb-965b-31e0c5f9a54c.png)

This maybe fixed by running `sudo apt-get install libpq5` . Then RStudio will launch normally.

---

On Ubuntu 20.04.2 LTS and 21.04 it does not start, because of the problem with LibSSL:

```
$ rstudio --version
rstudio: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

which [is not available](https://packages.ubuntu.com/search?suite=focal&arch=amd64&mode=exactfilename&searchon=contents&keywords=libssl.so.1.0.0) for these Ubuntu versions.

Please note that deb-version from `https://rstudio.org/download/latest/stable/desktop/bionic/rstudio-latest-amd64.deb` installs and runs normally on 18.04 LTS and 20.04 LTS versions. It does not run on 21.04, but this version is very young.

**Comment by LyzardKing** [comment]
Thanks for the help in debugging this.
It was downloading the incorrect version on recent ubuntu releases.
It should work now from master.

**Comment by N0rbert** [comment]
Great! 
Now RStudio installs normally on  18.04 LTS, 20.04 LTS, 20.10 and even 21.04.
But requires manual run of `sudo apt-get install libpq5` to operate.
This will be last needed fix.

**Comment by LyzardKing** [comment]
ah yes, I forgot to add that... although it isn't needed in 20.10 (not in my system at least).
Can you confirm it is needed only in older versions (18.04)?
Thank you

**Comment by N0rbert** [comment]
I have tested on fresh Ubuntu MATE VMs with all  versions - 18.04 LTS, 20.04 LTS, 20.10 and 21.04.
All they require manual run of `sudo apt-get install libpq5`  .

**Comment by LyzardKing** [comment]
Done.
I also added r-base as a dependency, to install the r language.
It should work on master, and I'll promote the snap to a stable build.
The ppa should autobuild in 1-2 days
