### ISSUE TITLE
Multicast not working on network

### ISSUE THREAD

**Issue by ssdeol84** [ubuntu/ubuntu-make#656]
Dear,

I'm trying to transcode rtmp h.264 live stream to mpeg2video mpegts UDP stream multicast by ffmpeg.

Problem is that stream is playing on same server but not playing on network...on network it starts and play for 1-2 seconds and stops...

How I can fix it??

**Comment by LyzardKing** [comment]
Hi. This is the repository for the ubuntu-make project, a program to setup common tools for developers on Ubuntu.
You should probably write a post on https://discourse.ubuntu.com/ where the Ubuntu desktop team can reply
