### ISSUE TITLE
Android Studio cannot be downloaded

### ISSUE THREAD

**Issue by ThanosFisherman** [ubuntu/ubuntu-make#658]
I'm having trouble downloading Android Studio and it's not the first time I've stumbled upon this error

`ERROR: Download page changed its syntax or is not parsable (url missing)`

I tried cloning the project and executing umake within the bin directory but I get the same message.

PopOS 21.04
umake version 20.04

**Comment by LyzardKing** [comment]
@ThanosFisherman This should be fixed in master.
I have a few things to add before pushing a new release, but you can use it from the git clone.
Let me know if there are other issues!

**Comment by LyzardKing** [comment]
Fixed in the latest release (21.10)
