### ISSUE TITLE
Unable to Set Screen Resolution(1920 * 1080) in Ubuntu 20.0.4

### ISSUE THREAD

**Issue by ankitp9537** [ubuntu/ubuntu-make#664]
![Screen_issue](https://user-images.githubusercontent.com/96340396/146642014-73a843d1-2ebc-46da-84f2-1fa8a8ea0cfc.jpeg)

I recently purchased a 24" LG PC. when I start my pc it shows a warning that your screen resolution is not currently set to 1920*1080. I try to solve this warning by using a terminal. but can't solve this issue. I set 1920 * 1080 new screen resolution using the below command cvt 1920 1080
```
cvt 1920 1080
sudo xrandr -0-newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
sudo xrandr --addmode VGA-1 "1920x1080_60.00"
```
After applying a new resolution still getting issues. Also, the screen does not fully fit in the monitor.
![screen_resolution](https://user-images.githubusercontent.com/96340396/146642049-019588ee-44b9-4550-ae7b-739910813f1c.png)

I also installed Nvidia Driver but still not working.

Anyone, please provide a solution to fix this issue. Thanks.

**Comment by LyzardKing** [comment]
This repo is for the ubuntu-make project, not the Ubuntu distro.
For assistance with that you should post on the ubuntu forum: https://discourse.ubuntu.com/
