### ISSUE TITLE
I am using ubuntu and I encountered such a problem, if anyone knows the solution, please reply

### ISSUE THREAD

**Issue by oaltikulac037** [ubuntu/ubuntu-make#666]
![IMG_20220129_003517_4.jpg](https://user-images.githubusercontent.com/98621735/151629594-331fea9f-2433-442c-ba3a-ee2c830e55f4.jpg)

**Comment by LyzardKing** [comment]
This repo is for the ubuntu-make project, not the Ubuntu distro.
For assistance related to the Ubuntu distro you should post on the ubuntu forum: https://discourse.ubuntu.com/
