### ISSUE TITLE
File listing must be displayed as per file creation date

### ISSUE THREAD

**Issue by shahidkarimizyte** [ubuntu/ubuntu-make#669]
IT IS SIMPLE

Recent file must be displayed on the top in the file explorer. Cuttently it's a black hole
![Screenshot from 2022-04-26 00-29-08](https://user-images.githubusercontent.com/87693391/165160412-bfe27d71-295f-46c8-9294-23bb3f765de8.png)

**Comment by LyzardKing** [comment]
This repo is for the ubuntu-make project, not the Ubuntu distro.
For assistance related to the Ubuntu distro you should post on the ubuntu forum: https://discourse.ubuntu.com/

In your screenshot the files are sorted by name. You can click on the "Modified" on the right to sort it by date
