### ISSUE TITLE
Umake snap bash completion has no completions 

### ISSUE THREAD

**Issue by notetiene** [ubuntu/ubuntu-make#670]
Using Ubuntu 20.04 and installing the snap package (`20.04+snap851` or snap version 938 from latest/edge), the bash completion doesn't work.  Manually loading `/usr/share/bash-completion/completions/umake` also doesn't solve the issue.

Typing:
```
$ umake <tab>
```
doesn't yield any results.

**Comment by notetiene** [comment]
I also tried the version from the master branch (while executing `enable_completion`) and nothing is working.

**Comment by LyzardKing** [comment]
@notetiene  sorry for the delay in replying.
The snap used to work with autocomplete. I haven't found the time to solve this atm.
It's unclear to me what I should change.

I'll leave this issue open if somebody wants to look into it

**Comment by LyzardKing** [comment]
This should be fixed with https://github.com/ubuntu/ubuntu-make/commit/6dbfb847480cb12682624ea2dbb826b2ec0f985b

There will be an update to the ppa/snap soon(ish)
