### ISSUE TITLE
How do I install android studio canary version?

### ISSUE THREAD

**Issue by Cyberavater** [ubuntu/ubuntu-make#672]
Is the android studio canary version added or maybe any plans for it? Thanks!

**Comment by Cyberavater** [comment]
Also, I don't see flutter on the list. Can we get flutter SDK as well? Thanks again.

**Comment by LyzardKing** [comment]
Flutter should already exist in the latest version.
Andriod Studio Canary should be easy enough to implement, by adding a flag like we do for other IDEs
