### ISSUE TITLE
Turn off display and then turn on my browser tabs and application forced out

### ISSUE THREAD

**Issue by jmbaa** [ubuntu/ubuntu-make#675]
Sometimes I need to get up for my own business. I just turn off screen. And come back my computer then turn on display. it forced stop all my applications which means brave browser, terminals, code editer etc. Like a just starting computer there is no any browser, terminal. So I open browser, it says "Restore tabs?" What the hell is going on?

jambaa@dell:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by LyzardKing** [comment]
This repo is for the ubuntu-make project, not the Ubuntu distro.
For assistance related to the Ubuntu distro you should post on the ubuntu forum: https://discourse.ubuntu.com/
