### ISSUE TITLE
Getting "ModuleNotFoundError: No module named 'umake'" on Debian 11

### ISSUE THREAD

**Issue by N0rbert** [ubuntu/ubuntu-make#677]
Steps to reproduce:
1. Have Debian 11 installed
2. Install Snap by `sudo apt-get install snapd`
3. Install Ubuntu Make using `sudo snap install ubuntu-make --classic`
4. Try to install Arduino as example by `export PATH=$PATH:/snap/bin; umake electronics arduino`

Expected results:
* arduino is installed

Actual results:
* arduino is not installed, got error instead
```
$ umake electronics arduino
Traceback (most recent call last):
  File "/snap/ubuntu-make/956/bin/umake", line 5, in <module>
    from umake import main
ModuleNotFoundError: No module named 'umake'
```

Details about the system:

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ snap --version
snap    2.57.4
snapd   2.57.4
series  16
debian  11
kernel  5.10.0-19-amd64

$ snap list 
Name         Version   Rev    Tracking       Publisher   Notes
core20       20221027  1695   latest/stable  canonical✓  base
snapd        2.57.4    17336  latest/stable  canonical✓  snapd
ubuntu-make  master    956    latest/edge    didrocks    classic
```

**Comment by LyzardKing** [comment]
I believe there is an issue with using the core20 base snap.
For now I might revert it back to core18 while I debug it

**Comment by LyzardKing** [comment]
@N0rbert This should work in the latest snap (not yet built)

**Comment by N0rbert** [comment]
Thanks! 
Rev. 961 solves the issue on Debian 11, but I get problem about *adduser* command (see https://github.com/ubuntu/ubuntu-make/issues/385#issuecomment-1323379892 there).
