### ISSUE TITLE
Plug and Play USB VGA adapters

### ISSUE THREAD

**Issue by sshcli** [ubuntu/ubuntu-make#685]
I'm not sure if this is the right repo, sorry if not.

I just want to report this big issue to the Ubuntu community
95% of USB VGA adapters sold on internet are not compatible with Ubuntu
I was a Windows user for more than 20 years, now I'm using Ubuntu, and really love it. (You are doing a great job!)
So far, IMHO, the only thing left that Ubuntu should implement to beat Windows in all aspects, is the Plug and Play USB VGA adapters

I was using a USB VGA adapter with Windows without any problems, drivers were automatically installed.
I can't use it on Ubuntu, it has been impossible for me.
 
Again, if this is not the right repo, please point me to the right place to report this issue.

Thanks in advance.

Regards,

**Comment by LyzardKing** [comment]
This repo is for the ubuntu-make project, not the Ubuntu distro.
For assistance related to the Ubuntu distro you should post on the ubuntu forum: https://discourse.ubuntu.com/
