### ISSUE TITLE
Add support for Brackets editor

### ISSUE THREAD

**Issue by marcoceppi** [ubuntu/ubuntu-make#7]
http://brackets.io/

**Comment by MikeChou** [comment]
The official package from brackets.io won't install on Ubuntu 16.04 and above due to a dependency problem I think. 
But the one from this ppa works great:
[https://launchpad.net/~webupd8team/+archive/ubuntu/brackets](url)

**Comment by LyzardKing** [comment]
brackets only releases a deb.
If we can get a tarfile (it's been asked for in the past I think) we can include it in umake.
