### ISSUE TITLE
Ubuntu 22.04 PXE boot with autoinstall

### ISSUE THREAD

**Issue by sqsous** [ubuntu/ubuntu-make#700]
Hello,
I am trying to pxe boot ubuntu 22.04 with autoinstall,
this my user-data file 
![image](https://github.com/ubuntu/ubuntu-make/assets/84263110/3cf6f158-a2ff-4a46-9d6d-0c3b61e38f74)
![image](https://github.com/ubuntu/ubuntu-make/assets/84263110/ee70a037-7893-4643-9368-1c5118a09719)
![image](https://github.com/ubuntu/ubuntu-make/assets/84263110/54254a3e-3de2-4faa-bd91-38c1a2ec15ed)
this user-data I got from a test bare-metal that I installed also using PXE boot but without the autoinstall ( I modified the user-data a bit )
but this is the error I get when it tires to autoinstall 
![image](https://github.com/ubuntu/ubuntu-make/assets/84263110/d115511f-e4ba-4a4f-bc63-a14045fab256)
I am not sure what is the issue
thanks for help, in advance :))

**Comment by LyzardKing** [comment]
This is the repository for the ubuntu-make took, not for the ubuntu distro.
You should report this issue on the ubuntu forum at https://discourse.ubuntu.com/
