### ISSUE TITLE
Unable to install Android-Studio in Ubuntu 15.04 (Ubuntu-make 0.6)

### ISSUE THREAD

**Issue by dggonzalez1971** [ubuntu/ubuntu-make#76]
"ERROR: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gccgo-5/gcc-5-base_5-20150202-0ubuntu1_i386.deb 404  Not Found [IP: 91.189.91.24 80]"
Ubuntu 15.04 Daily Build 20150228

**Comment by didrocks** [comment]
It seems this has been a transient failure while you downloaded it, right?

I don't see that happening above the daily tests or when trying this manually here (on trusty and vivid).  Can you please confirm?

**Comment by dggonzalez1971** [comment]
The error message is shown before and after starting the download. If you want I can capture video and hit the link.

**Comment by didrocks** [comment]
Seems like your apt database isn't refreshed, can you try apt-get update, and apt-cache policy gcc-5-base? (paste the result here) and retry?

**Comment by dggonzalez1971** [comment]
Solved after updating
before upgrade
cc-5-base:
  Instalados: 5-20150202-0ubuntu1
  Candidato:  5-20150228-1ubuntu1
  Tabla de versión:
     5-20150228-1ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
 *** 5-20150202-0ubuntu1 0
        100 /var/lib/dpkg/status
after upgrade

gcc-5-base:
  Instalados: 5-20150228-1ubuntu1
  Candidato:  5-20150228-1ubuntu1
  Tabla de versión:
 *** 5-20150228-1ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status
Thanks
