### ISSUE TITLE
Support a full Oracle Java stack from upstream

### ISSUE THREAD

**Issue by castrojo** [ubuntu/ubuntu-make#8]
webup8 maintains a PPA that install's Oracle Java: http://www.webupd8.org/2014/03/oracle-java-8-stable-released-install.html

There are likely some issues we'd need to resolve (accepting a license), etc., but there's a clear demand for people who just want Oracle Java. Here's the manual way people do it: http://askubuntu.com/questions/56104/how-can-i-install-sun-oracles-proprietary-java-jdk-6-7-8-or-jre

This is long and error prone, it would be awesome if udtc could just automate this entirely.

**Comment by LyzardKing** [comment]
Closing since it hasn't been implemented since, and it now requires a login on the oracle website.
