### ISSUE TITLE
No option to install Firefox Developer Edition in other languages than English

### ISSUE THREAD

**Issue by marcinant** [ubuntu/ubuntu-make#80]
As in topic. 

Firefox Developer Edition is available in localized versions. It could be nice to have an ability to install localized version with umake.

**Comment by didrocks** [comment]
Good idea! Seems like that can be an easy contribution, let's open that to any volounteer :)

**Comment by didrocks** [comment]
This one is implemented as of Ubuntu Make 0.9.2 with a lang question and a --lang= for command-line only.
