### ISSUE TITLE
Can't un-install once an app no longer supported

### ISSUE THREAD

**Issue by popey** [ubuntu/ubuntu-make#83]
I installed ADT eclipse some time ago, but that's since been removed from umake. I can now no longer use umake to remove ADT eclipse as a result.

Perhaps when apps are deprecated they should be switched to a "remove-only" mode rather than completely remove them from umake.

**Comment by didrocks** [comment]
And done! As long as the framework is installed, you should see it in shell completion and in --help. If you try to reinstall it, it will say you can't.

Once the framework is removed from your machine, you shouldn't get it anymore neither in shell completion, in --help, like if it never existed (you will note as well that the error message when trying to install it will be different as well).

if you want to try it before release, you can git clone trunk and run:
$ . enable_completion
(to get shell completion working from trunk)
$ bin/umake <…>

**Comment by didrocks** [comment]
(just to reword: it will always been shown in shell completion for now, need to have a look on how to do this in a lightweight way), however --help will work as described
