### ISSUE TITLE
How to Uninstall Android Studio Completely via Ubuntu Make

### ISSUE THREAD

**Issue by vaibhavmule** [ubuntu/ubuntu-make#86]
Please answer here OR at http://askubuntu.com/questions/613429/how-to-uninstalled-android-studio-if-i-installed-via-ubuntu-make

**Comment by Tinche** [comment]
Hi,

I've answered your question on the Ask Ubuntu page. This isn't really an issue in Ubuntu Make, so I'm gonna suggest closing this.

**Comment by vaibhavmule** [comment]
Thanks.

**Comment by pavankumarAN** [comment]
Can you please tell this for ubuntu 18.04? @vaibhavmule @Tinche

**Comment by LyzardKing** [comment]
@pavankumarAN the reply on the askubuntu page is still valid. 
you simply run the umake command with "-r" added to it.
If you have a problem please open a new issue.
