### ISSUE TITLE
New Ubuntu Logo

### ISSUE THREAD

**Issue by Operation420** [ubuntu/ubuntu-make#87]
This logo is the same one we all know and love, but with a few additions to emphasize what the community is about, humanity, or as it's known in African, **Ubuntu**.

![image](https://cloud.githubusercontent.com/assets/11903487/7329079/cb05a8e0-ea98-11e4-852c-d39985e6e235.png)

**Comment by didrocks** [comment]
This isn't the official ubuntu logo.

**Comment by Operation420** [comment]
> This isn't the official ubuntu logo.

@didrocks Have you ever heard of a feature suggestion?

And it is the Ubuntu logo, you can see the three guys there

**Comment by Tinche** [comment]
@didrocks I suggest reporting this account for abuse.

**Comment by Operation420** [comment]
Abuse what are you talking about troll?

**Comment by didrocks** [comment]
@Tinche: done

**Comment by Operation420** [comment]
WTF you must have didrocks alright, you cannot even answer a simple question and join this troll

**Comment by Operation420** [comment]
You can do that but can't type to answer questions, what do you have against Open Source?
