### ISSUE TITLE
Allow compile from source for Golang

### ISSUE THREAD

**Issue by m3talsmith** [ubuntu/ubuntu-make#89]
It would be nice to have the latest stable go running, which would mean pulling form the release branch of 1.4 right to get 1.4.3. umake would have to include point to https://github.com/golang/go/archive/release-branch.go1.4.zip -> unzip -> cd in && make, which is time consuming, but it would be a nice option.

**Comment by didrocks** [comment]
Thanks for your feedback!
ubuntu make isn't supposed to be something compiling, (at least on the client side), but rather delivering a tested ready-to-use environment for the user.

I wonder why go 1.4.3 doesn't have binaries as it's a release ready to pull?

Another way (which is where I think Ubuntu Make should go), is to do that work daily server-side, prepare some containers that are validated, and then, offering that for download to the user. Keeping that as an enhancement opportunity opened to any enthousiast contributor :)

**Comment by m3talsmith** [comment]
I like your idea @didrocks :+1:
