### ISSUE TITLE
Print a better Eclipse download error on server-side error.

### ISSUE THREAD

**Issue by leogaggl** [ubuntu/ubuntu-make#90]
I am getting the following error trying to install Eclipse:

ERROR: https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5&r=1 couldn't finish download: 404 Client Error: Not Found
ERROR: 404 Client Error: Not Found
CRITICAL: Exception in worker
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/umake/network/download_center.py", line 125, in _fetch
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 825, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 65, in _worker
    work_item.run()
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 56, in run
    self.future.set_exception(e)
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 504, in set_exception
    self._invoke_callbacks()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3/dist-packages/umake/network/download_center.py", line 185, in _one_done
    self._done()
  File "/usr/lib/python3/dist-packages/umake/network/download_center.py", line 193, in _done
    self._done_callback(self._downloaded_content)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 83, in done
    UI.return_main_screen()
  File "/usr/lib/python3/dist-packages/umake/ui/__init__.py", line 35, in return_main_screen
    cls.currentUI._return_main_screen(status_code=status_code)
  File "/usr/lib/python3/dist-packages/umake/ui/cli/__init__.py", line 53, in _return_main_screen
    MainLoop().quit(status_code=status_code)
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 141, in quit
    raise self.ReturnMainLoop()
umake.tools.ReturnMainLoop

Ubuntu make seems to be working OK otherwise - Android Tools installed fine.

Cheers,
Leo

**Comment by didrocks** [comment]
Thanks for reporting this bug.

It seems it was a temporary 404 from eclipse's website. I don't get it here, do you mind retrying? I guess the error message could be a little bit better handled to remove the stacktrace and only print "HTTPError: 404 Client Error: Not Found", what do you think?

**Comment by Tinche** [comment]
Hi,
my first thought was that the Eclipse folks changed the URLs, but it actually works for me. Running
```
$ curl 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5&r=1' -v
* Hostname was NOT found in DNS cache
*   Trying 198.41.30.198...
* Connected to www.eclipse.org (198.41.30.198) port 443 (#0)
* TLS 1.0 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate: *.eclipse.org
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /downloads/download.php?file=/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5&r=1 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.eclipse.org
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Tue, 28 Apr 2015 09:09:31 GMT
* Server Apache is not blacklisted
< Server: Apache
< Cache-control: no-cache, max-age=86400
< Location: http://mirrors.uniri.hr/eclipse//technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5
< Expires: Wed, 29 Apr 2015 09:09:31 GMT
< Access-Control-Allow-Origin: http://eclipse.org ; https://eclipse.org ; http://www.eclipse.org ; https://www.eclipse.org
< Access-Control-Allow-Methods: GET
< X-NodeID: (null)
< X-Frame-Options: SAMEORIGIN
< Vary: Accept-Encoding
< Content-Length: 0
< Content-Type: text/html; charset=utf-8
<
```
This URL will actually redirect to a chosen proxy, presumably near to you. Try running the same command as me (curl) and see what happens. It's possible the proxy chosen for you doesn't have the file; in that case this should be reported to Eclipse.

**Comment by leogaggl** [comment]
Thanks for the quick reply ! I agree that some more shorter error message would be nice ! 

Personally I would find it usefully if it actually includes the URL that is throwing the 404 - as it makes troubleshooting a lot easier.

Turns out that this is a problem with Eclipse's geographic mirrors. The mirror I am getting is http://mirror.aarnet.edu.au/pub/eclipse/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5 - which actually throws the 404.

Not sure how you guys could prevent that. Probably similar to the APT retry mechanism that it tries the next mirror if it returns a 404. Or default to the Eclipse Main DL site perhaps ?

Thanks for your help - keep up the great work !

**Comment by leogaggl** [comment]
Been re-trying this a few times, but unfortunately the AARNET mirror seems not to sync that file properly and returns a 404.

I might have to override the URL in /usr/lib/python3/dist-packages/umake/frameworks/ide.py

**Comment by didrocks** [comment]
Please contact the eclipse foundation for the mirror, we don't have a list of available mirrors, it's all done server-side and I don't really fancy a duplicated version (because of the maintainance cost: it's going to break).

On the other issue (error showing up on the stacktrace), it happened that an annotation was missing on the download function (@MainLoop.in_mainloop_thread), so 2 exceptions were raised in a row if the download doesn't complete and you didn't get the nice wrapping. This only happened in one framework: the eclipse ide one, congrats for finding it :p

You will get something like:
ERROR: An error occurred while downloading <url>: 404 Client Error: Not Found

Fixing it in trunk (referencing and renaming this bug report).
