### ISSUE TITLE
List supported platforms somewhere

### ISSUE THREAD

**Issue by PuZZleDucK** [ubuntu/ubuntu-make#91]
It would be nice to list the supported platforms somewhere (anywhere!) in the readme or wiki. Lots of places mention Go and Android, I found one blog that mentioned Stencyl and command line completion indicated Dart, Web (web what? firefox or HTML/php) and Ide (which ide?). Thats only 6.
However the Ubuntu 15.4 release notes actually lists all 15 (and 8 are IDEs, so which will I install with the ide target).
Maybe a --list option could show the possible targets or the docs could better explain how this is all organized (like does the ide trget install all 8 IDEs?).

**Comment by didrocks** [comment]
Thanks for your feedback!
You can simply run:
umake --help.

That list all the categories and platforms supported, with a short description of each and the commande to run to install them. Is that what you were looking for?

**Comment by didrocks** [comment]
Note that there are categories and platforms. You can even umake <category> <tabtab> to complete all platform from each category.
We also write "default" if a platform is the default of a category (so "umake go" and "umake go go-lang" are equivalent).

**Comment by PuZZleDucK** [comment]
Oh wow... that's exactly what I was looking for... and more :D 
Looks like I FTRTFHelp Page, sorry 'bout that.

**Comment by didrocks** [comment]
no worry, happy that's exactly what you expected ;)
