### ISSUE TITLE
Should support VS Code :)

### ISSUE THREAD

**Issue by popey** [ubuntu/ubuntu-make#92]
(once it releases)

It would be awesome to be able to install Visual Studio Code onto Ubuntu using umake. Currently not yet released, and requires a Live / Outlook account to get in.

https://code.visualstudio.com

**Comment by Tinche** [comment]
The download link is here: http://download.microsoft.com/download/0/D/5/0D57186C-834B-463A-AECB-BC55A8E466AE/VSCode-linux-x64.zip. Don't know how permanent that is.

Note that this piece of software isn't free. The license is here: https://code.visualstudio.com/License, so this should be shown to users prior to downloading and installing.

Also note that the linked license is valid "until 30/04/2016 (day/month/year) or next public release of the software, whichever is first."

**Comment by didrocks** [comment]
Hehe, double emails in my inbox about it! I'm having a look. Thanks Popey for the warning and Tinche for the links (yeah, unsure as well how permanent this url is). Happy that we have all the infra to show the license though :)

**Comment by didrocks** [comment]
Support (without tests for now) is now available. However, the website is just down, waiting a little bit to give it a real try :)

**Comment by didrocks** [comment]
Now that the server is up again and I mock the user agent (or I'm getting an asp.net stacktrace with a 500 error), I can get the large and medium tests running!

The new docker image is pushed as well.
Coming to a release near you :)
