### ISSUE TITLE
Previous installation

### ISSUE THREAD

**Issue by raulsperoni** [ubuntu/ubuntu-make#93]
Hi, maybe this is a dumb question, im changing my laptop but im keeping my /home . I've used make to install android studio and intellij, can i use this files or i'll need to download everything again?

thx!

**Comment by Tinche** [comment]
Pretty much all the files are in /home, (some in ~/tools, some in .local/share/applications, maybe some elsewhere) but we also install some dependencies using the normal apt-get toolchain - like Java for Eclipse, etc. So I'd recommend just installing again from scratch.

**Comment by raulsperoni** [comment]
ok thanks!
