### ISSUE TITLE
Support for Mono and Mono Develop

### ISSUE THREAD

**Issue by silviucc** [ubuntu/ubuntu-make#94]
It would be nice if support for Mono and Mono Develop would be added. Please consider it :)

**Comment by jayrulez** [comment]
:+1:

**Comment by didrocks** [comment]
A nice opportunity for new contributors, tagging as such! Thanks for the suggestion :)

**Comment by LyzardKing** [comment]
This has no archive, as far ar I can tell. If we can get an archive for monodevelop then it should be easy enough to include
