### ISSUE TITLE
Different name used to describe Stencyl in frameworks/games.py

### ISSUE THREAD

**Issue by Vdragon** [ubuntu/ubuntu-make#95]
Hi Ubuntu Make developers, 
I'm currently making zh_TW translation, and found out that frameworks/games.py uses two different strings to describe it, which cause trouble on generating the correct translation.
![_542](https://cloud.githubusercontent.com/assets/1192163/7443735/d1933d64-f194-11e4-85ba-decd39b101fe.png)

**Comment by didrocks** [comment]
Hey Vdragon,
Nice catch! One is for the ubuntu make --help description and the other one for the .desktop file (description shown in unity launcher for instance). In that case, it makes sense for both to be identical, using the first one
