### ISSUE TITLE
s/Developer/Developing/g

### ISSUE THREAD

**Issue by Vdragon** [ubuntu/ubuntu-make#96]
Hi Ubuntu Make developers, 
it seems that many strings uses "developer" term in framework names, I suggest switch to "developing" instead unless the framework itself claims to use "developer".

**Comment by Vdragon** [comment]
Related with #95

**Comment by didrocks** [comment]
That would make sense, I would however get some more opinion from a native speaker, leaving it opened here to check if we can get some. Thanks!
