### ISSUE TITLE
Man pages for umake

### ISSUE THREAD

**Issue by johnsamuelwrites** [ubuntu/ubuntu-make#98]
It will be quite useful if there are man pages for umake. Current documentation of umake is only obtained by the following command
$ umake --help

$ man umake 
No manual entry for umake
See 'man 7 undocumented' for help when manual pages are not available.

**Comment by didrocks** [comment]
Thanks for the feature request! Nice one, indeed, and can be easily dealt by anyone who wants to make a first contribution :)
